Repository testcontainers/testcontainers-go, pull requests merged in 2019-09, with the labels that each got.

#87 Using a slice of strings ([]string) for Docker Cmd.
  README.md
  container.go
  docker.go
  docker_test.go
Labels: type/bc-break

#91 Add v to release name or go modules will complain
  .github/release-drafter.yml
Labels: type/bug

#84 Added the ability to build from a Dockerfile
  README.md
  container.go
  container_test.go
  docker.go
  docker_test.go
  go.mod
  go.sum
  testresources/Dockerfile
Labels: type/feature

#94 (#93) Reset internal state after container.Terminate(), and expose InspectContainer
  docker.go
  docker_test.go
Labels: type/bug
