Repository testcontainers/testcontainers-go, pull requests merged in 2020-04, with the labels that each got.

#175 Force testcontainers to always pull images when creating container
  container.go
  docker.go
Labels: type/feature

#177 chore(vendor): update docker engine and uuid
  go.mod
  go.sum
Labels: dependencies

#180 Fix/159 wait port windows
  wait/errors.go
  wait/errors_windows.go
  wait/host_port.go
Labels: os/windows, type/bug

#176 #173: Reaper reuse
  docker.go
  docker_test.go
  generic.go
  network_test.go
  reaper.go
Labels: type/feature

#97 (#25) Create very basic implementation of Local Docker Compose
  README.md
  compose.go
  compose_test.go
  go.mod
  testresources/docker-compose-complex.yml
  testresources/docker-compose-override.yml
  testresources/docker-compose-simple.yml
Labels: type/feature

#184 docs: add example for wait http
  wait/http_test.go
Labels: type/docs
