Repository testcontainers/testcontainers-go, pull requests merged in 2020-06, with the labels that each got.

#209 Add pass-through for entrypoint to ContainerRequest
  container.go
  docker.go
  docker_test.go
Labels: type/feature

#211 Grammar and spelling fixes
  docs/features/garbage_collector.md
  docs/quickstart/gotest.md
  testing.go
Labels: type/docs, type/housekeeping

#213 use nginx when possible when writing test
  container_test.go
Labels: type/housekeeping

#215 wait strategy where not properly set
  docker_test.go
Labels: type/housekeeping, type/test-improvement

#216 add badges to readme
  README.md
Labels: type/housekeeping

#217 chore: simplify complex docker-compose file
  compose_test.go
  testresources/docker-compose-complex.yml
Labels: type/housekeeping, type/test-improvement

#218 Fix docs index
  docs/index.md
Labels: type/docs

#220 Close db connection when sql.wait is done
  wait/sql.go
Labels: type/bug

#222 github.com/docker/distribution should be an indirect dependency
  go.mod
  go.sum
Labels: dependencies
