Repository testcontainers/testcontainers-go, pull requests merged in 2021-12, with the labels that each got.

#388 docs: fix ryuk link
  docs/features/garbage_collector.md
Labels: type/docs

#368 Add wait.ExecStrategy to wait on cmd exec in a container
  wait/exec.go
  wait/exec_test.go
Labels: type/feature

#381 feat: additionally remove volumes by default on compose down
  compose.go
  compose_test.go
  testresources/docker-compose-volume.yml
Labels: type/feature

#369 Bugfix: log-consumer go-routine should recover from closed-connection
  docker.go
  logconsumer_test.go
Labels: type/bug

#392 #391: remember service map from all docker compose files
  compose.go
  compose_test.go
  testresources/docker-compose-postgres.yml
Labels: type/bug

#387 Upgrade dependencies to latest versions
  compose.go
  compose_test.go
  container.go
  container_test.go
  docker.go
  docker_test.go
  generic.go
  go.mod
  go.sum
  logconsumer_test.go
  reaper.go
  wait/host_port.go
Labels: type/housekeeping

#386 Replace ContainerRequest.BindMounts and ContainerRequest.VolumeMounts with ContainerRequest.Mounts as dedicated type
  container.go
  container_test.go
  docker.go
  docker_mounts.go
  docker_test.go
  mounts.go
  mounts_test.go
  reaper.go
Labels: type/feature, type/bc-break
