Repository testcontainers/testcontainers-go, pull requests merged in 2021-11, with the labels that each got.

#373 feat: support reading DOCKER_HOST from testcontainers props file
  docker.go
  docker_test.go
  go.mod
  go.sum
Labels: type/feature

#378 Bump runc
  go.mod
  go.sum
Labels: dependencies

#376 Updated default ryuk image to testcontainers/ryuk:0.3.3.
  reaper.go
Labels: dependencies

#354 Swap incorrect key and value of BindMounts and VolumeMounts
  docker.go
  docker_test.go
Labels: type/bc-break
