Repository testcontainers/testcontainers-go, pull requests merged in 2022-09, with the labels that each got.

#517 feat: copy directory to container
  container.go
  docker.go
  docker_test.go
  docs/features/copy_file.md
  file.go
  file_test.go
Labels: type/feature

#522 docs: add contributing guides
  docs/contributing.md
  e2e/go.sum
Labels: type/docs

#523 chore: improve issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature.yml
Labels: type/housekeeping

#514 fix(compose): wait.ForExit() strategy should work for finished containers
  compose.go
  compose_test.go
  testresources/docker-compose-short-lifespan.yml
Labels: type/bug

#524 feat: add host param to url function for wait.ForSQL
  e2e/container_test.go
  wait/sql.go
  wait/sql_test.go
Labels: type/bc-break

#526 chore: pin codecov's GH action to v3.1.0
  .github/workflows/ci.yml
Labels: dependencies, type/security

#530 chore: retire old versions of Go
  .github/workflows/ci-podman.yml
  .github/workflows/ci.yml
  e2e/go.mod
  go.mod
Labels: type/housekeeping, dependencies

#535 chore: include test flakiness in the release drafter
  .github/release-drafter.yml
Labels: type/housekeeping

#528 chore: do not skip test
  logconsumer_test.go
Labels: type/test-flakiness

#534 docs: improve consistency and fix typos
  README.md
  docs/contributing_docs.md
  docs/features/build_from_dockerfile.md
  docs/features/copy_file.md
  docs/features/docker_compose.md
  docs/features/garbage_collector.md
  docs/features/using_podman.md
  docs/index.md
  docs/quickstart/gotest.md
  testing.go
Labels: type/docs

#536 docs: add a basic layout for wait strategies in docs
  docs/features/wait/exec.md
  docs/features/wait/exit.md
  docs/features/wait/health.md
  docs/features/wait/host_port.md
  docs/features/wait/http.md
  docs/features/wait/introduction.md
  docs/features/wait/log.md
  docs/features/wait/multi.md
  docs/features/wait/sql.md
  mkdocs.yml
  wait/host_port.go
  wait/sql.go
Labels: type/docs
