Repository testcontainers/testcontainers-go, pull requests merged in 2022-11, with the labels that each got.

#610 docs: wording in project name
  docs/features/build_from_dockerfile.md
  docs/quickstart/gotest.md
Labels: documentation

#612 docs: networking basics
  docker_test.go
  docs/features/networking.md
  mkdocs.yml
Labels: documentation

#569 feat: add golangci-lint
  .github/workflows/ci.yml
  .github/workflows/golangci-lint.yml
  .golangci.yml
  README.md
  compose_api.go
  compose_local.go
  container_test.go
  docker.go
  docker_test.go
  docs/examples/cockroachdb.md
  docs/examples/nginx.md
  docs/examples/pulsar.md
  docs/examples/redis.md
  docs/features/creating_container.md
  docs/features/wait/http.md
  docs/quickstart/gotest.md
  e2e/container_test.go
  file.go
  file_test.go
  generic_test.go
  go.mod
  go.sum
  logconsumer_test.go
  network_test.go
  parallel_test.go
  reaper.go
  scripts/checks.sh
  testresources/echoserver.go
  wait/exec_test.go
  wait/exit.go
  wait/exit_test.go
  wait/health.go
  wait/http.go
  wait/http_test.go
  wait/log.go
  wait/log_test.go
  wait/sql.go
  wait/testdata/Dockerfile
  wait/testdata/go.mod
  wait/testdata/main.go
Labels: chore

#615 docs: fix syntax
  docs/examples/nginx.md
  docs/examples/pulsar.md
  docs/examples/redis.md
Labels: documentation

#617 chore: use a fixed version of MySQL
  docker_test.go
  docs/features/wait/log.md
  docs/features/wait/multi.md
Labels: chore

#623 update gotest.md - fix errors in the example
  docs/quickstart/gotest.md
Labels: documentation

#625 chore: retire podman pipeline
  .github/workflows/ci-podman.yml
Labels: dependencies, podman

#624 fix: do not prepend garbage in the container.Exec response
  container.go
  docker.go
  docker_exec_test.go
  exec/processor.go
  wait/exec_test.go
  wait/exit_test.go
  wait/log_test.go
  wait/wait.go
Labels: bug

#627 README: update `nginxC.Terminate`
  README.md
Labels: documentation

#580 feat: implement new MultiStrategy design
  docs/features/wait/multi.md
  e2e/container_test.go
  wait/all.go
  wait/all_test.go
  wait/exec.go
  wait/exit.go
  wait/health.go
  wait/host_port.go
  wait/http.go
  wait/log.go
  wait/log_test.go
  wait/nop.go
  wait/sql.go
  wait/wait.go
Labels: enhancement

#632 docs: document replace directive for Docker Compose
  docs/quickstart/gotest.md
Labels: documentation

#631 docs: remove code snippets from main README
  README.md
Labels: documentation

#630 chore: bump version in mkdocs
  mkdocs.yml
Labels: documentation

#635 fix: avoid panics when checking container state and container.raw is nil
  docker.go
  docker_test.go
Labels: bug

#637 Add firestore example
  .github/workflows/firestore-example.yml
  docs/examples/firestore.md
  examples/firestore/Makefile
  examples/firestore/firestore.go
  examples/firestore/firestore_test.go
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/firestore/tools/tools.go
  mkdocs.yml
Labels: documentation

#638 Add datastore example
  .github/workflows/datastore-example.yml
  docs/examples/datastore.md
  examples/datastore/Makefile
  examples/datastore/datastore.go
  examples/datastore/datastore_test.go
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/datastore/tools/tools.go
  mkdocs.yml
Labels: documentation

#639 chore: adjust generator for the docs site
  docs/examples/index.md
  examples/_template/go.mod.tmpl
  examples/main.go
  examples/main_test.go
Labels: chore
