Repository testcontainers/testcontainers-go, pull requests merged in 2022-10, with the labels that each got.

#541 issue #537 Rename the wait/multi.go file to wait/all.go
  wait/all.go
Labels: type/housekeeping

#539 chore: add CONTRIBUTING file
  CONTRIBUTING.md
  docs/bounty.md
Labels: type/docs

#542 chore: add emoji to breaking changes in release drafter
  .github/release-drafter.yml
Labels: type/housekeeping

#556 chore: use hashed versions of test-summary action
  .github/workflows/ci-podman.yml
  .github/workflows/ci.yml
  .gitignore
  Makefile
  e2e/Makefile
Labels: dependencies, type/security

#560 fix container NetworkMode usage
  docker.go
  docker_test.go
Labels: type/bug

#555 Support for cap-add/cap-drop
  container.go
  docker.go
  docker_test.go
Labels: type/feature

#562 Add system requirements parent docs page for podman and colima
  mkdocs.yml
Labels: type/docs, hacktoberfest

#564 Update testcontainers/ryuk version to 0.3.4
  reaper.go
Labels: dependencies

#565 docs: add general Docker requirements
  docs/system_requirements/index.md
  docs/system_requirements/using_colima.md
  docs/system_requirements/using_podman.md
  mkdocs.yml
Labels: type/docs

#553 Support returning all IP addresses of a container
  container.go
  docker.go
  docker_test.go
Labels: type/feature

#558 fix: use regex to find container by name
  docker.go
  docker_test.go
Labels: type/bug

#566 chore: proper messaging on disabling ryuk
  docker.go
  docs/features/garbage_collector.md
Labels: type/docs, type/housekeeping

#570 feat: add sessionID HTTP Header to the Docker client setup
  docker.go
  reaper.go
  reaper_test.go
  session.go
Labels: type/feature

#574 fix: check if the container request if for the reaper
  docker.go
Labels: type/bug

#575 fix: edit link in documentation
  mkdocs.yml
Labels: type/docs

#576 chore: check error message in parts when testing the CreateContainerWithDirs method
  docker_test.go
Labels: type/test-improvement

#577 fix: better error message in tests
  docker_test.go
Labels: type/test-improvement

#476 425 support native docker compose api
  compose.go
  compose_api.go
  compose_api_test.go
  compose_local.go
  compose_test.go
  docker.go
  docs/features/docker_compose.md
  e2e/go.mod
  e2e/go.sum
  generic_test.go
  go.mod
  go.sum
  testresources/docker-compose-build.yml
  testresources/docker-compose-override.yml
  testresources/docker-compose-postgres.yml
Labels: type/feature, compose

#586 chore: sync governance files
  .github/release-drafter.yml
  .github/settings.yml
  docs/contributing.md
  docs/contributing_docs.md
Labels: type/docs, type/housekeeping

#589 chore: sync governance files
  .github/release-drafter.yml
  .github/settings.yml
Labels: documentation

#591 feat: log docker info from compose
  compose.go
  docker.go
Labels: compose, enhancement

#593 fix: support parallel execution of reusable containers
  generic.go
  parallel_test.go
Labels: bug

#596 feat: bump version of test-summary
  .github/workflows/ci.yml
Labels: dependencies

#598 docs: Rename the MkDocs site name to match other Testcontainers languages
  docs/index.md
  mkdocs.yml
Labels: documentation

#599 docs: add languages to docs site
  README.md
  docs/css/extra.css
  docs/features/build_from_dockerfile.md
  docs/features/docker_compose.md
  docs/features/garbage_collector.md
  docs/features/wait/introduction.md
  docs/index.md
  docs/language-logos/dotnet.svg
  docs/language-logos/go.svg
  docs/language-logos/java.svg
  docs/language-logos/nodejs.svg
  docs/language-logos/python.svg
  docs/language-logos/rust.svg
  docs/logo.png
  docs/system_requirements/using_colima.md
  docs/system_requirements/using_podman.md
Labels: documentation

#597 add example of using Pulsar with testcontainers-go
  docs/examples/pulsar.md
  mkdocs.yml
Labels: documentation
