Repository testcontainers/testcontainers-go, pull requests merged in 2022-08, with the labels that each got.

#491 Return container IP when attached to a single named network
  docker.go
  docker_test.go
Labels: type/bug

#493 chore: retire non-supported Go versions
  .github/workflows/ci-podman.yml
  .github/workflows/ci.yml
Labels: type/housekeeping, dependencies

#501 chore: add issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/discussions.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/slack.yml
Labels: type/housekeeping

#424 Update go-redis to v8.11.5
  docker_test.go
  go.mod
  go.sum
Labels: dependencies
