Repository testcontainers/testcontainers-go, pull requests merged in 2022-12, with the labels that each got.

#649 chore: run go mod tidy for all examples
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/nginx/go.mod
  examples/nginx/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/pulsar/go.mod
  examples/pulsar/go.sum
  examples/redis/go.mod
  examples/redis/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
  examples/toxiproxy/go.mod
  examples/toxiproxy/go.sum
Labels: dependencies

#658 chore: format dependabot using go-yaml indents
  .github/dependabot.yml
Labels: chore

#667 chore: update mkdocs format to go-yaml v3
  mkdocs.yml
Labels: chore

#668 chore: group dependabot updates
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
Labels: dependencies

#670 Improve datastore, firestore, pubsub and spanner tests
  examples/datastore/datastore_test.go
  examples/firestore/firestore_test.go
  examples/pubsub/pubsub_test.go
  examples/spanner/spanner_test.go
Labels: documentation

#672 chore: run go mod tidy in examples
  docs/examples/index.md
  examples/Makefile
  examples/datastore/go.mod
  examples/firestore/go.mod
  examples/nginx/go.mod
  examples/nginx/go.sum
  examples/pubsub/go.mod
  examples/pulsar/go.mod
  examples/pulsar/go.sum
  examples/redis/go.mod
  examples/redis/go.sum
  examples/spanner/go.mod
  examples/toxiproxy/go.mod
  examples/toxiproxy/go.sum
Labels: dependencies

#699 chore(deps): bump google.golang.org/api from 0.104.0 to 0.105.0
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
Labels: dependencies

#702 chore: reduce concurrent builds
  .github/workflows/bigtable-example.yml
  .github/workflows/ci.yml
  .github/workflows/cockroachdb-example.yml
  .github/workflows/datastore-example.yml
  .github/workflows/firestore-example.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/mysql-example.yml
  .github/workflows/nginx-example.yml
  .github/workflows/postgres-example.yml
  .github/workflows/pubsub-example.yml
  .github/workflows/pulsar-example.yml
  .github/workflows/redis-example.yml
  .github/workflows/spanner-example.yml
  .github/workflows/toxiproxy-example.yml
  examples/_template/ci.yml.tmpl
  examples/main_test.go
Labels: chore

#527 chore: bump transitive dependencies
  commons-test.mk
  e2e/go.mod
  e2e/go.sum
  examples/Makefile
  go.mod
  go.sum
Labels: dependencies, security

#701 chore: move redis-specific tests to the example module
  docker_test.go
  examples/redis/go.mod
  examples/redis/go.sum
  examples/redis/redis_test.go
  examples/redis/testresources/Dockerfile
  go.mod
  go.sum
Labels: dependencies

#706 docs: refine onboarding process with quickstart guide
  README.md
  docs/index.md
  docs/quickstart.md
  examples/mkdocs.go
  mkdocs.yml
Labels: documentation

#709 chore: add compose module to dependabot
  .github/dependabot.yml
  examples/dependabot_test.go
  examples/main.go
  examples/main_test.go
Labels: dependencies

#713 chore: simplify compose replace directives
  docs/features/docker_compose.md
  e2e/go.mod
  e2e/go.sum
  modules/compose/go.mod
  modules/compose/go.sum
Labels: dependencies

#712 chore: support running MySQL compose in ARM
  modules/compose/testresources/docker-compose-complex.yml
Labels: chore

#714 chore: bump testcontainers-go to 0.17.0 in examples
  examples/bigtable/go.mod
  examples/cockroachdb/go.mod
  examples/datastore/go.mod
  examples/firestore/go.mod
  examples/mysql/go.mod
  examples/nginx/go.mod
  examples/postgres/go.mod
  examples/pubsub/go.mod
  examples/pulsar/go.mod
  examples/redis/go.mod
  examples/spanner/go.mod
  examples/toxiproxy/go.mod
  mkdocs.yml
Labels: dependencies

#715 chore: bump containerd transitive dep in examples
  examples/_template/go.mod.tmpl
  examples/_template/go.sum.tmpl
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/mysql/go.mod
  examples/mysql/go.sum
  examples/nginx/go.mod
  examples/nginx/go.sum
  examples/postgres/go.mod
  examples/postgres/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/pulsar/go.mod
  examples/pulsar/go.sum
  examples/redis/go.mod
  examples/redis/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
  examples/toxiproxy/go.mod
  examples/toxiproxy/go.sum
Labels: dependencies

#717 chore: move e2e module to postgres example module
  .github/dependabot.yml
  .github/workflows/ci.yml
  Makefile
  e2e/Makefile
  e2e/README.md
  e2e/container_test.go
  e2e/doc.go
  e2e/go.mod
  e2e/go.sum
  e2e/tools/tools.go
  examples/dependabot_test.go
  examples/main.go
  examples/main_test.go
  examples/postgres/postgres_test.go
Labels: dependencies

#718 fix: close response body in http strategy
  wait/http.go
Labels: bug
