Repository testcontainers/testcontainers-go, pull requests merged in 2022-04, with the labels that each got.

#421 fix: use 1.18 format to install dependencies
  .github/workflows/ci.yml
  Pipfile
  go.mod
  go.sum
  requirements.txt
  tools/tools.go
Labels: type/housekeeping, dependencies

#422 chore: preparation to rename to main
  README.md
  docker.go
  docs/index.md
Labels: type/housekeeping

#401 chore(ci): run tests for more recent Go versions
  .github/workflows/ci.yml
Labels: type/housekeeping, type/test-improvement

#426 Fix compose v2 wait strategy
  compose.go
Labels: type/bug

#429 chore: update branding
  docs/css/extra.css
  docs/favicon.ico
  docs/logo.png
  docs/logo.svg
  mkdocs.yml
Labels: type/docs

#432 Negotiate client version for docker compose
  compose.go
Labels: type/housekeeping
