Repository testcontainers/testcontainers-go, pull requests merged in 2022-07, with the labels that each got.

#474 chore: tell dependabot about the new module
  .github/dependabot.yml
Labels: dependencies

#475 refactor: read RYUK_CONTAINER_PRIVILEGED once
  docker.go
  docker_test.go
  reaper.go
Labels: type/feature

#467 feat: update 3d party packages
  go.mod
  go.sum
Labels: dependencies

#478 chore(ci): update podman pipeline
  .github/workflows/ci-podman.yml
  .github/workflows/ci.yml
  e2e/Makefile
Labels: type/housekeeping

#479 refactor: more nuanced env vs properties config
  docker.go
  docker_test.go
Labels: type/housekeeping

#464 Issue 439: use an existing container
  container.go
  docker.go
  docs/features/creating_container.md
  generic.go
  generic_test.go
Labels: type/feature

#481 docs: fix format for create-container feature
  docs/features/creating_container.md
Labels: type/docs

#484 feat(deps): update dependencies to resolve dependabot security alerts
  e2e/go.sum
  go.mod
  go.sum
Labels: dependencies

#473 chore: display test summary on GH actions
  .github/workflows/ci-podman.yml
  .github/workflows/ci.yml
Labels: type/housekeeping

#468 feat: Use exposed ports specified in image if it is not specified in ContainerRequest
  docker.go
  docker_test.go
  wait/exec_test.go
  wait/exit_test.go
  wait/host_port.go
  wait/log_test.go
  wait/wait.go
Labels: type/feature
