Repository testcontainers/testcontainers-go, pull requests merged in 2022-02, with the labels that each got.

#393 Logger per container instance
  compose.go
  compose_test.go
  container.go
  docker.go
  docker_test.go
  generic.go
  logconsumer_test.go
  logger.go
Labels: type/feature

#402 Expose HostConfig Resources via ContainerRequest
  container.go
  docker.go
  docker_test.go
Labels: type/feature

#377 Add support for Docker Compose V2
  compose.go
  compose_test.go
  testresources/docker-compose-container-name.yml
Labels: type/bug

#408 add import statements to quick start
  docs/quickstart/gotest.md
Labels: type/docs

#403 Remove intermediate containers when building from Dockerfile
  docker.go
Labels: type/feature
