Repository testcontainers/testcontainers-go, pull requests merged in 2022-06, with the labels that each got.

#446 chore(deps): bump containerd version to v1.5.13
  go.mod
  go.sum
Labels: dependencies

#471 Remove unused import in redis example
  docs/examples/redis.md
Labels: type/docs

#456 Issue 332 generic parallel containers
  docs/features/creating_container.md
  parallel.go
  parallel_test.go
Labels: type/feature

#451 feature: custom ForSQL query
  .github/workflows/ci.yml
  Makefile
  e2e/Makefile
  e2e/README.md
  e2e/container_test.go
  e2e/doc.go
  e2e/go.mod
  e2e/go.sum
  e2e/tools/tools.go
  wait/sql.go
  wait/sql_test.go
Labels: type/feature
