Repository testcontainers/testcontainers-go, pull requests merged in 2023-05, with the labels that each got.

#1129 chore(deps): bump gotest.tools/gotestsum from 1.9.0 to 1.10.0
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/consul/go.mod
  examples/consul/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/mongodb/go.mod
  examples/mongodb/go.sum
  examples/nginx/go.mod
  examples/nginx/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
  examples/toxiproxy/go.mod
  examples/toxiproxy/go.sum
  go.mod
  go.sum
  modulegen/go.mod
  modulegen/go.sum
  modules/compose/go.mod
  modules/couchbase/go.mod
  modules/couchbase/go.sum
  modules/localstack/go.mod
  modules/localstack/go.sum
  modules/mysql/go.mod
  modules/mysql/go.sum
  modules/neo4j/go.mod
  modules/neo4j/go.sum
  modules/postgres/go.mod
  modules/postgres/go.sum
  modules/pulsar/go.mod
  modules/pulsar/go.sum
  modules/redis/go.mod
  modules/redis/go.sum
  modules/vault/go.mod
  modules/vault/go.sum
Labels: dependencies

#1131 chore(deps): bump google.golang.org/api to 0.120.0 in /examples
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
Labels: dependencies

#1058 feat: Add Redpanda module
  .github/dependabot.yml
  .github/workflows/module-redpanda.yml
  docs/modules/redpanda.md
  mkdocs.yml
  modules/redpanda/Makefile
  modules/redpanda/admin_api.go
  modules/redpanda/go.mod
  modules/redpanda/go.sum
  modules/redpanda/mounts/bootstrap.yaml.tpl
  modules/redpanda/mounts/entrypoint-tc.sh
  modules/redpanda/mounts/redpanda.yaml.tpl
  modules/redpanda/options.go
  modules/redpanda/redpanda.go
  modules/redpanda/redpanda_test.go
  modules/redpanda/tools/tools.go
Labels: enhancement

#1154 chore(deps): bump dependencies in /modules/redpanda
  modules/redpanda/go.mod
  modules/redpanda/go.sum
Labels: dependencies

#1155 chore(deps): bump google dependencies in /examples
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
Labels: dependencies

#1156 chore(deps): bump github.com/docker/docker v23.0.5+incompatible in modules and examples
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/consul/go.mod
  examples/consul/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/mongodb/go.mod
  examples/mongodb/go.sum
  examples/nginx/go.mod
  examples/nginx/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
  examples/toxiproxy/go.mod
  examples/toxiproxy/go.sum
  modules/couchbase/go.mod
  modules/couchbase/go.sum
  modules/localstack/go.mod
  modules/localstack/go.sum
  modules/mysql/go.mod
  modules/mysql/go.sum
  modules/neo4j/go.mod
  modules/neo4j/go.sum
  modules/postgres/go.mod
  modules/postgres/go.sum
  modules/redis/go.mod
  modules/redis/go.sum
  modules/redpanda/go.mod
  modules/redpanda/go.sum
Labels: dependencies

#1157 Revert "chore: run pipelines in order (#1130)"
  .github/workflows/README.md
  .github/workflows/ci-modulegen.yml
  .github/workflows/ci.yml
  .github/workflows/cockroachdb-example.yml
  .github/workflows/consul-example.yml
  .github/workflows/datastore-example.yml
  .github/workflows/firestore-example.yml
  .github/workflows/module-compose.yml
  .github/workflows/module-couchbase.yml
  .github/workflows/module-localstack.yml
  .github/workflows/module-mysql.yml
  .github/workflows/module-neo4j.yml
  .github/workflows/module-postgres.yml
  .github/workflows/module-pulsar.yml
  .github/workflows/module-redis.yml
  .github/workflows/module-vault.yml
  .github/workflows/mongodb-example.yml
  .github/workflows/nginx-example.yml
  .github/workflows/pubsub-example.yml
  .github/workflows/spanner-example.yml
  .github/workflows/toxiproxy-example.yml
  modulegen/_template/ci.yml.tmpl
  modulegen/main_test.go
Labels: chore

#1158 chore(deps): bump dependencies in /modules/localstack
  modules/localstack/go.mod
  modules/localstack/go.sum
Labels: dependencies

#1160 Fix race condition while initializing docker client
  docker.go
Labels: bug

#1162 ci(lint): enable misspell and gci linters
  .github/workflows/golangci-lint.yml
  .golangci.yml
  container.go
  container_test.go
  docker.go
  docker_mounts.go
  docker_test.go
  generic_test.go
  logconsumer_test.go
  mounts.go
  network.go
  network_test.go
  reaper.go
  wait/exec_test.go
  wait/health_test.go
Labels: chore

#1163 fix: define a two-phase release process
  RELEASING.md
  internal/version.go
  mkdocs.yml
  scripts/pre-release.sh
  scripts/release.sh
Labels: documentation, chore

#1164 Revert "fix: don't panic when logs waits for more than 5 seconds (#947)"
  docker.go
Labels: bug

#1189 chore(deps): bump github.com/docker/distribution from 2.8.1+incompatible to 2.8.2+incompatible
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/consul/go.mod
  examples/consul/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/mongodb/go.mod
  examples/mongodb/go.sum
  examples/nginx/go.mod
  examples/nginx/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
  examples/toxiproxy/go.mod
  examples/toxiproxy/go.sum
  go.mod
  go.sum
  modules/compose/go.mod
  modules/compose/go.sum
  modules/couchbase/go.mod
  modules/couchbase/go.sum
  modules/localstack/go.mod
  modules/localstack/go.sum
  modules/mysql/go.mod
  modules/mysql/go.sum
  modules/neo4j/go.mod
  modules/neo4j/go.sum
  modules/postgres/go.mod
  modules/postgres/go.sum
  modules/pulsar/go.mod
  modules/pulsar/go.sum
  modules/redis/go.mod
  modules/redis/go.sum
  modules/redpanda/go.mod
  modules/redpanda/go.sum
  modules/vault/go.mod
  modules/vault/go.sum
Labels: dependencies

#1192 fix: update link to modules docs
  modulegen/README.md
Labels: documentation

#1085 fix: align header while log producers are reading
  docker.go
Labels: bug

#1195 chore: support for bumping ryuk in an automated manner
  reaper.go
  scripts/bump-reaper.sh
Labels: chore

#1225 chore: use fixed version in k3s module
  docs/modules/k3s.md
  modules/k3s/k3s.go
Labels: chore

#1228 chore(deps): bump github.com/stretchr/testify from 1.8.2 to 1.8.3
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  modulegen/go.mod
  modulegen/go.sum
  modules/compose/go.mod
  modules/compose/go.sum
  modules/k3s/go.mod
  modules/k3s/go.sum
  modules/localstack/go.mod
  modules/localstack/go.sum
  modules/postgres/go.mod
  modules/postgres/go.sum
  modules/pulsar/go.mod
  modules/pulsar/go.sum
  modules/redis/go.mod
  modules/redis/go.sum
  modules/redpanda/go.mod
  modules/redpanda/go.sum
  modules/vault/go.mod
  modules/vault/go.sum
Labels: dependencies

#1229 chore(deps): bump google.golang.org/api from 0.121.0 to 0.123.0 in /examples
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
Labels: dependencies

#1244 chore(deps): bump google.golang.org/api from 0.123.0 to 0.124.0 in /examples
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
Labels: dependencies

#1153 #1152 execute HostConfigModifier at last
  go.mod
  go.sum
  lifecycle.go
  lifecycle_test.go
Labels: bug

#1246 docs: document the Go version
  docs/system_requirements/docker.md
  docs/system_requirements/index.md
  mkdocs.yml
Labels: documentation

#1161 feat: setup docker_host discovery strategies properly
  .github/workflows/ci-rootless-docker.yml
  config.go
  config_test.go
  container_test.go
  docker.go
  docker_auth.go
  docker_auth_test.go
  docker_test.go
  docs/features/configuration.md
  docs/system_requirements/docker.md
  internal/config/config.go
  internal/config/config_test.go
  internal/testcontainersdocker/client.go
  internal/testcontainersdocker/docker_host.go
  internal/testcontainersdocker/docker_host_test.go
  internal/testcontainersdocker/docker_rootless.go
  internal/testcontainersdocker/docker_rootless_test.go
  internal/testcontainersdocker/docker_socket.go
  logconsumer_test.go
  modules/localstack/localstack.go
  provider.go
  provider_test.go
  reaper.go
  reaper_test.go
Labels: feature
