Repository testcontainers/testcontainers-go, pull requests merged in 2023-09, with the labels that each got.

#1560 feat: support waiting for logs with regexp
  docs/features/wait/log.md
  wait/log.go
  wait/log_test.go
Labels: feature

#1574 feat: add Elasticsearch module
  .github/dependabot.yml
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/elasticsearch.md
  internal/config/config.go
  mkdocs.yml
  modules/elasticsearch/Makefile
  modules/elasticsearch/elasticsearch.go
  modules/elasticsearch/elasticsearch_test.go
  modules/elasticsearch/examples_test.go
  modules/elasticsearch/go.mod
  modules/elasticsearch/go.sum
  modules/elasticsearch/options.go
  modules/elasticsearch/version.go
  modules/elasticsearch/version_test.go
Labels: feature

#1582 chore: remove dependabot groups
  .github/dependabot.yml
  .github/workflows/ci.yml
  modulegen/_template/ci.yml.tmpl
  modulegen/internal/dependabot/types.go
  modulegen/main_test.go
Labels: dependencies

#1599 chore(deps): bump github.com/aws/aws-sdk-go and aws-sdk-go-v2 in /modules/localstack
  modules/localstack/go.mod
  modules/localstack/go.sum
Labels: dependencies

#1606 ci(security): setup codeql scan
  .github/workflows/codeql.yml
Labels: chore

#1566 chore(deps): bump github.com/hashicorp/vault-client-go in /modules/vault
  modules/vault/go.mod
  modules/vault/go.sum
  modules/vault/vault_test.go
Labels: dependencies

#1604 ci(lint): enable errorlint linter
  .golangci.yml
  docker.go
  internal/testcontainersdocker/docker_host.go
  internal/testcontainersdocker/docker_rootless.go
  parallel_test.go
  wait/errors.go
  wait/exec_test.go
  wait/host_port.go
  wait/http.go
  wait/sql.go
Labels: chore

#1518 chore(ci): enable code coverage on Sonarcloud
  .github/workflows/ci-test-go.yml
  .github/workflows/ci.yml
  commons-test.mk
  modulegen/_template/ci.yml.tmpl
  modulegen/main_test.go
  sonar-project.properties
Labels: chore

#1607 fix: remove extra equal in sonar.organization
  sonar-project.properties
Labels: chore

#1608 ci(sonarcloud): run only when docker is not rootless
  .github/workflows/ci-test-go.yml
  .golangci.yml
  sonar-project.properties
Labels: chore

#1609 chore: support linting all modules locally
  commons-test.mk
  examples/Makefile
  modules/Makefile
  modules/compose/compose_local.go
Labels: chore

#1611 chore: always generate the examples including a explicit image
  modulegen/_template/examples_test.go.tmpl
  modulegen/_template/module_test.go.tmpl
  modulegen/internal/module/main.go
  modulegen/main_test.go
Labels: chore

#1612 feat: support creating a network for localstack
  docs/modules/localstack.md
  modules/localstack/localstack.go
  modules/localstack/localstack_test.go
Labels: feature

#1615 chore: update sonarcloud properties when releasing the project
  scripts/pre-release.sh
Labels: chore

#1617 chore(deps): bump github.com/containerd/containerd from 1.7.3 to 1.7.6
  Makefile
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/consul/go.mod
  examples/consul/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/nginx/go.mod
  examples/nginx/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
  examples/toxiproxy/go.mod
  examples/toxiproxy/go.sum
  go.mod
  go.sum
  modules/artemis/go.mod
  modules/artemis/go.sum
  modules/clickhouse/go.mod
  modules/clickhouse/go.sum
  modules/compose/go.mod
  modules/compose/go.sum
  modules/couchbase/go.mod
  modules/couchbase/go.sum
  modules/elasticsearch/go.mod
  modules/elasticsearch/go.sum
  modules/k3s/go.mod
  modules/k3s/go.sum
  modules/localstack/go.mod
  modules/localstack/go.sum
  modules/mariadb/go.mod
  modules/mariadb/go.sum
  modules/mongodb/go.mod
  modules/mongodb/go.sum
  modules/mysql/go.mod
  modules/mysql/go.sum
  modules/nats/go.mod
  modules/nats/go.sum
  modules/neo4j/go.mod
  modules/neo4j/go.sum
  modules/postgres/go.mod
  modules/postgres/go.sum
  modules/pulsar/go.mod
  modules/pulsar/go.sum
  modules/redis/go.mod
  modules/redis/go.sum
  modules/redpanda/go.mod
  modules/redpanda/go.sum
  modules/vault/go.mod
  modules/vault/go.sum
Labels: dependencies

#1610 feat: add kafka (KRaft mode only) module
  .github/dependabot.yml
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/kafka.md
  mkdocs.yml
  modules/kafka/Makefile
  modules/kafka/consumer_test.go
  modules/kafka/examples_test.go
  modules/kafka/go.mod
  modules/kafka/go.sum
  modules/kafka/kafka.go
  modules/kafka/kafka_test.go
Labels: feature

#1644 modulegen: generate sonar configuration
  modulegen/_template/sonar-project.properties.tmpl
  modulegen/internal/context/context.go
  modulegen/internal/main.go
  modulegen/internal/sonar/main.go
  modulegen/internal/sonar/types.go
  sonar-project.properties
Labels: chore

#1645 fix: avoid deadlocks when Docker is not available
  docker_client.go
Labels: bug

#1646 fix: support running the semver Docker image interactively during the release process
  scripts/release.sh
Labels: chore

#1647 feat: add functional option for startup commands
  docs/modules/artemis.md
  docs/modules/clickhouse.md
  docs/modules/couchbase.md
  docs/modules/elasticsearch.md
  docs/modules/k3s.md
  docs/modules/kafka.md
  docs/modules/localstack.md
  docs/modules/mariadb.md
  docs/modules/mongodb.md
  docs/modules/mysql.md
  docs/modules/nats.md
  docs/modules/neo4j.md
  docs/modules/postgres.md
  docs/modules/pulsar.md
  docs/modules/redis.md
  docs/modules/redpanda.md
  docs/modules/vault.md
  generic.go
  generic_test.go
  modulegen/_template/module.md.tmpl
Labels: feature

#1650 docs: remove shared docs in template
  modulegen/_template/module.md.tmpl
Labels: documentation

#1618 feat: add RabbitMQ support
  .github/dependabot.yml
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/postgres.md
  docs/modules/rabbitmq.md
  mkdocs.yml
  modulegen/_template/examples_test.go.tmpl
  modules/rabbitmq/Makefile
  modules/rabbitmq/examples_test.go
  modules/rabbitmq/go.mod
  modules/rabbitmq/go.sum
  modules/rabbitmq/mounts/rabbitmq-testcontainers.conf.tpl
  modules/rabbitmq/options.go
  modules/rabbitmq/rabbitmq.go
  modules/rabbitmq/rabbitmq_test.go
  modules/rabbitmq/testdata/certs/server_ca.pem
  modules/rabbitmq/testdata/certs/server_cert.pem
  modules/rabbitmq/testdata/certs/server_key.pem
  modules/rabbitmq/types_test.go
Labels: feature

#1667 chore(deps): bump google.golang.org/grpc from 1.57.0 to 1.58.1 and google.golang.org/api from 0.138.0 to 0.142.0 in /examples
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
Labels: dependencies

#1668 make ryuk timeouts configurable via properties file
  internal/config/config.go
  internal/config/config_test.go
  reaper.go
  reaper_test.go
Labels: feature

#1670 feat: add GCloud module
  .github/dependabot.yml
  .github/workflows/ci-test-go.yml
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/examples/bigtable.md
  docs/examples/datastore.md
  docs/examples/firestore.md
  docs/examples/pubsub.md
  docs/examples/spanner.md
  docs/modules/gcloud.md
  examples/bigtable/bigtable.go
  examples/bigtable/go.sum
  examples/datastore/Makefile
  examples/datastore/datastore.go
  examples/datastore/datastore_test.go
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/Makefile
  examples/firestore/firestore.go
  examples/firestore/firestore_test.go
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/pubsub/Makefile
  examples/pubsub/go.mod
  examples/pubsub/pubsub.go
  examples/pubsub/pubsub_test.go
  examples/spanner/Makefile
  examples/spanner/go.mod
  examples/spanner/go.sum
  examples/spanner/spanner.go
  mkdocs.yml
  modules/gcloud/Makefile
  modules/gcloud/bigquery.go
  modules/gcloud/bigquery_test.go
  modules/gcloud/bigtable.go
  modules/gcloud/bigtable_test.go
  modules/gcloud/datastore.go
  modules/gcloud/datastore_test.go
  modules/gcloud/firestore.go
  modules/gcloud/firestore_test.go
  modules/gcloud/gcloud.go
  modules/gcloud/go.mod
  modules/gcloud/go.sum
  modules/gcloud/pubsub.go
  modules/gcloud/pubsub_test.go
  modules/gcloud/spanner.go
  modules/gcloud/spanner_test.go
  sonar-project.properties
Labels: feature

#1681 chore(deps): bump cloud.google.com/go/datastore from 1.13.0 to 1.14.0 and google.golang.org/grpc from 1.58.1 to 1.58.2 and cloud.google.com/go/spanner from 1.47.0 to 1.49.0 in /modules/gcloud
  modules/gcloud/go.mod
  modules/gcloud/go.sum
Labels: dependencies

#1682 chore(deps): bump github.com/twmb/franz-go/pkg/kadm from 1.9.0 to 1.9.1 and github.com/twmb/franz-go from 1.14.4 to 1.15.0 in /modules/redpanda
  modules/redpanda/go.mod
  modules/redpanda/go.sum
Labels: dependencies

#1680 chore(deps): bump github.com/aws/aws-sdk-go-v2/config from 1.18.39 to 1.18.42 and github.com/aws/aws-sdk-go from 1.45.3 to 1.45.15 and github.com/aws/aws-sdk-go-v2/service/s3 from 1.38.5 to 1.39.0 in /modules/localstack
  modules/localstack/go.mod
  modules/localstack/go.sum
Labels: dependencies

#1683 chore(deps): bump k8s.io/apimachinery from 0.28.1 to 0.28.2 and k8s.io/client-go from 0.28.1 to 0.28.2 in /modules/k3s
  modules/k3s/go.mod
  modules/k3s/go.sum
Labels: dependencies

#1684 chore(deps): bump github.com/tidwall/gjson from 1.16.0 to 1.17.0 in /modules/couchbase and /modules/vault
  modules/couchbase/go.mod
  modules/couchbase/go.sum
  modules/vault/go.mod
  modules/vault/go.sum
Labels: dependencies

#1685 Wait for k3s node to sync
  docs/modules/k3s.md
  modules/k3s/k3s.go
  modules/k3s/k3s_example_test.go
  modules/k3s/k3s_image_test.go
  modules/k3s/k3s_test.go
Labels: chore

#1687 chore(deps): bump golang.org/x/text to v0.15.0
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/consul/go.mod
  examples/consul/go.sum
  examples/nginx/go.mod
  examples/nginx/go.sum
  examples/toxiproxy/go.mod
  examples/toxiproxy/go.sum
  go.mod
  go.sum
  modules/artemis/go.mod
  modules/artemis/go.sum
  modules/clickhouse/go.mod
  modules/clickhouse/go.sum
  modules/compose/go.mod
  modules/compose/go.sum
  modules/couchbase/go.mod
  modules/couchbase/go.sum
  modules/elasticsearch/go.mod
  modules/elasticsearch/go.sum
  modules/k3s/go.mod
  modules/k3s/go.sum
  modules/localstack/go.mod
  modules/localstack/go.sum
  modules/mariadb/go.mod
  modules/mariadb/go.sum
  modules/mongodb/go.mod
  modules/mongodb/go.sum
  modules/mysql/go.mod
  modules/mysql/go.sum
  modules/nats/go.mod
  modules/nats/go.sum
  modules/neo4j/go.mod
  modules/neo4j/go.sum
  modules/postgres/go.mod
  modules/postgres/go.sum
  modules/pulsar/go.mod
  modules/pulsar/go.sum
  modules/rabbitmq/go.mod
  modules/rabbitmq/go.sum
  modules/redis/go.mod
  modules/redis/go.sum
  modules/redpanda/go.mod
  modules/redpanda/go.sum
  modules/vault/go.mod
  modules/vault/go.sum
Labels: dependencies

#1690 docs: improve experience for creating modules for first time
  docs/modules/index.md
  modulegen/_template/examples_test.go.tmpl
  modulegen/internal/module/main.go
  modulegen/main_test.go
Labels: documentation

#1696 fix: typo
  docs/features/wait/multi.md
Labels: documentation

#1695 reduce timeout in context cancellation propegation test for test stability
  docker_test.go
Labels: chore

#1693 fix TestContainerRunningCheckingStatusCode to pass on arm platforms
  docker_test.go
Labels: chore

#1698 Improve redpanda resource usage
  modules/redpanda/redpanda.go
Labels: chore

#1699 fix: bump tc-go dependency in RabbitMQ
  modules/rabbitmq/go.mod
Labels: dependencies

#1697 avoid race conditions by waiting one polling interval
  wait/http.go
  wait/http_test.go
Labels: chore
