Repository testcontainers/testcontainers-go, pull requests merged in 2023-08, with the labels that each got.

#1375 chore(ci): add a Windows pipeline for running the tests
  .github/workflows/ci-windows-trigger.yml
  .github/workflows/ci-windows.yml
  .github/workflows/ci.yml
Labels: chore

#1411 chore(deps): bump cloud.google.com/go in /examples
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
Labels: dependencies

#1413 test: fix TestGetDockerConfig
  docker_auth_test.go
Labels: chore

#1410 chore(deps): bump golang.org/x/mod and github.com/aws/aws-sdk-go-v2/config in /modules/localstack
  modules/localstack/go.mod
  modules/localstack/go.sum
Labels: dependencies

#1360 feat(redpanda): Add option to enable topic auto-creation
  modules/redpanda/mounts/bootstrap.yaml.tpl
  modules/redpanda/mounts/redpanda.yaml.tpl
  modules/redpanda/options.go
  modules/redpanda/redpanda.go
  modules/redpanda/redpanda_test.go
Labels: enhancement

#1414 chore(ci): define a pipeline with multiple gates
  .github/settings.yml
  .github/workflows/bigtable-example.yml
  .github/workflows/ci-reaper-off.yml
  .github/workflows/ci-rootless-docker.yml
  .github/workflows/ci-test-go.yml
  .github/workflows/ci.yml
  .github/workflows/cockroachdb-example.yml
  .github/workflows/consul-example.yml
  .github/workflows/datastore-example.yml
  .github/workflows/firestore-example.yml
  .github/workflows/module-compose.yml
  .github/workflows/module-couchbase.yml
  .github/workflows/module-k3s.yml
  .github/workflows/module-localstack.yml
  .github/workflows/module-mysql.yml
  .github/workflows/module-neo4j.yml
  .github/workflows/module-postgres.yml
  .github/workflows/module-pulsar.yml
  .github/workflows/module-redis.yml
  .github/workflows/module-redpanda.yml
  .github/workflows/module-vault.yml
  .github/workflows/mongodb-example.yml
  .github/workflows/nats-example.yml
  .github/workflows/nginx-example.yml
  .github/workflows/pubsub-example.yml
  .github/workflows/spanner-example.yml
  .github/workflows/toxiproxy-example.yml
  modulegen/_template/ci.yml.tmpl
  modulegen/main.go
  modulegen/main_test.go
  modulegen/mkdocs.go
Labels: chore

#1415 chore(ci): set LongPathsEnabled on WIndows workers
  .github/workflows/ci-windows.yml
Labels: chore

#1416 docs: fix link to GH action in docs site
  docs/system_requirements/index.md
Labels: documentation

#1417 chore: run go mod tidy
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/consul/go.mod
  examples/consul/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/mongodb/go.mod
  examples/mongodb/go.sum
  examples/nats/go.mod
  examples/nats/go.sum
  examples/nginx/go.mod
  examples/nginx/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
  examples/toxiproxy/go.mod
  examples/toxiproxy/go.sum
  modules/couchbase/go.mod
  modules/couchbase/go.sum
  modules/k3s/go.mod
  modules/k3s/go.sum
  modules/localstack/go.mod
  modules/localstack/go.sum
  modules/mysql/go.mod
  modules/mysql/go.sum
  modules/neo4j/go.mod
  modules/neo4j/go.sum
  modules/postgres/go.mod
  modules/postgres/go.sum
  modules/pulsar/go.mod
  modules/pulsar/go.sum
  modules/redis/go.mod
  modules/redis/go.sum
  modules/redpanda/go.mod
  modules/redpanda/go.sum
  modules/vault/go.mod
  modules/vault/go.sum
Labels: dependencies

#1418 chore: fix branch protection settings
  .github/settings.yml
Labels: chore

#1420 fix: proper check name in branch protection settings
  .github/settings.yml
Labels: chore

#1419 chore: update mergo to the new vanity url
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/consul/go.mod
  examples/consul/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/mongodb/go.mod
  examples/mongodb/go.sum
  examples/nats/go.mod
  examples/nats/go.sum
  examples/nginx/go.mod
  examples/nginx/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
  examples/toxiproxy/go.mod
  examples/toxiproxy/go.sum
  generic.go
  go.mod
  go.sum
  modules/compose/go.mod
  modules/compose/go.sum
  modules/couchbase/go.mod
  modules/couchbase/go.sum
  modules/k3s/go.mod
  modules/k3s/go.sum
  modules/localstack/go.mod
  modules/localstack/go.sum
  modules/mysql/go.mod
  modules/mysql/go.sum
  modules/neo4j/go.mod
  modules/neo4j/go.sum
  modules/postgres/go.mod
  modules/postgres/go.sum
  modules/pulsar/go.mod
  modules/pulsar/go.sum
  modules/redis/go.mod
  modules/redis/go.sum
  modules/redpanda/go.mod
  modules/redpanda/go.sum
  modules/vault/go.mod
  modules/vault/go.sum
Labels: dependencies

#1438 chore(deps): bump Github actions
  .github/workflows/ci-test-go.yml
  .github/workflows/ci-windows.yml
  .github/workflows/golangci-lint.yml
Labels: dependencies

#1441 internal/testcontainersdocker: close unused client
  internal/testcontainersdocker/docker_host.go
Labels: bug

#1442 chore: remove temporary workaround for windows
  .github/workflows/ci-windows.yml
Labels: chore

#1443 chore: downgrade GH action github-script
  .github/workflows/ci-windows.yml
Labels: dependencies

#1444 fix: proper semver name
  .github/workflows/ci-windows.yml
Labels: dependencies

#1445 fix: simplify and do not run make on windows
  .github/workflows/ci-windows.yml
Labels: dependencies

#1446 chore: run dependabot on sundays
  .github/dependabot.yml
  modulegen/dependabot.go
  modulegen/dependabot_test.go
  modulegen/main.go
  modulegen/main_test.go
  modulegen/mkdocs.go
Labels: dependencies

#1455 fix devcontainer go version to 1.19
  .devcontainer/devcontainer.json
Labels: dependencies

#1456 chore: run Windows tests on a Linux container
  .github/workflows/ci-windows.yml
Labels: chore

#1079 feat: use credential helper in docker config, even if auth is empty in .docker/config.json
  docker_auth.go
Labels: feature

#1460 Simplify dependabot updates sorting
  .github/dependabot.yml
  modulegen/dependabot.go
  modulegen/main.go
  modulegen/main_test.go
Labels: chore

#1308 Add global testcontainers header to docs
  docs/css/extra.css
  docs/css/tc-header.css
  docs/index.md
  docs/js/tc-header.js
  docs/language-logos/ruby.svg
  docs/testcontainers-logo.svg
  docs/theme/main.html
  docs/theme/partials/header.html
  docs/theme/partials/nav.html
  docs/theme/partials/tc-header.html
  mkdocs.yml
Labels: documentation

#1470 chore: add a GH action for release drafter
  .github/workflows/release-drafter.yml
Labels: chore

#1471 chore(deps): bump Google emulators dependencies in /examples
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
Labels: dependencies

#1474 chore: triple max timeout for the workflow run, which takes +10m
  .github/workflows/ci-windows.yml
Labels: chore

#1372 feat: add clickhouse module
  .github/dependabot.yml
  .github/workflows/ci.yml
  docs/modules/clickhouse.md
  mkdocs.yml
  modules/clickhouse/Makefile
  modules/clickhouse/clickhouse.go
  modules/clickhouse/clickhouse_test.go
  modules/clickhouse/go.mod
  modules/clickhouse/go.sum
  modules/clickhouse/testdata/config.xml
  modules/clickhouse/testdata/config.yaml
  modules/clickhouse/testdata/init-db.sh
Labels: enhancement

#1339 Add default labels when Ryuk is disabled
  docker.go
  internal/testcontainersdocker/labels.go
  reaper.go
  reaper_test.go
Labels: chore

#1478 chore: run modulegen tests on Windows
  .github/workflows/ci.yml
Labels: chore

#1459 Support groups in dependabot updates
  .github/dependabot.yml
  modulegen/dependabot.go
Labels: dependencies

#1447 Add support for MongoDB testing module
  .github/dependabot.yml
  .github/workflows/ci.yml
  docs/examples/mongodb.md
  docs/modules/mongodb.md
  examples/mongodb/mongodb.go
  mkdocs.yml
  modules/mongodb/Makefile
  modules/mongodb/go.mod
  modules/mongodb/go.sum
  modules/mongodb/mongodb.go
  modules/mongodb/mongodb_test.go
Labels: enhancement

#1491 feat: pass testcontainers-go version as HTTP header
  internal/testcontainersdocker/client.go
Labels: enhancement

#1458 fix: properly set the Docker socket on Windows
  .github/workflows/ci-windows.yml
  config_test.go
  container_test.go
  docker_auth_test.go
  docker_test.go
  docs/features/configuration.md
  examples/nginx/nginx.go
  internal/config/config_test.go
  internal/testcontainersdocker/docker_host.go
  internal/testcontainersdocker/docker_host_test.go
  internal/testcontainersdocker/docker_rootless.go
  internal/testcontainersdocker/docker_rootless_test.go
  internal/testcontainersdocker/docker_socket.go
  lifecycle_test.go
  logger.go
  mounts_test.go
  provider_test.go
  wait/host_port_test.go
  wait/http_test.go
Labels: bug

#1496 fix: run tests for module generator in all platforms
  .github/workflows/ci-test-go.yml
  .github/workflows/ci.yml
  modulegen/main_test.go
Labels: chore

#1493 chore: Use generic db url for postgresql container
  modules/postgres/postgres.go
  modules/postgres/postgres_test.go
Labels: chore

#1440 feat(modules): add artemis container
  .github/dependabot.yml
  .github/workflows/ci.yml
  docs/modules/artemis.md
  mkdocs.yml
  modules/artemis/Makefile
  modules/artemis/artemis.go
  modules/artemis/artemis_test.go
  modules/artemis/example_test.go
  modules/artemis/go.mod
  modules/artemis/go.sum
Labels: enhancement

#1497 chore: bump minimal Go version to 1.20
  .devcontainer/devcontainer.json
  .github/workflows/ci-windows.yml
  .github/workflows/ci.yml
  .github/workflows/golangci-lint.yml
  .golangci.yml
  docker_test.go
  docs/system_requirements/ci/bitbucket_pipelines.md
  docs/system_requirements/ci/circle_ci.md
  docs/system_requirements/ci/concourse_ci.md
  docs/system_requirements/ci/dind_patterns.md
  docs/system_requirements/ci/gitlab_ci.md
  docs/system_requirements/ci/tekton.md
  docs/system_requirements/ci/travis.md
  docs/system_requirements/index.md
  examples/bigtable/go.mod
  examples/cockroachdb/go.mod
  examples/consul/go.mod
  examples/datastore/go.mod
  examples/firestore/go.mod
  examples/nats/go.mod
  examples/nginx/go.mod
  examples/pubsub/go.mod
  examples/spanner/go.mod
  examples/toxiproxy/go.mod
  go.mod
  modulegen/_template/ci.yml.tmpl
  modulegen/_template/go.mod.tmpl
  modulegen/go.mod
  modulegen/main_test.go
  modules/clickhouse/go.mod
  modules/compose/go.mod
  modules/k3s/go.mod
  modules/localstack/go.mod
  modules/mongodb/go.mod
  modules/mysql/go.mod
  modules/neo4j/go.mod
  modules/postgres/go.mod
  modules/pulsar/go.mod
  modules/redis/go.mod
  modules/redpanda/go.mod
  modules/vault/go.mod
  scripts/bump-go.sh
  wait/testdata/go.mod
Labels: chore, dependencies

#1510 doc fix: make file permission examples octal
  docs/features/copy_file.md
Labels: documentation

#1490 chore: use Info instead of Ping to check if Docker is live
  docker.go
  docker_auth.go
  docker_auth_test.go
  docker_client.go
  docker_test.go
  internal/testcontainersdocker/client.go
  lifecycle_test.go
  logconsumer_test.go
  logger.go
  modules/compose/compose.go
  modules/compose/compose_api.go
  modules/compose/compose_local.go
  modules/compose/compose_test.go
  mounts_test.go
  provider.go
  testing.go
Labels: chore

#1503 modulegen: create internal/dependabot
  modulegen/context.go
  modulegen/context_test.go
  modulegen/dependabot.go
  modulegen/dependabot_test.go
  modulegen/internal/dependabot/main.go
  modulegen/internal/dependabot/reader.go
  modulegen/internal/dependabot/sorter.go
  modulegen/internal/dependabot/types.go
  modulegen/internal/dependabot/writer.go
  modulegen/main.go
  modulegen/main_test.go
Labels: chore

#1511 feat(modules/redpanda): support tls
  docs/modules/redpanda.md
  modules/redpanda/mounts/redpanda.yaml.tpl
  modules/redpanda/options.go
  modules/redpanda/redpanda.go
  modules/redpanda/redpanda_test.go
Labels: enhancement

#1516 fix: reset config in tests
  config_test.go
  internal/config/config_test.go
  logconsumer_test.go
Labels: chore

#1517 fix: do not remove the file schema in docker.host property
  internal/testcontainersdocker/docker_host.go
  internal/testcontainersdocker/docker_host_test.go
Labels: bug

#1520 modulegen: create internal/workflow
  .github/workflows/ci.yml
  modulegen/_template/ci.yml.tmpl
  modulegen/context_test.go
  modulegen/internal/template/main.go
  modulegen/internal/workflow/main.go
  modulegen/internal/workflow/types.go
  modulegen/main.go
  modulegen/main_test.go
  modulegen/mkdocs_test.go
Labels: chore

#1542 fix: use proper service name in Pulsar module
  docs/modules/pulsar.md
Labels: documentation

#1508 [Enhancement]: add ability to set repo:tag for ContainerRequest FromDockerfile
  container.go
  container_test.go
  docker.go
  docker_test.go
  docs/features/build_from_dockerfile.md
  from_dockerfile_test.go
Labels: enhancement

#1539 modulegen: create internal/module and internal/modfile
  modulegen/_template/go.mod.tmpl
  modulegen/context.go
  modulegen/go.mod
  modulegen/go.sum
  modulegen/internal/modfile/main.go
  modulegen/internal/modfile/reader.go
  modulegen/internal/modfile/writer.go
  modulegen/internal/module/main.go
  modulegen/main.go
  modulegen/main_test.go
  modulegen/module.go
  scripts/bump-go.sh
Labels: chore

#1551 modulegen: generate code-workspace with json marshal
  .vscode/.testcontainers-go.code-workspace
  docs/modules/index.md
  modulegen/_template/testcontainers-go.code-workspace.tmpl
  modulegen/internal/vscode/main.go
  modulegen/internal/vscode/types.go
  modulegen/internal/vscode/writer.go
Labels: chore

#1556 fix: remove wrong example from workspace
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  modulegen/_template/ci.yml.tmpl
  modulegen/main_test.go
Labels: chore

#1555 chore: refine fail-fast strategy on CI
  .github/workflows/ci-test-go.yml
  .github/workflows/ci.yml
  modulegen/_template/ci.yml.tmpl
  modulegen/main_test.go
Labels: chore

#1559 feat: convert NATS example into a module
  .github/dependabot.yml
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/examples/nats.md
  docs/modules/nats.md
  examples/nats/nats.go
  mkdocs.yml
  modules/nats/Makefile
  modules/nats/go.mod
  modules/nats/go.sum
  modules/nats/nats.go
  modules/nats/nats_test.go
  modules/nats/options.go
Labels: feature

#1558 Update Pipenv to use Python 3.8
  Pipfile
  Pipfile.lock
Labels: dependencies

#1561 Update actions/github-script to 6.4.1
  .github/workflows/ci-windows.yml
Labels: chore
