Repository testcontainers/testcontainers-go, pull requests merged in 2023-10, with the labels that each got.

#1717 chore(deps): bump github.com/aws/aws-sdk-go-v2/service/s3 from 1.39.0 to 1.40.0 and github.com/aws/aws-sdk-go from 1.45.15 to 1.45.19 in /modules/localstack
  modules/localstack/go.mod
  modules/localstack/go.sum
Labels: dependencies

#1716 chore(deps): bump cloud.google.com/go/firestore from 1.12.0 to 1.13.0, google.golang.org/api from 0.142.0 to 0.143.0 and cloud.google.com/ge, google.golang.org/api from 0.142.0 to 0.143.0 and cloud.google.com/go/bigquery from 1.53.0 to 1.55 in /modules/gcloud
  modules/gcloud/go.mod
  modules/gcloud/go.sum
Labels: dependencies

#1720 chore(deps): bump github.com/shirou/gopsutil/v3 from 3.23.8 to 3.23.9
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/consul/go.mod
  examples/consul/go.sum
  examples/nginx/go.mod
  examples/nginx/go.sum
  examples/toxiproxy/go.mod
  examples/toxiproxy/go.sum
  go.mod
  go.sum
  modules/artemis/go.mod
  modules/artemis/go.sum
  modules/clickhouse/go.mod
  modules/clickhouse/go.sum
  modules/compose/go.mod
  modules/compose/go.sum
  modules/couchbase/go.mod
  modules/couchbase/go.sum
  modules/elasticsearch/go.mod
  modules/elasticsearch/go.sum
  modules/gcloud/go.mod
  modules/gcloud/go.sum
  modules/k3s/go.mod
  modules/k3s/go.sum
  modules/kafka/go.mod
  modules/kafka/go.sum
  modules/localstack/go.mod
  modules/localstack/go.sum
  modules/mariadb/go.mod
  modules/mariadb/go.sum
  modules/mongodb/go.mod
  modules/mongodb/go.sum
  modules/mysql/go.mod
  modules/mysql/go.sum
  modules/nats/go.mod
  modules/nats/go.sum
  modules/neo4j/go.mod
  modules/neo4j/go.sum
  modules/postgres/go.mod
  modules/postgres/go.sum
  modules/pulsar/go.mod
  modules/pulsar/go.sum
  modules/rabbitmq/go.mod
  modules/rabbitmq/go.sum
  modules/redis/go.mod
  modules/redis/go.sum
  modules/redpanda/go.mod
  modules/redpanda/go.sum
  modules/vault/go.mod
  modules/vault/go.sum
Labels: dependencies

#1724 Rancher Desktop instructions
  docs/system_requirements/rancher.md
  mkdocs.yml
Labels: documentation

#1721 K6 module
  .github/dependabot.yml
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/k6.md
  mkdocs.yml
  modules/k6/Makefile
  modules/k6/examples_test.go
  modules/k6/go.mod
  modules/k6/go.sum
  modules/k6/k6.go
  modules/k6/k6_test.go
  modules/k6/scripts/fail.js
  modules/k6/scripts/httpbin.js
  modules/k6/scripts/pass.js
  sonar-project.properties
Labels: feature, hacktoberfest

#1726 feat: Add Cassandra module
  .github/dependabot.yml
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/cassandra.md
  mkdocs.yml
  modules/cassandra/Makefile
  modules/cassandra/cassandra.go
  modules/cassandra/cassandra_test.go
  modules/cassandra/examples_test.go
  modules/cassandra/executable.go
  modules/cassandra/go.mod
  modules/cassandra/go.sum
  modules/cassandra/testdata/config.yaml
  modules/cassandra/testdata/init.cql
  modules/cassandra/testdata/init.sh
  sonar-project.properties
Labels: feature, hacktoberfest

#1743 DOCKER_HOST var typo
  docs/system_requirements/rancher.md
Labels: documentation

#1745 docs: Fix typo and mention the relevant function name in doc
  docs/modules/mariadb.md
  docs/modules/postgres.md
Labels: documentation

#1772 chore(deps): bump golang.org/x/net from 0.15.0 to 0.17.0
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/consul/go.mod
  examples/consul/go.sum
  examples/nginx/go.mod
  examples/nginx/go.sum
  examples/toxiproxy/go.mod
  examples/toxiproxy/go.sum
  go.mod
  go.sum
  modules/artemis/go.mod
  modules/artemis/go.sum
  modules/cassandra/go.mod
  modules/cassandra/go.sum
  modules/clickhouse/go.mod
  modules/clickhouse/go.sum
  modules/compose/go.mod
  modules/compose/go.sum
  modules/couchbase/go.mod
  modules/couchbase/go.sum
  modules/elasticsearch/go.mod
  modules/elasticsearch/go.sum
  modules/gcloud/go.mod
  modules/gcloud/go.sum
  modules/k3s/go.mod
  modules/k3s/go.sum
  modules/k6/go.mod
  modules/k6/go.sum
  modules/kafka/go.mod
  modules/kafka/go.sum
  modules/localstack/go.mod
  modules/localstack/go.sum
  modules/mariadb/go.mod
  modules/mariadb/go.sum
  modules/mongodb/go.mod
  modules/mongodb/go.sum
  modules/mysql/go.mod
  modules/mysql/go.sum
  modules/nats/go.mod
  modules/nats/go.sum
  modules/neo4j/go.mod
  modules/neo4j/go.sum
  modules/postgres/go.mod
  modules/postgres/go.sum
  modules/pulsar/go.mod
  modules/pulsar/go.sum
  modules/rabbitmq/go.mod
  modules/rabbitmq/go.sum
  modules/redis/go.mod
  modules/redis/go.sum
  modules/redpanda/go.mod
  modules/redpanda/go.sum
  modules/vault/go.mod
  modules/vault/go.sum
Labels: dependencies

#1774 chore(deps): bump cloud.google.com/go/{datastore,bigtable,spanner} in /modules/gcloud
  modules/gcloud/go.mod
  modules/gcloud/go.sum
Labels: dependencies

#1773 chore(deps): bump github.com/aws/aws-sdk-go-v2/{service/s3,credentials,config} in /modules/localstack
  modules/localstack/go.mod
  modules/localstack/go.sum
Labels: dependencies

#1700 fix race condition in Test_StartStop
  logconsumer_test.go
Labels: chore, hacktoberfest

#1744 docs: add default options to k6 module
  docs/modules/k6.md
  modules/k6/examples_test.go
Labels: documentation, hacktoberfest

#1776 Fix wrong module names in docs and comments
  docs/modules/neo4j.md
  modules/elasticsearch/options.go
  modules/gcloud/gcloud.go
  modules/nats/options.go
  modules/rabbitmq/options.go
Labels: documentation, hacktoberfest

#1725 ignore patterns defined in dockerignore
  container.go
  container_test.go
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/consul/go.mod
  examples/consul/go.sum
  examples/nginx/go.mod
  examples/nginx/go.sum
  examples/toxiproxy/go.mod
  examples/toxiproxy/go.sum
  go.mod
  go.sum
  modules/artemis/go.mod
  modules/artemis/go.sum
  modules/cassandra/go.mod
  modules/cassandra/go.sum
  modules/clickhouse/go.mod
  modules/clickhouse/go.sum
  modules/couchbase/go.mod
  modules/couchbase/go.sum
  modules/elasticsearch/go.mod
  modules/elasticsearch/go.sum
  modules/gcloud/go.mod
  modules/gcloud/go.sum
  modules/k3s/go.mod
  modules/k3s/go.sum
  modules/k6/go.mod
  modules/k6/go.sum
  modules/kafka/go.mod
  modules/kafka/go.sum
  modules/localstack/go.mod
  modules/localstack/go.sum
  modules/mariadb/go.mod
  modules/mariadb/go.sum
  modules/mongodb/go.mod
  modules/mongodb/go.sum
  modules/mysql/go.mod
  modules/mysql/go.sum
  modules/nats/go.mod
  modules/nats/go.sum
  modules/neo4j/go.mod
  modules/neo4j/go.sum
  modules/postgres/go.mod
  modules/postgres/go.sum
  modules/pulsar/go.mod
  modules/pulsar/go.sum
  modules/rabbitmq/go.mod
  modules/rabbitmq/go.sum
  modules/redis/go.mod
  modules/redis/go.sum
  modules/redpanda/go.mod
  modules/redpanda/go.sum
  modules/vault/go.mod
  modules/vault/go.sum
  testdata/dockerignore/.dockerignore
Labels: feature, hacktoberfest

#1778 chore(deps): bump golang.org/x/mod from 0.12.0 to 0.13.0 in /modules/{elasticsearch,kafka} and /modulegen
  modulegen/go.mod
  modulegen/go.sum
  modules/elasticsearch/go.mod
  modules/elasticsearch/go.sum
  modules/kafka/go.mod
  modules/kafka/go.sum
Labels: dependencies

#1780 fix: use correct formatting directive for errors in lifecycle logs
  lifecycle.go
Labels: chore, hacktoberfest

#1779 fix: data race in docker client `Info()`
  commons-test.mk
  docker_client.go
  docker_client_test.go
Labels: bug

#1719 feat: support for replacing images with custom substitutions
  container.go
  container_test.go
  docker.go
  docs/features/common_functional_options.md
  docs/features/image_name_substitution.md
  generic.go
  mkdocs.yml
Labels: feature, hacktoberfest

#1787 chore(deps): combine and bump compose dependencies
  .github/workflows/ci.yml
  docs/features/docker_compose.md
  modulegen/_template/ci.yml.tmpl
  modulegen/main_test.go
  modules/compose/compose_api.go
  modules/compose/go.mod
  modules/compose/go.sum
Labels: dependencies, hacktoberfest

#1790 chore: add an example of using localstack alongside AWS lambdas
  generic.go
  modules/localstack/examples_test.go
  modules/localstack/go.mod
  modules/localstack/localstack.go
  modules/localstack/testdata/function.zip
  modules/localstack/testdata/index.js
Labels: chore

#1701 Log producer start stop sync
  docker.go
Labels: chore, hacktoberfest

#1794 chore: use HTTP calls to invoke the lambda from the tests
  modules/localstack/examples_test.go
Labels: chore

#1793 chore: expose SessionID
  testcontainer.go
  testcontainers_test.go
Labels: chore

#1822 chore(deps): bump google.golang.org/grpc from 1.57.0 to 1.57.1
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/consul/go.mod
  examples/consul/go.sum
  examples/nginx/go.mod
  examples/nginx/go.sum
  examples/toxiproxy/go.mod
  examples/toxiproxy/go.sum
  go.mod
  go.sum
  modules/artemis/go.mod
  modules/artemis/go.sum
  modules/cassandra/go.mod
  modules/cassandra/go.sum
  modules/clickhouse/go.mod
  modules/clickhouse/go.sum
  modules/couchbase/go.mod
  modules/couchbase/go.sum
  modules/elasticsearch/go.mod
  modules/elasticsearch/go.sum
  modules/gcloud/go.mod
  modules/gcloud/go.sum
  modules/k3s/go.mod
  modules/k3s/go.sum
  modules/k6/go.mod
  modules/k6/go.sum
  modules/kafka/go.mod
  modules/kafka/go.sum
  modules/localstack/go.mod
  modules/localstack/go.sum
  modules/mariadb/go.mod
  modules/mariadb/go.sum
  modules/mongodb/go.mod
  modules/mongodb/go.sum
  modules/mysql/go.mod
  modules/mysql/go.sum
  modules/nats/go.mod
  modules/nats/go.sum
  modules/neo4j/go.mod
  modules/neo4j/go.sum
  modules/postgres/go.mod
  modules/postgres/go.sum
  modules/pulsar/go.mod
  modules/pulsar/go.sum
  modules/rabbitmq/go.mod
  modules/rabbitmq/go.sum
  modules/redis/go.mod
  modules/redis/go.sum
  modules/redpanda/go.mod
  modules/redpanda/go.sum
  modules/vault/go.mod
  modules/vault/go.sum
Labels: dependencies

#1795 Add OpenSSF Scorecards GitHub Action
  .github/workflows/ci-test-go.yml
  .github/workflows/codeql.yml
  .github/workflows/scorecards.yml
  README.md
Labels: documentation

#1788 Auto-cleanup of k6 build cache
  docs/modules/k6.md
  modules/k6/examples_test.go
  modules/k6/k6.go
  modules/k6/k6_test.go
Labels: chore

#1785 feat: add image-keep option for built images
  container.go
  docker.go
  docker_test.go
  docs/features/build_from_dockerfile.md
Labels: enhancement

#1828 fix(redpanda): add wait for listening port condition on startup
  modules/redpanda/redpanda.go
Labels: chore
