Repository testcontainers/testcontainers-go, pull requests merged in 2023-11, with the labels that each got.

#1886 chore(deps): bump github.com/docker/docker from 24.0.6+incompatible to 24.0.7+incompatible
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/consul/go.mod
  examples/consul/go.sum
  examples/nginx/go.mod
  examples/nginx/go.sum
  examples/toxiproxy/go.mod
  examples/toxiproxy/go.sum
  go.mod
  go.sum
  modules/artemis/go.mod
  modules/artemis/go.sum
  modules/cassandra/go.mod
  modules/cassandra/go.sum
  modules/clickhouse/go.mod
  modules/clickhouse/go.sum
  modules/compose/go.mod
  modules/compose/go.sum
  modules/couchbase/go.mod
  modules/couchbase/go.sum
  modules/elasticsearch/go.mod
  modules/elasticsearch/go.sum
  modules/gcloud/go.mod
  modules/gcloud/go.sum
  modules/k3s/go.mod
  modules/k3s/go.sum
  modules/k6/go.mod
  modules/k6/go.sum
  modules/kafka/go.mod
  modules/kafka/go.sum
  modules/localstack/go.mod
  modules/localstack/go.sum
  modules/mariadb/go.mod
  modules/mariadb/go.sum
  modules/mongodb/go.mod
  modules/mongodb/go.sum
  modules/mysql/go.mod
  modules/mysql/go.sum
  modules/nats/go.mod
  modules/nats/go.sum
  modules/neo4j/go.mod
  modules/neo4j/go.sum
  modules/postgres/go.mod
  modules/postgres/go.sum
  modules/pulsar/go.mod
  modules/pulsar/go.sum
  modules/rabbitmq/go.mod
  modules/rabbitmq/go.sum
  modules/redis/go.mod
  modules/redis/go.sum
  modules/redpanda/go.mod
  modules/redpanda/go.sum
  modules/vault/go.mod
  modules/vault/go.sum
Labels: dependencies

#1887 feat: expose a WithNetwork functional option
  docs/features/common_functional_options.md
  docs/modules/localstack.md
  generic.go
  modules/localstack/localstack.go
Labels: feature

#1889 chore(deps): bump k8s.io/client-go from 0.28.2 to 0.28.3 in /modules/k3s
  modules/k3s/go.mod
  modules/k3s/go.sum
Labels: dependencies

#1890 chore(deps): bump Github actions
  .github/workflows/release-drafter.yml
  .github/workflows/scorecards.yml
Labels: dependencies

#1892 chore(deps): bump github.com/aws/aws-sdk-go and github.com/aws/aws-sdk-go-v2/config in /modules/localstack
  modules/localstack/go.mod
  modules/localstack/go.sum
Labels: dependencies

#1894 chore: add tests for withNetwork option
  container_test.go
  generic.go
  generic_test.go
  options.go
  options_test.go
Labels: chore

#1897 chore(deps): bump github.com/nats-io/nkeys and github.com/nats-io/nats.go in /modules/nats
  modules/nats/go.mod
  modules/nats/go.sum
Labels: dependencies

#1903 Fix - respect ContainerCustomizer in neo4j module
  modules/neo4j/examples_test.go
  modules/neo4j/neo4j.go
Labels: bug

#1896 chore(deps): bump github.com/twmb/franz-go and github.com/twmb/franz-go/pkg/kadm in /modules/redpanda
  modules/redpanda/go.mod
  modules/redpanda/go.sum
Labels: dependencies

#1905 chore: make rabbitmq examples more readable
  modules/rabbitmq/examples_test.go
  modules/rabbitmq/types_test.go
  options.go
Labels: chore

#1899 feat: Allow the container working directory to be specified
  container.go
  docker.go
  docker_test.go
Labels: feature

#1904 fix(reaper): fix race condition when reusing reapers
  reaper.go
  reaper_test.go
Labels: bug

#1907 chore: deprecate BindMount APIs
  container.go
  container_test.go
  docker.go
  docker_auth_test.go
  docker_mounts.go
  docker_test.go
  docs/features/copy_file.md
  docs/features/files_and_mounts.md
  lifecycle_test.go
  mkdocs.yml
  mounts.go
  mounts_test.go
  reaper.go
  reaper_test.go
Labels: chore

#1909 lint: enable nonamedreturns
  .golangci.yml
  docker.go
  modules/kafka/consumer_test.go
  modules/localstack/localstack.go
  wait/exit.go
  wait/health.go
  wait/host_port.go
  wait/http.go
  wait/log.go
  wait/sql.go
Labels: chore

#1902 Reduce flakiness in ClickHouse tests
  modules/clickhouse/clickhouse_test.go
Labels: chore

#1916 Add database driver note to SQL Wait strategy docs
  docs/features/wait/sql.md
Labels: documentation

#1918 docs: fix code snippet for image substitution
  docs/features/image_name_substitution.md
Labels: documentation

#1923 fix(modules.kafka): Switch to MaxInt for 32-bit support
  modules/kafka/kafka.go
Labels: bug

#1914 feat: support for executing commands in a container with user, workDir and env
  docker.go
  docker_exec_test.go
  docs/features/common_functional_options.md
  exec/processor.go
  modules/cassandra/executable.go
  modules/rabbitmq/examples_test.go
  modules/rabbitmq/rabbitmq_test.go
  modules/rabbitmq/types_test.go
  options.go
  options_test.go
Labels: breaking change, enhancement

#1825 docs: add some Vault module examples
  docker_test.go
  modules/vault/examples_test.go
  network_test.go
  wait/exec_test.go
  wait/http_test.go
Labels: documentation

#1925 chore: skip TestContainerLogWithErrClosed as flaky on rootless docker
  logconsumer_test.go
Labels: chore

#1910 Add username and password functions to mongodb
  modules/mongodb/mongodb.go
  modules/mongodb/mongodb_test.go
Labels: feature

#1928 feat: support for custom registry prefixes at the configuration level
  container.go
  container_test.go
  docker.go
  docs/features/common_functional_options.md
  docs/features/configuration.md
  docs/features/image_name_substitution.md
  docs/system_requirements/ci/bitbucket_pipelines.md
  image_substitutors_test.go
  internal/config/config.go
  internal/config/config_test.go
  mkdocs.yml
  network.go
  options.go
  reaper.go
  reaper_test.go
  scripts/bump-reaper.sh
Labels: feature

#1930 docs: include MongoDB's username and password options into the docs
  docs/modules/mongodb.md
  modules/mongodb/mongodb.go
  scripts/pre-release.sh
Labels: documentation

#1931 feat: support customizing the Docker build command
  container.go
  docker.go
  docs/features/build_from_dockerfile.md
  from_dockerfile_test.go
  testdata/target.Dockerfile
Labels: breaking change

#1927 fix: fallback matching of registry authentication config
  docker_auth.go
  docker_auth_test.go
Labels: bug
