Repository testcontainers/testcontainers-go, pull requests merged in 2023-04, with the labels that each got.

#1032 docs: add permalink to mkdocs headings
  mkdocs.yml
Labels: documentation

#1035 feat: support for wait.ForExec with response matcher
  docs/features/wait/exec.md
  wait/exec.go
  wait/exec_test.go
Labels: feature

#1036 feat: provide container lifecycle hooks
  container.go
  docker.go
  docs/features/creating_container.md
  lifecycle.go
  lifecycle_test.go
Labels: feature

#1037 chore: support for multiple lifecycles defined by the user
  container.go
  docker.go
  docs/features/creating_container.md
  lifecycle.go
  lifecycle_test.go
Labels: chore

#1042 feat: use an interface for container customization in modules
  docs/modules/couchbase.md
  docs/modules/index.md
  docs/modules/localstack.md
  docs/modules/mysql.md
  docs/modules/postgres.md
  docs/modules/pulsar.md
  docs/modules/redis.md
  generic.go
  modulegen/_template/docs_example.md.tmpl
  modulegen/_template/example.go.tmpl
  modulegen/main_test.go
  modules/couchbase/couchbase.go
  modules/couchbase/couchbase_test.go
  modules/couchbase/options.go
  modules/couchbase/service.go
  modules/localstack/go.mod
  modules/localstack/localstack.go
  modules/localstack/localstack_test.go
  modules/localstack/types.go
  modules/localstack/v1/s3_test.go
  modules/localstack/v2/s3_test.go
  modules/mysql/mysql.go
  modules/neo4j/config.go
  modules/neo4j/neo4j.go
  modules/postgres/postgres.go
  modules/pulsar/pulsar.go
  modules/pulsar/pulsar_test.go
  modules/redis/redis.go
  modules/vault/vault.go
  modules/vault/vault_test.go
  testcontainer.go
Labels: feature

#1059 fix: generated code must compile
  modulegen/_template/example_test.go.tmpl
  modulegen/main.go
  modulegen/main_test.go
Labels: bug

#1074 chore(deps): bump github.com/docker/docker from 23.0.2+incompatible to 23.0.3+incompatible in /modules
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/consul/go.mod
  examples/consul/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  go.mod
  go.sum
  modules/neo4j/go.mod
  modules/neo4j/go.sum
  modules/pulsar/go.mod
  modules/pulsar/go.sum
  modules/vault/go.mod
  modules/vault/go.sum
Labels: dependencies

#1076 chore(deps): bump docker libs in /modules/compose
  modules/compose/go.mod
  modules/compose/go.sum
Labels: dependencies

#1077 chore(deps): bump aws deps in /modules/localstack
  modules/localstack/go.mod
  modules/localstack/go.sum
Labels: dependencies

#1039 feat: Add ability to disable internal checks for `wait.HostPortStrategy`
  wait/host_port.go
  wait/host_port_test.go
Labels: enhancement
