Repository testcontainers/testcontainers-go, pull requests merged in 2023-12, with the labels that each got.

#1933 fix: exec multiplexed to return stderr
  docker_exec_test.go
  exec/processor.go
  modules/compose/go.mod
  modules/compose/go.sum
Labels: feature

#1954 chore(deps): bump k8s.io from 0.28.3 to 0.28.4 in /modules/k3s
  modules/k3s/go.mod
  modules/k3s/go.sum
Labels: dependencies

#1953 chore(deps): bump github.com/aws/aws-sdk-go and github.com/aws/aws-sdk-go-v2 in /modules/localstack
  modules/localstack/go.mod
  modules/localstack/go.sum
  modules/localstack/v2/s3_test.go
Labels: dependencies

#1967 chore(deps): bump github.com/elastic/go-elasticsearch/v8 from 8.10.1 to 8.11.1 and golang.org/x/mod from 0.13.0 to 0.14.0 in /modules/elasticsearch
  modules/elasticsearch/go.mod
  modules/elasticsearch/go.sum
Labels: dependencies

#1969 feat: add module to support Microsoft SQL Server
  .github/dependabot.yml
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/mssql.md
  mkdocs.yml
  modules/mssql/Makefile
  modules/mssql/examples_test.go
  modules/mssql/go.mod
  modules/mssql/go.sum
  modules/mssql/mssql.go
  modules/mssql/mssql_test.go
  sonar-project.properties
Labels: feature

#1981 chore(deps): bump github.com/aws/aws-sdk-go and github.com/aws/aws-sdk-go-v2 in /modules/localstack
  modules/localstack/go.mod
  modules/localstack/go.sum
Labels: dependencies

#1983 chore(deps): bump google.golang.org/api from 0.152.0 to 0.153.0, cloud.google.com/go/bigtable from 1.20.0 to 1.21.0 and cloud.google.com/go/spanner from 1.53.0 to 1.53.1 in /modules/gcloud
  modules/gcloud/go.mod
  modules/gcloud/go.sum
Labels: dependencies

#1970 Add more content on how to use Exec function
  docker_test.go
  docs/features/override_container_command.md
Labels: documentation

#1993 feat: create networks with random names
  docker.go
  docker_test.go
  docs/features/common_functional_options.md
  docs/features/creating_networks.md
  docs/features/networking.md
  examples/toxiproxy/go.mod
  examples/toxiproxy/toxiproxy_test.go
  generic.go
  modules/localstack/examples_test.go
  modules/localstack/localstack.go
  modules/localstack/localstack_test.go
  modules/pulsar/pulsar_test.go
  network.go
  network/network.go
  network/network_test.go
  network_test.go
  options.go
  options_test.go
Labels: feature

#2006 chore(deps): bump golang.org/x/crypto to 0.17.0 in /modules
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  modules/compose/go.mod
  modules/compose/go.sum
  modules/gcloud/go.mod
  modules/gcloud/go.sum
  modules/kafka/go.mod
  modules/kafka/go.sum
  modules/mongodb/go.mod
  modules/mongodb/go.sum
  modules/mssql/go.mod
  modules/mssql/go.sum
  modules/nats/go.mod
  modules/nats/go.sum
  modules/redpanda/go.mod
  modules/redpanda/go.sum
Labels: dependencies, security

#2039 chore: lookup exposed ports in the image from Config, not from ContainerConfig
  lifecycle.go
Labels: chore

#2038 feat: support configuring Ryuk verbose mode at config level
  docs/features/configuration.md
  internal/config/config.go
  internal/config/config_test.go
  reaper.go
  reaper_test.go
Labels: feature

#2040 chore: bump Ryuk to 0.6.0
  internal/config/config.go
Labels: dependencies

#2036 Add neo4j license agreement customization options
  modules/neo4j/config.go
  modules/neo4j/neo4j_test.go
Labels: enhancement

#2046 fix: remove docker.io from Ryuk image name
  internal/config/config.go
Labels: bug

#2047 chore: do not read config but instead pass the hub prefix to the prependHub modifier
  docker.go
  image_substitutors_test.go
  options.go
Labels: chore
