Repository testcontainers/testcontainers-go, pull requests merged in 2023-01, with the labels that each got.

#647 feat: support passing registry credentials to the reaper
  container.go
  docker.go
  network.go
  reaper.go
  reaper_test.go
Labels: chore

#723 MongoDB example
  .github/dependabot.yml
  .github/workflows/mongodb-example.yml
  docs/examples/mongodb.md
  examples/mongodb/Makefile
  examples/mongodb/go.mod
  examples/mongodb/go.sum
  examples/mongodb/mongodb.go
  examples/mongodb/mongodb_test.go
  examples/mongodb/tools/tools.go
  mkdocs.yml
Labels: documentation

#726 simplify mongodb test
  examples/mongodb/mongodb_test.go
Labels: documentation

#741 chore(deps): bump google.golang.org/grpc from 1.51.0 to 1.52.0 in /examples
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
Labels: dependencies

#773 chore(deps): bump google.golang.org/api from 0.105.0 to 0.108.0 in /examples
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
Labels: dependencies

#774 chore(deps): bump gotest.tools/gotestsum from 1.8.2 to 1.9.0
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/consul/go.mod
  examples/consul/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/mongodb/go.mod
  examples/mongodb/go.sum
  examples/mysql/go.mod
  examples/mysql/go.sum
  examples/nginx/go.mod
  examples/nginx/go.sum
  examples/postgres/go.mod
  examples/postgres/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/pulsar/go.mod
  examples/pulsar/go.sum
  examples/redis/go.mod
  examples/redis/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
  examples/toxiproxy/go.mod
  examples/toxiproxy/go.sum
  go.mod
  go.sum
  modules/compose/go.mod
  modules/compose/go.sum
Labels: dependencies

#721 Reaper container should not be labeled with "org.testcontainers.golang.sessionId"
  reaper.go
  reaper_test.go
Labels: bug

#775 chore: support for titles in examples
  docs/examples/index.md
  examples/_template/Makefile.tmpl
  examples/_template/ci.yml.tmpl
  examples/_template/docs_example.md.tmpl
  examples/_template/example.go.tmpl
  examples/_template/example_test.go.tmpl
  examples/_template/go.mod.tmpl
  examples/_template/tools.go.tmpl
  examples/main.go
  examples/main_test.go
Labels: enhancement

#783 chore(deps): bump google.golang.org/grpc from 1.52.0 to 1.52.1 in /examples
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
Labels: dependencies

#789 chore: check dependabot dependencies weekly
  .github/dependabot.yml
  examples/dependabot.go
  examples/dependabot_test.go
Labels: chore, dependencies

#790 chore(deps): bump google.golang.org/grpc from 1.52.1 to 1.52.3 in /examples
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
Labels: dependencies

#791 fix: use right import package for compose in docs
  docs/features/docker_compose.md
Labels: documentation, bug

#792 chore: build images with backoff retries
  docker.go
Labels: chore

#794 chore: run "go mod tidy" automatically when creating examples
  examples/_template/go.sum.tmpl
  examples/main.go
Labels: chore

#796 chore: extract docker host calculation to an internal package
  docker.go
  internal/testcontainersdocker/docker_host.go
  internal/testcontainersdocker/docker_host_test.go
  reaper.go
  reaper_test.go
Labels: chore

#797 chore: bump containerd in examples
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/consul/go.mod
  examples/consul/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/mongodb/go.mod
  examples/mongodb/go.sum
  examples/mysql/go.mod
  examples/mysql/go.sum
  examples/nginx/go.mod
  examples/nginx/go.sum
  examples/postgres/go.mod
  examples/postgres/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/pulsar/go.mod
  examples/pulsar/go.sum
  examples/redis/go.mod
  examples/redis/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
  examples/toxiproxy/go.mod
  examples/toxiproxy/go.sum
Labels: dependencies

#782 Verify Reaper state to create new or return existing instance
  docker.go
  reaper.go
  reaper_test.go
Labels: bug
