Repository testcontainers/testcontainers-go, pull requests merged in 2023-03, with the labels that each got.

#894 fix: proper sorting of dependabot updates when generating a module
  .github/dependabot.yml
  modulegen/_template/go.mod.tmpl
  modulegen/main.go
  modulegen/main_test.go
Labels: bug

#906 chore: monthly updates for dependabot
  .github/dependabot.yml
  modulegen/dependabot.go
  modulegen/dependabot_test.go
Labels: chore, dependencies

#907 chore(deps): bump github.com/aws/aws-sdk-go deps in localstack module
  modules/localstack/go.mod
  modules/localstack/go.sum
Labels: dependencies

#908 chore(deps): bump google.golang.org/api from 0.110.0 to 0.111.0 in /examples
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
Labels: dependencies

#911 chore: update module dependencies
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/consul/go.mod
  examples/consul/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/mongodb/go.mod
  examples/mongodb/go.sum
  examples/mysql/go.mod
  examples/mysql/go.sum
  examples/nginx/go.mod
  examples/nginx/go.sum
  examples/postgres/go.mod
  examples/postgres/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/pulsar/go.mod
  examples/pulsar/go.sum
  examples/redis/go.mod
  examples/redis/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
  examples/toxiproxy/go.mod
  examples/toxiproxy/go.sum
  modules/localstack/go.mod
  modules/localstack/go.sum
Labels: dependencies

#872 feat: convert pulsar example into a Go module
  .github/dependabot.yml
  .github/workflows/module-pulsar.yml
  docs/examples/pulsar.md
  docs/modules/pulsar.md
  examples/pulsar/pulsar.go
  examples/pulsar/pulsar_test.go
  mkdocs.yml
  modules/pulsar/Makefile
  modules/pulsar/go.mod
  modules/pulsar/go.sum
  modules/pulsar/pulsar.go
  modules/pulsar/pulsar_test.go
  modules/pulsar/tools/tools.go
Labels: feature

#919 chore(deps): bump dependencies
  go.mod
  go.sum
  modulegen/go.mod
  modulegen/go.sum
  modules/localstack/go.mod
  modules/localstack/go.sum
Labels: dependencies

#920 chore: sync dependencies in Go modules
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/consul/go.mod
  examples/consul/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/mongodb/go.mod
  examples/mongodb/go.sum
  examples/mysql/go.mod
  examples/mysql/go.sum
  examples/nginx/go.mod
  examples/nginx/go.sum
  examples/postgres/go.mod
  examples/postgres/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/redis/go.mod
  examples/redis/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
  examples/toxiproxy/go.mod
  examples/toxiproxy/go.sum
  modules/pulsar/go.mod
  modules/pulsar/go.sum
Labels: dependencies

#869 feat: support for reading auth credentials from docker credential helpers
  container.go
  container_test.go
  docker.go
  docker_auth.go
  docker_auth_test.go
  docker_test.go
  docs/features/build_from_dockerfile.md
  docs/features/docker_auth.md
  go.mod
  go.sum
  internal/testcontainersdocker/images.go
  internal/testcontainersdocker/images_test.go
  internal/testcontainersdocker/testresources/Dockerfile
  internal/testcontainersdocker/testresources/Dockerfile.multistage
  internal/testcontainersdocker/testresources/Dockerfile.multistage.multiBuildArgs
  internal/testcontainersdocker/testresources/Dockerfile.multistage.singleBuildArgs
  mkdocs.yml
  reaper.go
  reaper_test.go
  testresources/.docker/config.json
Labels: feature

#924 chore: bump minimal compile version of GO to 1.19
  .github/workflows/bigtable-example.yml
  .github/workflows/ci.yml
  .github/workflows/cockroachdb-example.yml
  .github/workflows/consul-example.yml
  .github/workflows/datastore-example.yml
  .github/workflows/firestore-example.yml
  .github/workflows/module-compose.yml
  .github/workflows/module-localstack.yml
  .github/workflows/module-pulsar.yml
  .github/workflows/mongodb-example.yml
  .github/workflows/mysql-example.yml
  .github/workflows/nginx-example.yml
  .github/workflows/postgres-example.yml
  .github/workflows/pubsub-example.yml
  .github/workflows/redis-example.yml
  .github/workflows/spanner-example.yml
  .github/workflows/toxiproxy-example.yml
  examples/bigtable/go.mod
  examples/cockroachdb/go.mod
  examples/consul/go.mod
  examples/datastore/go.mod
  examples/firestore/go.mod
  examples/mongodb/go.mod
  examples/mysql/go.mod
  examples/nginx/go.mod
  examples/postgres/go.mod
  examples/pubsub/go.mod
  examples/redis/go.mod
  examples/spanner/go.mod
  examples/toxiproxy/go.mod
  go.mod
  modulegen/_template/ci.yml.tmpl
  modulegen/_template/go.mod.tmpl
  modulegen/go.mod
  modules/compose/go.mod
  modules/localstack/go.mod
  modules/pulsar/go.mod
  wait/testdata/go.mod
Labels: chore

#910 remove volumes on down
  modules/compose/compose_api.go
  modules/compose/compose_api_test.go
  modules/compose/go.mod
  modules/compose/go.sum
Labels: chore, compose

#927 chore: sync dependencies
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/consul/go.mod
  examples/consul/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/mongodb/go.mod
  examples/mongodb/go.sum
  examples/mysql/go.mod
  examples/mysql/go.sum
  examples/nginx/go.mod
  examples/nginx/go.sum
  examples/postgres/go.mod
  examples/postgres/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/redis/go.mod
  examples/redis/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
  examples/toxiproxy/go.mod
  examples/toxiproxy/go.sum
  modules/localstack/go.mod
  modules/localstack/go.sum
  modules/pulsar/go.mod
  modules/pulsar/go.sum
Labels: dependencies

#928 fix: use right paths in the release script
  scripts/release.sh
Labels: chore

#929 chore: prepare Go modules for the next release
  RELEASING.md
  examples/bigtable/go.mod
  examples/cockroachdb/go.mod
  examples/consul/go.mod
  examples/datastore/go.mod
  examples/firestore/go.mod
  examples/mongodb/go.mod
  examples/mysql/go.mod
  examples/nginx/go.mod
  examples/postgres/go.mod
  examples/pubsub/go.mod
  examples/redis/go.mod
  examples/spanner/go.mod
  examples/toxiproxy/go.mod
  mkdocs.yml
  modules/compose/go.mod
  modules/localstack/go.mod
  modules/pulsar/go.mod
  scripts/release.sh
Labels: chore, dependencies

#931 fix: move to the right dir to git commit when releasing
  scripts/release.sh
Labels: chore

#876 add couchbase module
  .github/dependabot.yml
  .github/workflows/module-couchbase.yml
  docs/modules/couchbase.md
  mkdocs.yml
  modules/couchbase/Makefile
  modules/couchbase/bucket.go
  modules/couchbase/couchbase.go
  modules/couchbase/couchbase_test.go
  modules/couchbase/go.mod
  modules/couchbase/go.sum
  modules/couchbase/options.go
  modules/couchbase/service.go
  modules/couchbase/storage_mode.go
  modules/couchbase/tools/tools.go
Labels: feature

#936 chore: bump Ryuk to latest release
  reaper.go
Labels: dependencies

#940 fix: update code snippet for Docker Auth
  docker_test.go
  docs/features/docker_auth.md
Labels: documentation

#950 Use `hashicorp/consul` in examples
  examples/consul/consul.go
Labels: chore

#945 feat: add Postgres module
  .github/dependabot.yml
  .github/workflows/module-postgres.yml
  docs/examples/postgres.md
  docs/modules/postgres.md
  examples/postgres/postgres.go
  examples/postgres/postgres_test.go
  mkdocs.yml
  modules/postgres/Makefile
  modules/postgres/go.mod
  modules/postgres/go.sum
  modules/postgres/postgres.go
  modules/postgres/postgres_test.go
  modules/postgres/testresources/init-user-db.sh
  modules/postgres/testresources/my-postgres.conf
  modules/postgres/tools/tools.go
Labels: enhancement

#974 chore(deps): bump compose dependencies in /modules/compose
  modules/compose/go.mod
  modules/compose/go.sum
Labels: dependencies

#973 chore(deps): bump google.golang.org/grpc from 1.53.0 to 1.54.0 in /examples
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
Labels: dependencies

#971 docs: extend Couchbase docs
  docs/modules/couchbase.md
  modules/couchbase/bucket.go
  modules/couchbase/couchbase.go
  modules/couchbase/couchbase_test.go
  modules/couchbase/options.go
  modules/couchbase/storage_mode.go
Labels: documentation

#942 feat: add Vault Module
  .github/dependabot.yml
  .github/workflows/module-vault.yml
  docs/modules/vault.md
  mkdocs.yml
  modules/vault/Makefile
  modules/vault/go.mod
  modules/vault/go.sum
  modules/vault/tools/tools.go
  modules/vault/vault.go
  modules/vault/vault_test.go
Labels: enhancement

#979 chore: update Go deps in modules
  .github/workflows/module-couchbase.yml
  modules/vault/go.mod
  modules/vault/go.sum
Labels: dependencies

#943 Add MySQL module
  .github/dependabot.yml
  .github/workflows/module-mysql.yml
  docs/examples/mysql.md
  docs/modules/mysql.md
  examples/mysql/mysql.go
  examples/mysql/mysql_test.go
  mkdocs.yml
  modules/mysql/Makefile
  modules/mysql/go.mod
  modules/mysql/go.sum
  modules/mysql/mysql.go
  modules/mysql/mysql_test.go
  modules/mysql/testresources/my.cnf
  modules/mysql/testresources/schema.sql
  modules/mysql/tools/tools.go
Labels: enhancement

#937 Neo4j
  .github/dependabot.yml
  .github/workflows/module-neo4j.yml
  docs/modules/neo4j.md
  mkdocs.yml
  modules/neo4j/Makefile
  modules/neo4j/config.go
  modules/neo4j/go.mod
  modules/neo4j/go.sum
  modules/neo4j/neo4j.go
  modules/neo4j/neo4j_test.go
  modules/neo4j/tools/tools.go
Labels: enhancement

#990 docs: fix technology name
  docs/modules/neo4j.md
Labels: documentation

#991 chore: include how to install the module in the generated docs
  modulegen/_template/docs_example.md.tmpl
  modulegen/main_test.go
Labels: chore

#995 chore: render logos from the base location
  docs/theme/partials/nav.html
Labels: chore

#996 chore: skip CI builds when updating the docs
  .github/workflows/bigtable-example.yml
  .github/workflows/ci-reaper-off.yml
  .github/workflows/ci.yml
  .github/workflows/cockroachdb-example.yml
  .github/workflows/consul-example.yml
  .github/workflows/datastore-example.yml
  .github/workflows/firestore-example.yml
  .github/workflows/module-compose.yml
  .github/workflows/module-couchbase.yml
  .github/workflows/module-localstack.yml
  .github/workflows/module-mysql.yml
  .github/workflows/module-neo4j.yml
  .github/workflows/module-postgres.yml
  .github/workflows/module-pulsar.yml
  .github/workflows/module-vault.yml
  .github/workflows/mongodb-example.yml
  .github/workflows/nginx-example.yml
  .github/workflows/pubsub-example.yml
  .github/workflows/redis-example.yml
  .github/workflows/spanner-example.yml
  .github/workflows/toxiproxy-example.yml
  modulegen/_template/ci.yml.tmpl
  modulegen/main_test.go
Labels: chore

#998 Revert "chore: render logos from the base location (#995)"
  docs/theme/partials/nav.html
Labels: chore

#982 feat: Auto detect the use of Podman from DOCKER_HOST
  docs/system_requirements/using_podman.md
  provider.go
  provider_test.go
Labels: podman, enhancement

#993 feat: add Redis module
  .github/dependabot.yml
  .github/workflows/module-redis.yml
  docs/examples/redis.md
  docs/modules/redis.md
  docs/quickstart.md
  examples/redis/redis.go
  examples/redis/redis_test.go
  mkdocs.yml
  modules/redis/Makefile
  modules/redis/go.mod
  modules/redis/go.sum
  modules/redis/redis.go
  modules/redis/redis_test.go
  modules/redis/testdata/Dockerfile
  modules/redis/testdata/redis6.conf
  modules/redis/testdata/redis7.conf
  modules/redis/tools/tools.go
Labels: feature

#1026 chore(deps): bump github.com/docker/docker from 23.0.1+incompatible to 23.0.2+incompatible
  go.mod
  go.sum
  modules/compose/go.mod
  modules/compose/go.sum
  modules/pulsar/go.mod
  modules/pulsar/go.sum
  modules/vault/go.mod
  modules/vault/go.sum
Labels: dependencies
