Repository testcontainers/testcontainers-go, pull requests merged in 2023-02, with the labels that each got.

#799 chore: restructure Docker helper methods
  docker.go
  internal/testcontainersdocker/docker_host.go
  internal/testcontainersdocker/docker_host_test.go
  internal/testcontainerssession/session.go
  session.go
Labels: chore

#810 chore(deps): bump google.golang.org/api from 0.108.0 to 0.109.0 in /examples
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
Labels: dependencies

#812 fix: Synchronise writes to dockerCompose.containers map
  modules/compose/compose_api.go
Labels: bug

#802 fix: nil pointer dereference in HealthStrategy
  wait/health.go
  wait/health_test.go
Labels: bug

#813 chore: update Docker labels for containers
  docker.go
  docker_test.go
  internal/testcontainersdocker/labels.go
  internal/version.go
  reaper.go
  reaper_test.go
Labels: chore

#827 chore(deps): bump google.golang.org/grpc from 1.52.3 to 1.53.0 in /examples
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
Labels: dependencies

#836 chore(deps): bump google.golang.org/api from 0.109.0 to 0.110.0 in /examples
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
Labels: dependencies

#814 fix: always absolute paths when tarring files to a Docker container
  container.go
  docker_test.go
  file.go
  file_test.go
Labels: bug

#776 chore: automate the creation of a release
  RELEASING.md
  scripts/release.sh
Labels: documentation, chore

#633 chore: move host-config and endpoint settings to a specific modifiers
  container.go
  docker.go
  docker_test.go
  docs/features/creating_container.md
  lifecycle.go
  lifecycle_test.go
  reaper.go
  reaper_test.go
Labels: enhancement

#839 fix: tune release script
  scripts/release.sh
Labels: chore

#840 chore: prepare for next minor development cycle (0.19.0)
  internal/version.go
  mkdocs.yml
Labels: chore

#858 chore: bump golang/x/net and containerd
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/consul/go.mod
  examples/consul/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/mongodb/go.mod
  examples/mongodb/go.sum
  examples/mysql/go.mod
  examples/mysql/go.sum
  examples/nginx/go.mod
  examples/nginx/go.sum
  examples/postgres/go.mod
  examples/postgres/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/pulsar/go.mod
  examples/pulsar/go.sum
  examples/redis/go.mod
  examples/redis/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
  examples/toxiproxy/go.mod
  examples/toxiproxy/go.sum
  go.mod
  go.sum
  modulegen/_template/go.mod.tmpl
  modulegen/go.sum
  modules/compose/go.mod
  modules/compose/go.sum
  modules/localstack/go.mod
  modules/localstack/go.sum
Labels: security

#859 chore: sync governance files
  .github/release-drafter.yml
  .github/settings.yml
  docs/language-logos/haskell.svg
Labels: chore

#860 docs: include haskell logo to the website
  docs/index.md
Labels: documentation

#871 chore: remove replace directive in modules
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/consul/go.mod
  examples/consul/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/mongodb/go.mod
  examples/mongodb/go.sum
  examples/mysql/go.mod
  examples/mysql/go.sum
  examples/nginx/go.mod
  examples/nginx/go.sum
  examples/postgres/go.mod
  examples/postgres/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/pulsar/go.mod
  examples/pulsar/go.sum
  examples/redis/go.mod
  examples/redis/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
  examples/toxiproxy/go.mod
  examples/toxiproxy/go.sum
  modulegen/_template/go.mod.tmpl
  modules/localstack/go.mod
  modules/localstack/go.sum
Labels: chore, dependencies

#873 chore: simplify env vars for localstack module
  modules/localstack/localstack.go
  modules/localstack/localstack_test.go
  modules/localstack/v1/s3_test.go
  modules/localstack/v2/s3_test.go
Labels: chore

#875 chore(deps): bump github.com/docker deps from 23.0.0+incompatible to 23.0.1+incompatible
  go.mod
  go.sum
  modules/compose/go.mod
  modules/compose/go.sum
Labels: dependencies

#877 fix: update modules path in generator
  modulegen/_template/ci.yml.tmpl
  modulegen/_template/docs_example.md.tmpl
  modulegen/_template/tools.go.tmpl
  modulegen/main.go
  modulegen/main_test.go
Labels: bug

#878 Update docs link for tc-node
  docs/index.md
Labels: documentation

#890 docs: add social links in the website
  docs/css/extra.css
  docs/icons/github.svg
  docs/icons/slack.svg
  docs/icons/stackoverflow.svg
  docs/icons/twitter.svg
  docs/theme/main.html
  docs/theme/partials/nav.html
  mkdocs.yml
  modulegen/mkdocs.go
Labels: documentation

#891 chore(deps): bump github.com/stretchr/testify from 1.8.1 to 1.8.2
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/postgres/go.mod
  examples/postgres/go.sum
  examples/redis/go.mod
  examples/redis/go.sum
  go.mod
  go.sum
  modulegen/go.mod
  modulegen/go.sum
  modules/compose/go.mod
  modules/compose/go.sum
  modules/localstack/go.mod
  modules/localstack/go.sum
Labels: dependencies

#301 feat: add basic auth support in the wait.ForHTTP strategy
  docs/features/wait/http.md
  wait/http.go
  wait/http_test.go
  wait/testdata/main.go
Labels: feature
