Repository testcontainers/testcontainers-go, pull requests merged in 2023-06, with the labels that each got.

#1252 docs: fix passing env vars example
  docs/features/build_from_dockerfile.md
Labels: documentation

#1284 chore(deps): bump google.golang.org/api from 0.124.0 to 0.125.0 in /examples
  examples/bigtable/go.mod
  examples/bigtable/go.sum
  examples/datastore/go.mod
  examples/datastore/go.sum
  examples/firestore/go.mod
  examples/firestore/go.sum
  examples/pubsub/go.mod
  examples/pubsub/go.sum
  examples/spanner/go.mod
  examples/spanner/go.sum
Labels: dependencies

#1285 fix: skip host network tests in Docker Desktop
  docker_test.go
  docs/features/networking.md
  testing.go
Labels: chore

#1292 chore: simplify ReadConfig signature, not passing context
  config.go
  config_test.go
  docker_test.go
  docs/features/configuration.md
  internal/config/config.go
  internal/config/config_test.go
  internal/testcontainersdocker/client.go
  internal/testcontainersdocker/docker_host.go
  logconsumer_test.go
  provider.go
Labels: chore

#1289 fix: support detecting if k3s module is running from inside a Docker container
  modules/k3s/k3s.go
Labels: bug

#1296 Fix locations set to None in sitemap
  mkdocs.yml
Labels: chore

#1086 fix: use first exposed port by default in HTTP wait strategy
  docs/features/wait/http.md
  wait/http.go
  wait/http_test.go
Labels: bug

#1298 docs: document CI services
  docker_auth_test.go
  docs/features/files_and_mounts.md
  docs/system_requirements/ci/aws_codebuild.md
  docs/system_requirements/ci/bitbucket_pipelines.md
  docs/system_requirements/ci/circle_ci.md
  docs/system_requirements/ci/concourse_ci.md
  docs/system_requirements/ci/dind_patterns.md
  docs/system_requirements/ci/drone.md
  docs/system_requirements/ci/gitlab_ci.md
  docs/system_requirements/ci/tekton.md
  docs/system_requirements/ci/travis.md
  mkdocs.yml
  modulegen/mkdocs.go
  mounts_test.go
Labels: documentation

#1297 feat: provide container logs on container startup failures
  docker.go
  lifecycle.go
  lifecycle_test.go
Labels: feature
