Repository testcontainers/testcontainers-go, pull requests merged in 2024-04, with the labels that each got.

#2464 chore: use "docker compose" (v2) instead of "docker-compose" (v1)
  docs/features/docker_compose.md
  modules/compose/compose.go
  modules/compose/compose_api.go
  modules/compose/compose_local.go
Labels: chore, compose

#2462 bug:Fix AMQPS url
  modules/rabbitmq/rabbitmq.go
  modules/rabbitmq/rabbitmq_test.go
Labels: bug

#2463 Upgrade neo4j module to use features from v0.29.1 of testcontainers-go
  docs/features/common_functional_options.md
  modules/neo4j/config.go
Labels: chore

#2452 fix(exec): updates the `Multiplexed` opt to combine stdout and stderr
  docker_exec_test.go
  exec/processor.go
Labels: bug

#2450 feat: optimizes file copies to and from containers
  docker.go
  file.go
  file_test.go
Labels: feature

#2350 feat(k6):Add remote test scripts
  docs/modules/k6.md
  modules/k6/k6.go
  modules/k6/k6_test.go
Labels: feature

#2346 fix: logging deadlock
  docker.go
  lifecycle.go
  logconsumer_test.go
Labels: bug

#2466 Fix: HTTP wait strategy does not take query params into account
  wait/http.go
  wait/http_test.go
  wait/testdata/main.go
Labels: bug

#2476 fix: handle dockerignore exclusions properly
  container.go
  container_ignore_test.go
  docs/features/build_from_dockerfile.md
Labels: chore

#2475 Elasticsearch disable CA retrieval when ssl is disabled
  modules/elasticsearch/elasticsearch.go
  modules/elasticsearch/elasticsearch_test.go
Labels: enhancement

#2478 chore: create TLS certs in a consistent manner
  container.go
  docker.go
  docker_exec_test.go
  docs/features/tls.md
  mkdocs.yml
  modules/cockroachdb/certs.go
  modules/cockroachdb/go.mod
  modules/cockroachdb/go.sum
  modules/rabbitmq/examples_test.go
  modules/rabbitmq/go.mod
  modules/rabbitmq/go.sum
  modules/rabbitmq/rabbitmq_test.go
  modules/rabbitmq/testdata/certs/server_ca.pem
  modules/rabbitmq/testdata/certs/server_cert.pem
  modules/rabbitmq/testdata/certs/server_key.pem
  modules/redpanda/go.mod
  modules/redpanda/go.sum
  modules/redpanda/redpanda_test.go
  reaper.go
Labels: chore

#2177 support Dolt
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/dolt.md
  mkdocs.yml
  modules/dolt/Makefile
  modules/dolt/dolt.go
  modules/dolt/dolt_test.go
  modules/dolt/examples_test.go
  modules/dolt/go.mod
  modules/dolt/go.sum
  modules/dolt/testdata/check_clone_private.sh
  modules/dolt/testdata/check_clone_public.sh
  modules/dolt/testdata/clone-db.sh
  modules/dolt/testdata/dolt_1_32_4.cnf
  modules/dolt/testdata/schema.sql
  sonar-project.properties
Labels: enhancement

#2481 feat: Bump default postgres version
  docs/modules/postgres.md
  modules/postgres/examples_test.go
  modules/postgres/postgres.go
Labels: enhancement

#2489 fix(postgres): Fix the non-default dbname error
  docs/modules/postgres.md
  modules/postgres/postgres.go
  modules/postgres/postgres_test.go
Labels: bug

#2488 fix: fallback to URL-path when parsing auth config URL without scheme
  docker_auth.go
  docker_auth_test.go
Labels: bug

#2505 chore(deps): bump golang.org/x/net in modules (minio, gcloud, weaviate, compose, qdrant, couchbase, k3s, milvus, mockserver, pulsar, kafka)
  modules/compose/go.mod
  modules/compose/go.sum
  modules/couchbase/go.mod
  modules/couchbase/go.sum
  modules/gcloud/go.mod
  modules/gcloud/go.sum
  modules/k3s/go.mod
  modules/k3s/go.sum
  modules/kafka/go.mod
  modules/kafka/go.sum
  modules/milvus/go.mod
  modules/milvus/go.sum
  modules/minio/go.mod
  modules/minio/go.sum
  modules/mockserver/go.mod
  modules/mockserver/go.sum
  modules/pulsar/go.mod
  modules/pulsar/go.sum
  modules/qdrant/go.mod
  modules/qdrant/go.sum
  modules/weaviate/go.mod
  modules/weaviate/go.sum
Labels: dependencies

#2485 feat: support Ryuk for the compose module
  .github/workflows/ci-test-go.yml
  docker.go
  modules/compose/compose.go
  modules/compose/compose_api.go
  modules/compose/compose_api_test.go
  modules/compose/compose_builder_test.go
  modules/compose/compose_test.go
  modules/compose/testdata/docker-compose-build.yml
  modules/compose/testdata/docker-compose-complex.yml
  modules/compose/testdata/docker-compose-container-name.yml
  modules/compose/testdata/docker-compose-no-exposed-ports.yml
  modules/compose/testdata/docker-compose-override.yml
  modules/compose/testdata/docker-compose-postgres.yml
  modules/compose/testdata/docker-compose-simple.yml
  modules/compose/testdata/docker-compose-volume.yml
  reaper.go
Labels: enhancement

#2510 chore: add funding button for testcontainers
  .github/FUNDING.yml
Labels: chore

#2509 feat: support passing io.Reader for compose files when creating a compose instance
  docs/features/docker_compose.md
  modules/compose/compose.go
  modules/compose/compose_api.go
  modules/compose/compose_api_test.go
Labels: feature, compose

#2511 feat: support overriding the default recreate options for compose
  docs/features/docker_compose.md
  modules/compose/compose.go
  modules/compose/compose_api.go
  modules/compose/compose_api_test.go
Labels: feature, compose

#2506 fix: don't retry on permanent APIClient errors
  docker.go
  docker_test.go
Labels: bug

#2513 [doc] Fix follow_logs.md by adding missing package
  docs/features/follow_logs.md
Labels: documentation

#2514 docs: document the SSHd tunnel
  docs/features/common_functional_options.md
  docs/features/networking.md
  options.go
  options_test.go
  port_forwarding.go
  port_forwarding_test.go
Labels: documentation

#2451 docs: add documentation for Exec method
  docker.go
  exec/processor.go
Labels: documentation

#2515 fix: use new UUID for sshd server password
  port_forwarding.go
Labels: chore

#2519 chore(deps): bump github.com/compose-spec/compose-go/v2 from v2.0.0-rc8 to v2.1.0
  modules/compose/go.mod
  modules/compose/go.sum
  modules/dolt/go.mod
  modules/dolt/go.sum
Labels: dependencies, compose
