Repository testcontainers/testcontainers-go, pull requests merged in 2024-11, with the labels that each got.

#2653 feat: add build to life cycle hooks
  container.go
  docker.go
  docs/features/creating_container.md
  lifecycle.go
  lifecycle_test.go
Labels: enhancement

#2867 fix: host access port instability
  docker.go
  exec/processor.go
  port_forwarding.go
  port_forwarding_test.go
Labels: bug

#2875 docs: fix new lifecycle hooks section
  docs/features/creating_container.md
Labels: documentation

#2879 chore: resolve AWS deprecations for localstack
  docs/modules/localstack.md
  modules/localstack/go.mod
  modules/localstack/go.sum
  modules/localstack/v2/s3_test.go
Labels: chore

#2889 fix: do not run sonar upload when ryuk is disabled
  .github/workflows/ci-test-go.yml
Labels: chore

#2890 fix: build artifact name properly
  .github/workflows/ci-test-go.yml
Labels: chore

#2891 fix: only upload to sonar on ubuntu-latest
  .github/workflows/ci-test-go.yml
Labels: chore

#2845 fix(influxdb): Respect custom waitStrategy
  modules/influxdb/influxdb.go
Labels: bug

#2893 docs: better contribution guidelines
  Makefile
  docs/contributing.md
  docs/contributing_docs.md
  mkdocs.yml
  modulegen/internal/mkdocs/types.go
Labels: documentation

#2895 feat(wait): strategy walk
  docs/features/wait/introduction.md
  docs/features/wait/walk.md
  mkdocs.yml
  wait/walk.go
  wait/walk_test.go
Labels: enhancement
