Repository testcontainers/testcontainers-go, pull requests merged in 2024-09, with the labels that each got.

#2763 fix: update checkout action in template
  modulegen/_template/ci.yml.tmpl
Labels: dependencies

#2758 feat(compose): select services via profiles
  modules/compose/compose.go
  modules/compose/compose_api.go
  modules/compose/compose_api_test.go
  modules/compose/compose_builder_test.go
  modules/compose/testdata/docker-compose-profiles.yml
Labels: feature, compose

#2731 feat(wait): for file
  .mockery.yaml
  docs/features/wait/file.md
  docs/features/wait/introduction.md
  generic.go
  go.mod
  go.sum
  mkdocs.yml
  wait/exec_test.go
  wait/exit_test.go
  wait/file.go
  wait/file_test.go
  wait/health_test.go
  wait/nop.go
  wait/strategytarget_mock_test.go
  wait/wait.go
  wait/wait_test.go
Labels: feature

#2770 docs: refine heading badges in README
  README.md
Labels: documentation

#2772 fix: docker config error handling when config file does not exist
  docker_auth.go
  docker_auth_test.go
  testdata/invalid-config/.docker/config.json
Labels: bug

#2774 ci: add generate for mocks
  .github/workflows/ci-test-go.yml
  commons-test.mk
  examples/nginx/go.sum
  examples/toxiproxy/go.sum
  generate.go
  modules/artemis/go.sum
  modules/azurite/go.sum
  modules/cassandra/go.sum
  modules/chroma/go.sum
  modules/clickhouse/go.sum
  modules/cockroachdb/go.sum
  modules/compose/go.sum
  modules/couchbase/go.mod
  modules/couchbase/go.sum
  modules/dolt/go.sum
  modules/elasticsearch/go.sum
  modules/gcloud/go.sum
  modules/grafana-lgtm/go.sum
  modules/inbucket/go.sum
  modules/influxdb/go.sum
  modules/k3s/go.sum
  modules/k6/go.sum
  modules/kafka/go.sum
  modules/localstack/go.sum
  modules/mariadb/go.sum
  modules/minio/go.sum
  modules/mockserver/go.sum
  modules/mongodb/go.sum
  modules/mssql/go.sum
  modules/mysql/go.sum
  modules/nats/go.sum
  modules/neo4j/go.sum
  modules/ollama/go.sum
  modules/openfga/go.sum
  modules/openldap/go.sum
  modules/opensearch/go.sum
  modules/postgres/go.sum
  modules/qdrant/go.sum
  modules/rabbitmq/go.sum
  modules/redis/go.sum
  modules/redpanda/go.sum
  modules/registry/go.sum
  modules/surrealdb/go.sum
  modules/valkey/go.sum
  modules/vault/go.sum
  modules/vearch/go.sum
  modules/weaviate/go.sum
Labels: chore

#2783 fix(postgres): Apply default snapshot name if no name specified
  modules/postgres/options.go
  modules/postgres/postgres.go
  modules/postgres/postgres_test.go
Labels: bug

#2777 feat(mongodb): Wait for mongodb module with a replicaset to finish
  modules/mongodb/mongodb.go
  modules/mongodb/mongodb_test.go
Labels: feature

#2775 fix: do not override ImageBuildOptions.Labels when building from a Dockerfile
  container.go
  container_test.go
  internal/core/labels.go
  internal/core/labels_test.go
Labels: bug

#2786 fix(mssql): bump Docker image version
  modules/mssql/examples_test.go
  modules/mssql/mssql.go
  modules/mssql/mssql_test.go
Labels: dependencies

#2787 chore: golangci-lint 1.61.0
  .github/workflows/ci-test-go.yml
  commons-test.mk
  container.go
  internal/config/config_test.go
  modules/consul/consul_test.go
Labels: chore

#2779 feat: support databend module
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/databend.md
  mkdocs.yml
  modules/databend/Makefile
  modules/databend/databend.go
  modules/databend/databend_test.go
  modules/databend/examples_test.go
  modules/databend/go.mod
  modules/databend/go.sum
  sonar-project.properties
Labels: enhancement

#2792 fix: container timeout test
  docker_test.go
Labels: chore

#2793 fix(registry): wait for
  docker_auth_test.go
  modules/registry/registry.go
Labels: bug

#2790 fix: parallel containers clean race
  parallel.go
  parallel_test.go
Labels: bug

#2795 chore: use a much smaller image for testing
  wait/exec_test.go
Labels: dependencies

#2791 fix: container logging deadlocks
  docker.go
  docker_test.go
  lifecycle.go
  logconsumer_test.go
Labels: bug

#2797 fix(grafana): update module path
  modules/grafana-lgtm/examples_test.go
  modules/grafana-lgtm/go.mod
  modules/grafana-lgtm/grafana_test.go
Labels: bug

#2724 fix(elasticsearch): wait for
  modules/elasticsearch/elasticsearch.go
  modules/elasticsearch/options.go
Labels: bug

#2794 fix(redpanda): wait for
  modules/redpanda/redpanda.go
Labels: bug

#2799 feat: add dynamodb-local module
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/dynamodb.md
  mkdocs.yml
  modules/dynamodb/Makefile
  modules/dynamodb/dynamodb.go
  modules/dynamodb/dynamodb_test.go
  modules/dynamodb/examples_test.go
  modules/dynamodb/go.mod
  modules/dynamodb/go.sum
  sonar-project.properties
Labels: enhancement

#2788 feat: add etcd module
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/etcd.md
  mkdocs.yml
  modules/etcd/Makefile
  modules/etcd/cmd_test.go
  modules/etcd/etcd.go
  modules/etcd/etcd_test.go
  modules/etcd/etcd_unit_test.go
  modules/etcd/examples_test.go
  modules/etcd/go.mod
  modules/etcd/go.sum
  modules/etcd/options.go
  sonar-project.properties
Labels: feature
