Repository testcontainers/testcontainers-go, pull requests merged in 2024-02, with the labels that each got.

#2178 chore(docker_mounts): stop doing misleading logging
  docker_mounts.go
Labels: chore

#2190 fix: deprecate BindMounts correctly
  docker_mounts.go
Labels: bug

#2048 [redpanda] sasl test for wrong mechanism
  modules/redpanda/redpanda_test.go
Labels: chore

#2191 fix: all mounts should contain the testcontainers labels
  docker_mounts.go
  mounts_test.go
Labels: bug

#2140 redpanda: allow using SASL and TLS together
  modules/redpanda/admin_api.go
  modules/redpanda/redpanda.go
  modules/redpanda/redpanda_test.go
Labels: feature

#1995 feat(modules.clickhouse): Add zookeeper for clickhouse clusterization
  docs/features/docker_compose.md
  docs/modules/clickhouse.md
  modules/clickhouse/clickhouse.go
  modules/clickhouse/clickhouse_test.go
  modules/clickhouse/mounts/zk_config.xml.tpl
Labels: feature

#2170 Add Support for WASM Transforms to Redpanda Module
  modules/redpanda/examples_test.go
  modules/redpanda/go.mod
  modules/redpanda/go.sum
  modules/redpanda/mounts/bootstrap.yaml.tpl
  modules/redpanda/options.go
  modules/redpanda/redpanda.go
  modules/redpanda/redpanda_test.go
Labels: feature

#2195 fix: go doc reference broken image
  README.md
Labels: documentation

#2197 chore(deps): bump cloud.google.com/go/spanner from 1.55.0 to 1.56.0 in /modules/gcloud, cloud.google.com/go/pubsub from 1.35.0 to 1.36.1 in /modules/gcloud, cloud.google.com/go/bigquery from 1.57.1 to 1.58.0 in /modules/gcloud
  modules/gcloud/go.mod
  modules/gcloud/go.sum
Labels: dependencies

#2200 redpanda/test: add admin client call
  modules/redpanda/redpanda_test.go
Labels: chore

#2201 fix: apply volume options only to volumes
  docker_mounts.go
  mounts_test.go
Labels: bug

#2199 feat (postgres): support for creating and restoring Snapshots
  docker_files_test.go
  docs/features/common_functional_options.md
  docs/features/files_and_mounts.md
  docs/features/override_container_command.md
  docs/features/wait/http.md
  docs/modules/postgres.md
  modules/postgres/go.mod
  modules/postgres/go.sum
  modules/postgres/postgres.go
  modules/postgres/postgres_test.go
  network/network_test.go
  testdata/waitForHello.sh
Labels: feature

#2210 chore(ci): do not fail fast main tests in different Go versions
  .github/workflows/ci.yml
  modulegen/_template/ci.yml.tmpl
Labels: chore

#2211 fix: wait more time in test
  docker_files_test.go
Labels: chore

#2194 Added Consul module
  .github/dependabot.yml
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  RELEASING.md
  docs/examples/consul.md
  docs/modules/consul.md
  examples/consul/consul.go
  examples/consul/consul_test.go
  mkdocs.yml
  modules/consul/Makefile
  modules/consul/consul.go
  modules/consul/consul_test.go
  modules/consul/examples_test.go
  modules/consul/go.mod
  modules/consul/go.sum
  modules/consul/testdata/config.json
  sonar-project.properties
Labels: feature

#1922 chore: define proper execution order for container lifecycle hooks
  docker.go
  docs/features/common_functional_options.md
  docs/features/creating_container.md
  lifecycle.go
  lifecycle_test.go
  modules/cassandra/cassandra.go
  modules/elasticsearch/elasticsearch.go
  modules/openldap/openldap.go
  modules/rabbitmq/examples_test.go
  modules/rabbitmq/rabbitmq_test.go
  options.go
  options_test.go
Labels: chore

#2237 chore(deps): bump golang.org/x/mod from 0.14.0 to 0.15.0 in /modules/kafka, golang.org/x/mod from 0.14.0 to 0.15.0 in /modulegen
  modulegen/go.mod
  modulegen/go.sum
  modules/kafka/go.mod
  modules/kafka/go.sum
Labels: dependencies

#2238 chore(deps): bump cloud.google.com/go/spanner from 1.56.0 to 1.57.0 in /modules/gcloud, cloud.google.com/go/bigquery from 1.58.0 to 1.59.1 in /modules/gcloud, google.golang.org/api from 0.160.0 to 0.165.0 in /modules/gcloud
  modules/gcloud/go.mod
  modules/gcloud/go.sum
Labels: dependencies

#2239 docs: improve module creation section
  docs/modules/index.md
Labels: documentation

#2236 chore(deps): bump k8s.io/client-go from 0.29.1 to 0.29.2 in /modules/k3s, k8s.io/apimachinery from 0.29.1 to 0.29.2 in /modules/k3s, k8s.io/api from 0.29.1 to 0.29.2 in /modules/k3s
  modules/k3s/go.mod
  modules/k3s/go.sum
Labels: dependencies

#2241 chore: enforce test package in modules
  modulegen/_template/examples_test.go.tmpl
  modulegen/_template/module_test.go.tmpl
  modulegen/main_test.go
  modules/cassandra/cassandra_test.go
  modules/clickhouse/clickhouse.go
  modules/clickhouse/clickhouse_test.go
  modules/k6/k6_test.go
  modules/kafka/consumer_test.go
  modules/kafka/kafka_helpers_test.go
  modules/kafka/kafka_test.go
  modules/mariadb/mariadb_test.go
  modules/minio/minio_test.go
  modules/mockserver/coverage.out
  modules/mssql/mssql_test.go
  modules/nats/nats_test.go
  modules/openldap/openldap_test.go
  modules/redis/options_test.go
  modules/redis/redis_test.go
  modules/redpanda/redpanda_helpers_test.go
  modules/redpanda/redpanda_test.go
Labels: chore

#2243 Fix modulege template to succeed on make lint command
  modulegen/_template/examples_test.go.tmpl
Labels: chore

#2245 feat: add vector database modules (Qdrant, Weaviate, Chroma, pgvector, OpenSearch, Milvus)
  .github/dependabot.yml
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/chroma.md
  docs/modules/milvus.md
  docs/modules/opensearch.md
  docs/modules/postgres.md
  docs/modules/qdrant.md
  docs/modules/weaviate.md
  mkdocs.yml
  modulegen/_template/examples_test.go.tmpl
  modules/chroma/Makefile
  modules/chroma/chroma.go
  modules/chroma/chroma_test.go
  modules/chroma/examples_test.go
  modules/chroma/go.mod
  modules/chroma/go.sum
  modules/milvus/Makefile
  modules/milvus/examples_test.go
  modules/milvus/go.mod
  modules/milvus/go.sum
  modules/milvus/milvus.go
  modules/milvus/milvus_test.go
  modules/milvus/mounts/embedEtcd.yaml.tpl
  modules/opensearch/Makefile
  modules/opensearch/examples_test.go
  modules/opensearch/go.mod
  modules/opensearch/go.sum
  modules/opensearch/opensearch.go
  modules/opensearch/opensearch_test.go
  modules/opensearch/options.go
  modules/postgres/postgres_test.go
  modules/qdrant/Makefile
  modules/qdrant/examples_test.go
  modules/qdrant/go.mod
  modules/qdrant/go.sum
  modules/qdrant/qdrant.go
  modules/qdrant/qdrant_test.go
  modules/weaviate/Makefile
  modules/weaviate/examples_test.go
  modules/weaviate/go.mod
  modules/weaviate/go.sum
  modules/weaviate/weaviate.go
  modules/weaviate/weaviate_test.go
  sonar-project.properties
Labels: feature

#2258 chore(milvus): embed etcd should use default ports
  modules/milvus/milvus.go
Labels: chore

#2260 feat: WithEnv customize request option
  docs/features/common_functional_options.md
  options.go
  options_test.go
Labels: enhancement

#2247 bug: allow start container with reuse in different test package
  docker.go
  generic_test.go
  reaper.go
Labels: bug

#2262 docs: fix comment corruption
  internal/config/config.go
  logconsumer.go
  modules/couchbase/couchbase.go
  modules/couchbase/storage_mode.go
  modules/neo4j/config.go
  options.go
  testing.go
Labels: documentation

#2272 Fix Dockerfile not located when added to dockerignore
  container.go
  container_test.go
  testdata/.dockerignore
Labels: bug
