Repository testcontainers/testcontainers-go, pull requests merged in 2024-05, with the labels that each got.

#2528 fix(compose): avoid race conditions when caching services
  modules/compose/compose_api.go
Labels: bug

#2532 fix(influxdb): include more characters in wait for log regex
  modules/influxdb/influxdb.go
  modules/influxdb/influxdb_test.go
Labels: chore

#2531 Update devcontainer image
  .devcontainer/devcontainer.json
Labels: dependencies

#2535 chore(deps): bump test-summary action to v2.3
  .github/workflows/ci-test-go.yml
Labels: dependencies

#2534 feat: expose JSON representation of a container with Inspect
  container.go
  docker.go
  docker_test.go
  modules/localstack/localstack_test.go
  wait/exec_test.go
  wait/exit_test.go
  wait/health_test.go
  wait/host_port.go
  wait/host_port_test.go
  wait/http.go
  wait/http_test.go
  wait/nop.go
  wait/wait.go
  wait/wait_test.go
Labels: feature

#1989 fix(modules.kafka): Use broker container IP instead of host IP for advertised broker listener
  modules/kafka/kafka.go
  modules/kafka/kafka_test.go
Labels: bug

#2469 feat(modules.mongodb): add replica set support via opts
  docs/modules/mongodb.md
  modules/mongodb/mongodb.go
  modules/mongodb/mongodb_test.go
Labels: feature

#2537 fix: add import to module generation
  modulegen/_template/module.go.tmpl
  modulegen/main_test.go
Labels: bug

#2539 docs: fix CircleCI docs
  docs/system_requirements/ci/circle_ci.md
Labels: documentation

#2541 feat(ryuk): allow to configure ryuk timeouts using env variables
  docs/features/configuration.md
  internal/config/config.go
  internal/config/config_test.go
Labels: feature

#2544 docs: document test session semantics
  docs/features/test_session_semantics.md
  mkdocs.yml
Labels: documentation

#2545 chore: use a virtualenv for working with the docs site
  .gitignore
  Makefile
  docs/contributing_docs.md
Labels: chore

#2546 docs: improve contributing docs for code snippets
  docs/contributing_docs.md
Labels: documentation

#2547 fix: update search bar eval in mkdocs
  docs/theme/partials/header.html
Labels: documentation
