Repository testcontainers/testcontainers-go, pull requests merged in 2024-06, with the labels that each got.

#2566 chore: run tests against latest Docker engine, nightly
  .github/workflows/docker-moby-latest.yml
Labels: dependencies

#2560 feat: add vearch module
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/vearch.md
  mkdocs.yml
  modules/vearch/Makefile
  modules/vearch/config.toml
  modules/vearch/examples_test.go
  modules/vearch/go.mod
  modules/vearch/go.sum
  modules/vearch/vearch.go
  modules/vearch/vearch_test.go
Labels: feature

#2568 chore: pin vearch version
  docs/modules/vearch.md
  modules/vearch/examples_test.go
  modules/vearch/vearch.go
  modules/vearch/vearch_test.go
Labels: dependencies

#2550 Handle error properly during port forwarding initialization.
  port_forwarding.go
Labels: bug

#2565 docs(compose): Fix typo docker compose docs
  docs/features/docker_compose.md
Labels: documentation

#2571 chore: bring golangci-lint back
  .github/workflows/ci-test-go.yml
  docker_test.go
  internal/config/config_test.go
  modulegen/main_test.go
  modules/compose/compose_api.go
  modules/compose/compose_api_test.go
  modules/dolt/dolt.go
  modules/elasticsearch/elasticsearch_test.go
  modules/influxdb/influxdb.go
  modules/influxdb/influxdb_test.go
  modules/k3s/k3s_test.go
  modules/k6/k6.go
  modules/mariadb/mariadb.go
  modules/mariadb/mariadb_test.go
  modules/mysql/mysql.go
  modules/mysql/mysql_test.go
  modules/nats/nats.go
  modules/nats/nats_test.go
  modules/ollama/examples_test.go
  modules/rabbitmq/examples_test.go
  modules/registry/registry.go
  modules/weaviate/weaviate_test.go
  port_forwarding.go
Labels: chore

#2456 fix(cockroachdb): Fixes cockroachdb wait strategy handling
  modules/cockroachdb/cockroachdb.go
  modules/cockroachdb/cockroachdb_test.go
Labels: bug

#2578 docs: update colima docs
  docs/system_requirements/using_colima.md
Labels: documentation

#2577 fix: prepend substitutors for built images
  container.go
  docker.go
  image_substitutors_test.go
Labels: bug

#2582 chore: skip reaper tests if ryuk is disabled
  reaper_test.go
Labels: chore

#2538 feat(mongodb): Make the replica set name configurable
  modules/mongodb/mongodb.go
  modules/mongodb/mongodb_test.go
Labels: enhancement

#2586 docs: update contributing guide
  .github/workflows/ci-test-go.yml
  Makefile
  commons-test.mk
  docs/contributing.md
  examples/Makefile
  modules/Makefile
Labels: documentation

#2576 fix: proper synchronisation for start/stop log production
  docker.go
  logconsumer_test.go
Labels: bug

#2589 network: WithCheckDuplicate: don't set CheckDuplicate value
  network/network.go
Labels: chore

#2588 gha: update golangci-lint to v1.59.1
  .github/workflows/ci-test-go.yml
  commons-test.mk
  docker_test.go
Labels: dependencies

#2592 docs: fix deprecation warning for material extensions emoji
  mkdocs.yml
Labels: documentation, dependencies

#2591 docs: example for NATS cluster
  docs/modules/nats.md
  modules/nats/examples_test.go
Labels: documentation

#2598 fix: allow compose files and readers to be used together
  modules/compose/compose_api.go
  modules/compose/compose_api_test.go
Labels: compose, bug

#2603 docs: document disabling ryuk with properties
  docs/features/configuration.md
Labels: documentation

#2597 chore(tests): rename test variables to kill sshd container more consistently
  port_forwarding_test.go
Labels: chore

#2604 Add support for Weaviate v1.25
  modules/weaviate/examples_test.go
  modules/weaviate/weaviate.go
  modules/weaviate/weaviate_test.go
Labels: dependencies

#2569 feat: add azurite module
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/azurite.md
  mkdocs.yml
  modules/azurite/Makefile
  modules/azurite/azurite.go
  modules/azurite/azurite_test.go
  modules/azurite/examples_test.go
  modules/azurite/go.mod
  modules/azurite/go.sum
  modules/azurite/options.go
  modules/azurite/services.go
  modules/gcloud/bigquery.go
  sonar-project.properties
Labels: feature

#2601 chore: improve log handling when container is stopping
  docker.go
Labels: chore

#2612 chore(ci): pass docker install type to the nightly build payload
  .github/workflows/docker-moby-latest.yml
Labels: chore, github_actions

#2608 chore: test cleanups
  docker.go
  options_test.go
Labels: chore

#2536 fix: Rename TC_HOST environment variable to TESTCONTAINERS_HOST_OVERRIDE
  docker.go
  docs/features/networking.md
  docs/system_requirements/using_podman.md
Labels: bug
