Repository testcontainers/testcontainers-go, pull requests merged in 2024-10, with the labels that each got.

#2812 feat: add require for critical checks
  container_test.go
  docker_test.go
  internal/core/docker_host_test.go
  internal/core/docker_rootless_test.go
  internal/core/images_test.go
  lifecycle_test.go
  modulegen/main_test.go
  modulegen/mkdocs_test.go
  modules/compose/compose_api_test.go
  modules/localstack/v1/s3_test.go
  modules/localstack/v2/s3_test.go
Labels: chore, hacktoberfest

#2818 chore: bump ryuk to latest release
  internal/config/config.go
Labels: dependencies

#2827 chore: replace 'assert' with 'require'
  container_ignore_test.go
  internal/config/config_test.go
  internal/core/docker_host_test.go
  modulegen/main_test.go
  modulegen/mkdocs_test.go
  modules/artemis/artemis_test.go
  modules/compose/compose_api_test.go
  modules/redpanda/redpanda_test.go
Labels: chore, hacktoberfest

#2831 fix: update module container struct name and missing imports
  modulegen/_template/examples_test.go.tmpl
  modulegen/_template/module.go.tmpl
  modulegen/_template/module.md.tmpl
  modulegen/_template/module_test.go.tmpl
  modulegen/internal/context/types.go
  modulegen/main_test.go
Labels: bug

#2825 feat: add yugabytedb module
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/yugabytedb.md
  mkdocs.yml
  modules/yugabytedb/Makefile
  modules/yugabytedb/examples_test.go
  modules/yugabytedb/go.mod
  modules/yugabytedb/go.sum
  modules/yugabytedb/options.go
  modules/yugabytedb/yugabytedb.go
  modules/yugabytedb/yugabytedb_test.go
  sonar-project.properties
Labels: enhancement

#2833 chore: update ryuk to 0.10.2
  internal/config/config.go
Labels: chore, dependencies

#2728 fix(reaper): refactor to allow retries and fix races
  container.go
  docker.go
  docker_mounts.go
  generic.go
  internal/core/labels.go
  lifecycle.go
  modules/compose/compose.go
  modules/compose/compose_api.go
  modules/compose/compose_api_test.go
  reaper.go
  reaper_test.go
  testing.go
Labels: bug

#2834 golangci-lint: enable thelper linter
  .golangci.yml
  docker_auth_test.go
  docker_test.go
  generic_test.go
  internal/config/config_test.go
  internal/core/docker_host_test.go
  internal/core/docker_rootless_test.go
  modulegen/context_test.go
  modulegen/main_test.go
  modulegen/mkdocs_test.go
  modules/artemis/artemis_test.go
  modules/clickhouse/clickhouse_test.go
  modules/compose/compose_builder_test.go
  modules/compose/compose_test.go
  modules/couchbase/couchbase_test.go
  modules/dolt/dolt_test.go
  modules/kafka/consumer_test.go
  modules/kafka/kafka_test.go
  modules/mariadb/mariadb_test.go
  modules/neo4j/neo4j_test.go
  modules/ollama/ollama_test.go
  modules/redis/redis_test.go
  modules/valkey/valkey_test.go
  port_forwarding_test.go
  reaper_test.go
  testing.go
Labels: chore

#2835 feat: add meilisearch-module
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/meilisearch.md
  mkdocs.yml
  modules/meilisearch/Makefile
  modules/meilisearch/examples_test.go
  modules/meilisearch/go.mod
  modules/meilisearch/go.sum
  modules/meilisearch/meilisearch.go
  modules/meilisearch/meilisearch_test.go
  modules/meilisearch/options.go
  modules/meilisearch/testdata/movies.dump
  sonar-project.properties
Labels: enhancement

#2842 fix(compose): race condition
  modules/compose/compose_api.go
Labels: compose, bug

#2851 chore: use require.(No)Error(t,err) instead of t.Fatal(err)
  container_file_test.go
  docker_files_test.go
  docker_test.go
  file_test.go
  from_dockerfile_test.go
  image_substitutors_test.go
  image_test.go
  lifecycle_test.go
  logconsumer_test.go
  modules/cassandra/cassandra_test.go
  modules/dolt/dolt_test.go
  modules/elasticsearch/elasticsearch_test.go
  modules/k6/k6_test.go
  modules/neo4j/neo4j_test.go
  modules/rabbitmq/rabbitmq_test.go
  modules/weaviate/weaviate_test.go
  wait/exec_test.go
  wait/exit_test.go
  wait/host_port_test.go
  wait/sql_test.go
Labels: chore, hacktoberfest

#2847 fix: mongodb replicaset should work with auth
  modules/mongodb/cli.go
  modules/mongodb/mongodb.go
  modules/mongodb/mongodb_test.go
  modules/mongodb/mount/entrypoint-tc.sh
Labels: bug

#2843 fix!: data races
  commons-test.mk
  docker.go
  docker_test.go
  network.go
  provider.go
  reaper.go
Labels: bug

#2844 fix(compose): container initialisation
  .golangci.yml
  container.go
  docker.go
  generic_test.go
  modules/compose/compose.go
  modules/compose/compose_api.go
  modules/compose/compose_api_test.go
  network.go
  reaper.go
Labels: compose, bug

#2850 chore: enable usestdlibvars linter
  .golangci.yml
  modules/elasticsearch/elasticsearch_test.go
  modules/ollama/examples_test.go
  modules/opensearch/opensearch_test.go
Labels: chore

#2853 chore: bump ryuk to 0.11.0
  docs/features/configuration.md
  internal/config/config.go
  internal/config/config_test.go
Labels: dependencies

#2854 chore: use require.Len instead of assert.Len
  lifecycle_test.go
  modulegen/main_test.go
  modulegen/mkdocs_test.go
  modules/compose/compose_api_test.go
  modules/compose/compose_test.go
  modules/localstack/v1/s3_test.go
  modules/localstack/v2/s3_test.go
  options_test.go
Labels: chore

#2855 chore: use require instead of t.Fatal
  container_test.go
  docker_test.go
  image_test.go
  logconsumer_test.go
  modules/influxdb/influxdb_test.go
  modules/kafka/kafka_helpers_test.go
  modules/kafka/kafka_test.go
  modules/mariadb/mariadb_test.go
  modules/neo4j/neo4j_test.go
  modules/pulsar/pulsar_test.go
  modules/rabbitmq/rabbitmq_test.go
  modules/redis/redis_test.go
  modules/valkey/valkey_test.go
  modules/weaviate/weaviate_test.go
  port_forwarding_test.go
  provider_test.go
  testing.go
  wait/exec_test.go
  wait/sql_test.go
Labels: chore, hacktoberfest

#2860 docs(mysql|neo4j): remove default image codeblock
  docs/modules/mysql.md
  docs/modules/neo4j.md
Labels: documentation

#2864 chore: remove unused lint directives
  docker.go
  modules/grafana-lgtm/examples_test.go
  port_forwarding.go
  reaper.go
Labels: chore

#2857 chore: use require instead of t.Fatal (part 2)
  lifecycle_test.go
  logconsumer_test.go
  modules/chroma/chroma_test.go
  modules/compose/compose_builder_test.go
  modules/compose/compose_test.go
  modules/couchbase/couchbase_test.go
  modules/elasticsearch/elasticsearch_test.go
  modules/influxdb/influxdb_test.go
  modules/neo4j/neo4j_test.go
  modules/rabbitmq/rabbitmq_test.go
  modules/weaviate/weaviate_test.go
Labels: chore

#2861 feat(ci): Test against the nightly master moby
  .github/workflows/docker-moby-latest.yml
Labels: chore

#2866 fix: docker auth for identity tokens
  docker_auth.go
  docker_auth_test.go
Labels: bug
