Repository testcontainers/testcontainers-go, pull requests merged in 2024-08, with the labels that each got.

#2660 feat: add grafana-lgtm module
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/grafana-lgtm.md
  mkdocs.yml
  modules/grafana-lgtm/Makefile
  modules/grafana-lgtm/examples_test.go
  modules/grafana-lgtm/go.mod
  modules/grafana-lgtm/go.sum
  modules/grafana-lgtm/grafana.go
  modules/grafana-lgtm/grafana_test.go
  sonar-project.properties
Labels: feature

#2658 fix: incorrect parsing of exposedPorts in readiness check
  lifecycle.go
  lifecycle_test.go
Labels: bug

#2681 chore: print Docker Info labels in banner
  docker_client.go
Labels: chore

#2689 test: fix image label test
  mounts_test.go
Labels: chore

#2651 fix: missing image build errors
  container_test.go
  docker.go
  from_dockerfile_test.go
  generic.go
  testdata/error.Dockerfile
Labels: bug

#2686 fix: port forwarding race condition
  port_forwarding.go
Labels: bug

#2688 test: racy port creation in port forwarding tests
  port_forwarding_test.go
Labels: chore

#2699 test(mongodb): fix replica test failures
  modules/mongodb/mongodb.go
  modules/mongodb/mongodb_test.go
Labels: chore

#2693 fix(milvus): racy container setup
  modules/milvus/go.mod
  modules/milvus/go.sum
  modules/milvus/milvus.go
  modules/milvus/milvus_test.go
Labels: bug

#2698 fix(wait): data race in test
  wait/health_test.go
Labels: chore

#2690 feat(inbucket): expose POP3 and wait for all ports
  modules/inbucket/go.mod
  modules/inbucket/go.sum
  modules/inbucket/inbucket.go
  modules/inbucket/inbucket_test.go
Labels: feature

#2666 feat(redpanda): Add option for arbitrary bootstrap config
  modules/redpanda/examples_test.go
  modules/redpanda/mounts/bootstrap.yaml.tpl
  modules/redpanda/options.go
  modules/redpanda/redpanda.go
  modules/redpanda/redpanda_test.go
Labels: enhancement

#2687 test: add retry on system error test
  docker_test.go
  testdata/retry/Dockerfile
Labels: chore

#2703 docs: add consistent snippets for network creation
  docs/features/creating_networks.md
  network/examples_test.go
  network/network_test.go
Labels: documentation

#2708 chore: improve lifecycle errors
  container_test.go
  docker.go
  lifecycle.go
  options_test.go
  wait/wait.go
Labels: chore

#2710 chore: remove obsolete compose version
  modules/compose/compose_api_test.go
  modules/compose/testdata/docker-compose-build.yml
  modules/compose/testdata/docker-compose-complex.yml
  modules/compose/testdata/docker-compose-container-name.yml
  modules/compose/testdata/docker-compose-no-exposed-ports.yml
  modules/compose/testdata/docker-compose-override.yml
  modules/compose/testdata/docker-compose-postgres.yml
  modules/compose/testdata/docker-compose-short-lifespan.yml
  modules/compose/testdata/docker-compose-simple.yml
  modules/compose/testdata/docker-compose-volume.yml
Labels: chore

#2711 chore(registry): disable build log
  modules/registry/registry_test.go
Labels: chore

#2713 docs: improve docs for container methods
  container.go
  docker.go
Labels: documentation

#2714 chore: remove unused params from defaultPreCreateHook
  docker.go
  lifecycle.go
Labels: chore

#2707 chore(mysql): add missing error check in example
  modules/mysql/examples_test.go
Labels: chore

#2712 fix(compose): remove test volumes
  modules/compose/compose_api.go
  modules/compose/compose_api_test.go
  modules/compose/compose_local.go
Labels: chore

#2715 fix: filter context errors from log production
  docker.go
Labels: chore

#2691 feat(wait): skip internal host port check
  docs/features/wait/host_port.md
  wait/host_port.go
Labels: feature

#2730 chore(mockserver): silence warning about internal port
  modules/mockserver/mockserver.go
Labels: chore

#2719 chore: increase timeout values
  logconsumer_test.go
  wait/log_test.go
Labels: chore

#2716 chore(wait): log test timeout
  wait/log_test.go
Labels: chore

#2722 fix(compose): container locking
  modules/compose/compose_api.go
Labels: bug

#2723 chore: fix nginx request failures in tests
  docker_test.go
Labels: chore

#2734 chore: run make tests in verbose mode
  commons-test.mk
Labels: chore

#2720 chore: improve error wrapping in some docker container methods and compose module
  docker.go
  generic.go
  modules/compose/compose.go
  modules/compose/compose_api.go
  modules/compose/compose_local.go
Labels: chore

#2727 fix!: docker authentication setup
  container.go
  container_test.go
  docker.go
  docker_auth.go
  docker_auth_test.go
  internal/core/images.go
Labels: breaking change

#2697 fix: logging restart
  lifecycle.go
  logconsumer_test.go
Labels: bug

#2692 fix(redpanda): race condition on port check
  modules/redpanda/redpanda.go
Labels: bug

#2725 fix: config via environment
  internal/config/config.go
  logger.go
Labels: bug

#2706 fix: authentication tests on WSL
  docker_auth_test.go
  testdata/auth.Dockerfile
  testhelpers_test.go
Labels: chore

#2743 chore(deps): bump minimal Go version from 1.21 to 1.22
  .devcontainer/devcontainer.json
  .github/workflows/ci.yml
  docs/system_requirements/ci/aws_codebuild.md
  docs/system_requirements/ci/concourse_ci.md
  docs/system_requirements/ci/dind_patterns.md
  docs/system_requirements/ci/gitlab_ci.md
  docs/system_requirements/ci/tekton.md
  docs/system_requirements/ci/travis.md
  examples/nginx/go.mod
  examples/toxiproxy/go.mod
  go.mod
  modulegen/_template/ci.yml.tmpl
  modulegen/go.mod
  modules/artemis/go.mod
  modules/azurite/go.mod
  modules/cassandra/go.mod
  modules/chroma/go.mod
  modules/clickhouse/go.mod
  modules/cockroachdb/go.mod
  modules/compose/go.mod
  modules/consul/go.mod
  modules/couchbase/go.mod
  modules/dolt/go.mod
  modules/elasticsearch/go.mod
  modules/gcloud/go.mod
  modules/grafana-lgtm/go.mod
  modules/inbucket/go.mod
  modules/influxdb/go.mod
  modules/k3s/go.mod
  modules/k6/go.mod
  modules/kafka/go.mod
  modules/localstack/go.mod
  modules/mariadb/go.mod
  modules/milvus/go.mod
  modules/minio/go.mod
  modules/mockserver/go.mod
  modules/mongodb/go.mod
  modules/mssql/go.mod
  modules/mysql/go.mod
  modules/nats/go.mod
  modules/neo4j/go.mod
  modules/ollama/go.mod
  modules/openfga/go.mod
  modules/openldap/go.mod
  modules/opensearch/go.mod
  modules/postgres/go.mod
  modules/pulsar/go.mod
  modules/qdrant/go.mod
  modules/rabbitmq/go.mod
  modules/redis/go.mod
  modules/redpanda/go.mod
  modules/registry/go.mod
  modules/surrealdb/go.mod
  modules/valkey/go.mod
  modules/vault/go.mod
  modules/weaviate/go.mod
  scripts/bump-go.sh
  wait/testdata/go.mod
Labels: dependencies

#2750 chore: use new testcontainers/ryuk:0.9.0 image
  internal/config/config.go
Labels: dependencies

#2747 Fix trailing slash on Image Prefix
  docker_test.go
  options.go
Labels: bug

#2753 Upgrade milvus-io/milvus-sdk-go to avoid checksum mismatch.
  modules/milvus/go.mod
  modules/milvus/go.sum
Labels: dependencies

#2741 fix: check if the discovered docker socket responds
  docker_client.go
  docs/features/configuration.md
  image_test.go
  internal/core/client.go
  internal/core/docker_host.go
  internal/core/docker_host_test.go
  internal/core/docker_rootless.go
  internal/core/docker_rootless_test.go
  modules/localstack/localstack.go
  provider.go
  provider_test.go
  reaper.go
  reaper_test.go
  testcontainers.go
Labels: bug
