Repository testcontainers/testcontainers-go, pull requests merged in 2024-03, with the labels that each got.

#2270 Move the file and mounts tests into a test package
  docker_files_test.go
  docker_mounts.go
  file_test.go
  mounts_test.go
  testhelpers_test.go
Labels: chore

#2259 feat: WithLogger ContainerCustomizer support
  docs/features/common_functional_options.md
  logger.go
  logger_test.go
Labels: enhancement

#2293 chore(deps): bump google.golang.org/grpc from 1.61.1 to 1.62.0 in /modules/gcloud, google.golang.org/api from 0.165.0 to 0.167.0 in /modules/gcloud, cloud.google.com/go/pubsub from 1.36.1 to 1.36.2 in /modules/gcloud
  modules/gcloud/go.mod
  modules/gcloud/go.sum
Labels: dependencies

#2295 chore(deps): bump github.com/stretchr/testify from 1.8.4 to 1.9.0
  examples/nginx/go.sum
  examples/toxiproxy/go.sum
  go.mod
  go.sum
  modules/artemis/go.mod
  modules/artemis/go.sum
  modules/cassandra/go.mod
  modules/cassandra/go.sum
  modules/chroma/go.sum
  modules/clickhouse/go.mod
  modules/clickhouse/go.sum
  modules/cockroachdb/go.mod
  modules/cockroachdb/go.sum
  modules/compose/go.mod
  modules/compose/go.sum
  modules/consul/go.mod
  modules/consul/go.sum
  modules/couchbase/go.sum
  modules/elasticsearch/go.mod
  modules/elasticsearch/go.sum
  modules/gcloud/go.sum
  modules/inbucket/go.sum
  modules/k3s/go.sum
  modules/k6/go.sum
  modules/kafka/go.sum
  modules/localstack/go.mod
  modules/localstack/go.sum
  modules/mariadb/go.sum
  modules/milvus/go.sum
  modules/minio/go.sum
  modules/mockserver/go.sum
  modules/mongodb/go.sum
  modules/mssql/go.sum
  modules/mysql/go.sum
  modules/nats/go.sum
  modules/neo4j/go.sum
  modules/openldap/go.sum
  modules/opensearch/go.sum
  modules/postgres/go.mod
  modules/postgres/go.sum
  modules/pulsar/go.mod
  modules/pulsar/go.sum
  modules/qdrant/go.sum
  modules/rabbitmq/go.sum
  modules/redis/go.mod
  modules/redis/go.sum
  modules/redpanda/go.mod
  modules/redpanda/go.sum
  modules/vault/go.mod
  modules/vault/go.sum
  modules/weaviate/go.sum
Labels: dependencies

#2297 chore(deps): bump github.com/couchbase/gocb/v2 from 2.7.1 to 2.7.2 in /modules/couchbase, github.com/tidwall/gjson from 1.17.0 to 1.17.1 in /modules/couchbase
  modules/couchbase/go.mod
  modules/couchbase/go.sum
Labels: dependencies

#2192 Adding surrealDB module
  .github/dependabot.yml
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/surrealdb.md
  mkdocs.yml
  modules/surrealdb/Makefile
  modules/surrealdb/examples_test.go
  modules/surrealdb/go.mod
  modules/surrealdb/go.sum
  modules/surrealdb/surrealdb.go
  modules/surrealdb/surrealdb_test.go
  sonar-project.properties
Labels: enhancement

#2265 feat: add ollama module
  .github/dependabot.yml
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/ollama.md
  mkdocs.yml
  modules/ollama/Makefile
  modules/ollama/examples_test.go
  modules/ollama/go.mod
  modules/ollama/go.sum
  modules/ollama/ollama.go
  modules/ollama/ollama_test.go
  modules/ollama/options.go
  sonar-project.properties
Labels: enhancement

#2323 chore(deps): bump github.com/jackc/pgx/v5 from 5.5.3 to 5.5.4 in /modules/postgres, github.com/jackc/pgx/v5 from 5.5.3 to 5.5.4 in /modules/cockroachdb
  modules/cockroachdb/go.mod
  modules/cockroachdb/go.sum
  modules/postgres/go.mod
  modules/postgres/go.sum
Labels: dependencies

#2321 chore(deps): bump github.com/hashicorp/vault-client-go from 0.3.3 to 0.4.3 in /modules/vault, github.com/tidwall/gjson from 1.17.0 to 1.17.1 in /modules/vault
  modules/vault/go.mod
  modules/vault/go.sum
Labels: dependencies

#2322 chore(deps): bump github.com/twmb/franz-go from 1.15.4 to 1.16.1 in /modules/redpanda, github.com/twmb/franz-go/pkg/kadm from 1.10.0 to 1.11.0 in /modules/redpanda
  modules/redpanda/go.mod
  modules/redpanda/go.sum
Labels: dependencies

#2320 chore(deps): bump github.com/aws/aws-sdk-go-v2/credentials from 1.16.14 to 1.17.5 in /modules/localstack, github.com/aws/aws-sdk-go-v2 from 1.24.1 to 1.25.2 in /modules/localstack
  modules/localstack/go.mod
  modules/localstack/go.sum
Labels: dependencies

#2326 chore: confirm support for new mongo images
  docs/modules/mongodb.md
  modules/mongodb/examples_test.go
  modules/mongodb/mongodb_test.go
Labels: chore

#2327 generic.go: GenericContainer(): clearer error message
  container_test.go
  generic.go
Labels: chore

#2331 chore: check that the new version is not empty
  scripts/release.sh
Labels: chore

#2325 chore: retire dependabot
  .github/dependabot.yml
  .github/workflows/ci.yml
  docs/modules/index.md
  modulegen/_template/ci.yml.tmpl
  modulegen/context_test.go
  modulegen/internal/context/context.go
  modulegen/internal/dependabot/main.go
  modulegen/internal/dependabot/reader.go
  modulegen/internal/dependabot/sorter.go
  modulegen/internal/dependabot/types.go
  modulegen/internal/dependabot/writer.go
  modulegen/internal/main.go
  modulegen/internal/make/main.go
  modulegen/main_test.go
Labels: dependencies

#2332 feat: add openfga module
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/openfga.md
  mkdocs.yml
  modules/openfga/Makefile
  modules/openfga/examples_test.go
  modules/openfga/go.mod
  modules/openfga/go.sum
  modules/openfga/openfga.go
  modules/openfga/openfga_test.go
  modules/openfga/testdata/authorization_model.json
  sonar-project.properties
Labels: feature

#2336 fix: consul race on HTTP port
  modules/consul/consul.go
Labels: bug

#2338 docs: fix wrong copy&paste
  docs/modules/weaviate.md
Labels: documentation

#2337 chore: use withEnv in localstack module
  docs/modules/localstack.md
  modules/localstack/examples_test.go
  modules/localstack/localstack_test.go
Labels: chore

#2339 Add method for getting Weaviate's gRPC port
  modules/weaviate/examples_test.go
  modules/weaviate/go.mod
  modules/weaviate/weaviate.go
  modules/weaviate/weaviate_test.go
Labels: enhancement

#2340 chore: updated compose-go version
  modules/compose/compose_api.go
  modules/compose/go.mod
  modules/compose/go.sum
Labels: dependencies

#2268 Added error handling for context.Canceled in log reading code
  docker.go
  logconsumer_test.go
Labels: bug

#2242 Move the container and config tests into a test package
  config_test.go
  container_ignore_test.go
  container_test.go
  testhelpers_test.go
Labels: chore

#2347 redpanda: set entrypoint to the custom entrypoint file
  modules/redpanda/redpanda.go
Labels: chore

#2349 feat: support for waiting for response headers
  docs/features/wait/http.md
  wait/http.go
  wait/http_test.go
  wait/testdata/main.go
Labels: enhancement

#2394 docs: Fix typo in ci-test-go.yml
  .github/workflows/ci-test-go.yml
Labels: chore

#2343 feat(MustConn): Add MustConnectionString on (some) dbs
  modules/mariadb/mariadb.go
  modules/mariadb/mariadb_test.go
  modules/mysql/mysql.go
  modules/mysql/mysql_test.go
  modules/nats/nats.go
  modules/nats/nats_test.go
  modules/postgres/postgres.go
  modules/postgres/postgres_test.go
Labels: enhancement

#2395 chore: bump ryuk to latest v0.7.0
  internal/config/config.go
Labels: dependencies

#2401 feat: support passing io.Reader as ContainerFile
  container.go
  container_file_test.go
  docker_files_test.go
  docs/features/files_and_mounts.md
  go.mod
  go.sum
  lifecycle.go
  modules/artemis/go.sum
  modules/cassandra/go.sum
  modules/consul/go.sum
  modules/pulsar/go.sum
  modules/weaviate/go.sum
  wait/http_test.go
Labels: feature

#2402 chore(deps): Bumping ChromaGo client version
  docs/modules/chroma.md
  modules/chroma/chroma.go
  modules/chroma/chroma_test.go
  modules/chroma/examples_test.go
  modules/chroma/go.mod
  modules/chroma/go.sum
Labels: dependencies

#2446 feat: authenticate docker on PullImage
  docker.go
  modules/k3s/k3s_test.go
Labels: enhancement

#1703 feat: add module to support InfluxDB v1.x
  .github/workflows/ci.yml
  .gitignore
  .vscode/.testcontainers-go.code-workspace
  docs/modules/influxdb.md
  mkdocs.yml
  modules/influxdb/Makefile
  modules/influxdb/examples_test.go
  modules/influxdb/go.mod
  modules/influxdb/go.sum
  modules/influxdb/influxdb.go
  modules/influxdb/influxdb_test.go
  modules/influxdb/testdata/docker-entrypoint-initdb.d/NOAA_data.txt.gz
  modules/influxdb/testdata/docker-entrypoint-initdb.d/test_v1_data.sh
  modules/influxdb/testdata/influxdb.conf
  sonar-project.properties
Labels: feature, hacktoberfest

#2342 feat(exitcode): Add exit code sugar method
  wait/exec.go
  wait/exec_test.go
Labels: feature

#2447 refactor: Add Weaviate modules tests
  docs/modules/weaviate.md
  modules/weaviate/examples_test.go
  modules/weaviate/go.mod
  modules/weaviate/go.sum
  modules/weaviate/weaviate.go
  modules/weaviate/weaviate_test.go
Labels: chore
