Repository testcontainers/testcontainers-go, pull requests merged in 2024-07, with the labels that each got.

#2606 fix: never cache JSON representation of a container
  docker.go
  docker_auth_test.go
  docker_test.go
  lifecycle.go
  port_forwarding.go
  testdata/auth.Dockerfile
Labels: bug

#2600 feat(postgres): use faster sql.DB instead of docker exec psql for snapshot/restore [rebased for main]
  docs/modules/postgres.md
  modules/postgres/go.mod
  modules/postgres/options.go
  modules/postgres/postgres.go
  modules/postgres/postgres_test.go
  modules/postgres/testdata/my-postgres.conf
  modules/postgres/wait_strategies.go
Labels: feature

#2619 chore: use self-hosted worker for Windows tests
  .github/workflows/ci-windows-trigger.yml
  .github/workflows/ci-windows.yml
Labels: chore

#2620 docs: document ryuk timeouts for compose
  docs/features/configuration.md
  docs/features/docker_compose.md
Labels: documentation

#2623 fix: do not use deprecated method in postgres tests
  modules/postgres/postgres_test.go
Labels: chore

#2628 chore: remove duplicated tests for config
  config_test.go
Labels: chore

#2627 docs: indicate version for the Run function
  docs/modules/artemis.md
  docs/modules/azurite.md
  docs/modules/cassandra.md
  docs/modules/chroma.md
  docs/modules/clickhouse.md
  docs/modules/cockroachdb.md
  docs/modules/consul.md
  docs/modules/couchbase.md
  docs/modules/dolt.md
  docs/modules/elasticsearch.md
  docs/modules/gcloud.md
  docs/modules/inbucket.md
  docs/modules/influxdb.md
  docs/modules/k3s.md
  docs/modules/k6.md
  docs/modules/kafka.md
  docs/modules/localstack.md
  docs/modules/mariadb.md
  docs/modules/milvus.md
  docs/modules/minio.md
  docs/modules/mockserver.md
  docs/modules/mongodb.md
  docs/modules/mssql.md
  docs/modules/mysql.md
  docs/modules/nats.md
  docs/modules/neo4j.md
  docs/modules/ollama.md
  docs/modules/openfga.md
  docs/modules/openldap.md
  docs/modules/opensearch.md
  docs/modules/postgres.md
  docs/modules/pulsar.md
  docs/modules/qdrant.md
  docs/modules/rabbitmq.md
  docs/modules/redis.md
  docs/modules/redpanda.md
  docs/modules/registry.md
  docs/modules/surrealdb.md
  docs/modules/vault.md
  docs/modules/vearch.md
  docs/modules/weaviate.md
  modulegen/_template/module.md.tmpl
  modulegen/main_test.go
Labels: documentation

#2626 Fix issues in BuildImage()
  container.go
  docker.go
Labels: chore

#2624 feat: honour go toolchain's verbose flag to print out logs
  Makefile
  docker_client.go
  generic_test.go
  internal/config/config.go
  logger.go
Labels: enhancement

#2643 fix: log output after context timeout
  lifecycle.go
Labels: bug

#2646 perf: optimise docker authentication config lookup
  docker_auth.go
Labels: chore

#2644 fix: retry on label error
  docker.go
Labels: bug

#2650 Fix: Couchbase containers intermittently hang on startup
  modules/couchbase/couchbase.go
  modules/couchbase/couchbase_test.go
Labels: bug

#2647 feat: add custom container registry substitutor
  image_substitutors_test.go
  options.go
Labels: feature

#2656 docs: fix compilation of examples
  docs/features/creating_container.md
  docs/quickstart.md
Labels: documentation

#2657 chore: test cleanups
  file_test.go
  modules/dolt/dolt_test.go
  modules/openldap/openldap_test.go
Labels: chore

#2641 fix: container.Endpoint and wait.FortHTTP to use lowest internal port
  container.go
  docker.go
  docs/features/wait/host_port.md
  docs/features/wait/http.md
  wait/host_port.go
  wait/http.go
Labels: bug
