Repository testcontainers/testcontainers-go, pull requests merged in 2024-01, with the labels that each got.

#2076 bump google.golang.org/api from 0.153.0 to 0.154.0, cloud.google.com/go/spanner from 1.53.1 to 1.54.0, bump google.golang.org/grpc from 1.59.0 to 1.60.1 in /modules/gcloud
  modules/gcloud/go.mod
  modules/gcloud/go.sum
Labels: dependencies

#2077 chore(deps): bump github.com/google/uuid from 1.4.0 to 1.5.0
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/consul/go.mod
  examples/consul/go.sum
  examples/nginx/go.mod
  examples/nginx/go.sum
  examples/toxiproxy/go.mod
  examples/toxiproxy/go.sum
  go.mod
  go.sum
  modules/artemis/go.mod
  modules/artemis/go.sum
  modules/cassandra/go.mod
  modules/cassandra/go.sum
  modules/clickhouse/go.mod
  modules/clickhouse/go.sum
  modules/compose/go.mod
  modules/compose/go.sum
  modules/couchbase/go.mod
  modules/couchbase/go.sum
  modules/elasticsearch/go.mod
  modules/elasticsearch/go.sum
  modules/gcloud/go.mod
  modules/gcloud/go.sum
  modules/k3s/go.mod
  modules/k3s/go.sum
  modules/k6/go.mod
  modules/k6/go.sum
  modules/kafka/go.mod
  modules/kafka/go.sum
  modules/localstack/go.mod
  modules/localstack/go.sum
  modules/mariadb/go.mod
  modules/mariadb/go.sum
  modules/mongodb/go.mod
  modules/mongodb/go.sum
  modules/mssql/go.mod
  modules/mssql/go.sum
  modules/mysql/go.mod
  modules/mysql/go.sum
  modules/nats/go.mod
  modules/nats/go.sum
  modules/neo4j/go.mod
  modules/neo4j/go.sum
  modules/postgres/go.mod
  modules/postgres/go.sum
  modules/pulsar/go.mod
  modules/pulsar/go.sum
  modules/rabbitmq/go.mod
  modules/rabbitmq/go.sum
  modules/redis/go.mod
  modules/redis/go.sum
  modules/redpanda/go.mod
  modules/redpanda/go.sum
  modules/vault/go.mod
  modules/vault/go.sum
Labels: dependencies

#2078 chore(deps): bump k8s.io/api, k8s.io/apimachinery, k8s.io/client-go from 0.28.4 to 0.29.0 in /modules/k3s
  modules/k3s/go.mod
  modules/k3s/go.sum
Labels: dependencies

#1972 fix(modules.gcloud): pass as ptr to allow request customization
  modules/gcloud/bigquery.go
  modules/gcloud/bigtable.go
  modules/gcloud/datastore.go
  modules/gcloud/firestore.go
  modules/gcloud/gcloud.go
  modules/gcloud/pubsub.go
  modules/gcloud/spanner.go
Labels: bug

#2080 chore: enrich HTTP headers to the Docker daemon with the project path
  docker.go
  docker_client.go
  generic.go
  internal/core/bootstrap.go
  internal/testcontainersdocker/client.go
  reaper_test.go
  testcontainer.go
Labels: chore

#1971 [breaking] Add err chan to log producer and don't panic on error
  container.go
  docker.go
  docs/features/follow_logs.md
  logconsumer_test.go
Labels: breaking change

#2082 GenericContainer: in case of error: return a reference to the failed container
  generic.go
  generic_test.go
Labels: enhancement

#2083 chore: move internal/testcontainersdocker package's files to internal/core
  container.go
  docker.go
  docker_auth.go
  docker_auth_test.go
  docker_client.go
  generic.go
  image_test.go
  internal/core/client.go
  internal/core/docker_host.go
  internal/core/docker_host_test.go
  internal/core/docker_rootless.go
  internal/core/docker_rootless_test.go
  internal/core/docker_socket.go
  internal/core/images.go
  internal/core/images_test.go
  internal/core/labels.go
  internal/core/testdata/Dockerfile
  internal/core/testdata/Dockerfile.multistage
  internal/core/testdata/Dockerfile.multistage.multiBuildArgs
  internal/core/testdata/Dockerfile.multistage.singleBuildArgs
  modules/localstack/localstack.go
  network/network_test.go
  options.go
  provider.go
  provider_test.go
  reaper.go
  reaper_test.go
  testcontainers.go
Labels: chore

#2049 feat: copy files to the container and create directories as needed upon request
  docker.go
  docker_test.go
  file.go
Labels: enhancement

#2051 fix(modules/rabbitmq): update container image to 3.12.11 to allow connections without passing admin credentials
  modules/rabbitmq/examples_test.go
  modules/rabbitmq/rabbitmq.go
  modules/rabbitmq/rabbitmq_test.go
Labels: bug

#2084 fix: Recreate Ryuk container if terminated
  reaper.go
  reaper_test.go
Labels: bug

#1994 feat: expose Redpanda's listener in the docker network
  docs/modules/redpanda.md
  modules/redpanda/mounts/redpanda.yaml.tpl
  modules/redpanda/options.go
  modules/redpanda/redpanda.go
  modules/redpanda/redpanda_test.go
Labels: enhancement

#2085 Adding mockserver module
  .github/dependabot.yml
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/mockserver.md
  mkdocs.yml
  modules/mockserver/Makefile
  modules/mockserver/coverage.out
  modules/mockserver/examples_test.go
  modules/mockserver/go.mod
  modules/mockserver/go.sum
  modules/mockserver/mockserver.go
  sonar-project.properties
Labels: feature

#2113 chore(deps): bump github.com/docker/go-connections from 0.4.0 to 0.5.0
  examples/cockroachdb/go.mod
  examples/cockroachdb/go.sum
  examples/consul/go.mod
  examples/consul/go.sum
  examples/nginx/go.mod
  examples/nginx/go.sum
  examples/toxiproxy/go.mod
  examples/toxiproxy/go.sum
  go.mod
  go.sum
  modules/artemis/go.mod
  modules/artemis/go.sum
  modules/cassandra/go.mod
  modules/cassandra/go.sum
  modules/clickhouse/go.mod
  modules/clickhouse/go.sum
  modules/couchbase/go.mod
  modules/couchbase/go.sum
  modules/elasticsearch/go.mod
  modules/elasticsearch/go.sum
  modules/gcloud/go.mod
  modules/gcloud/go.sum
  modules/k3s/go.mod
  modules/k3s/go.sum
  modules/k6/go.mod
  modules/k6/go.sum
  modules/kafka/go.mod
  modules/kafka/go.sum
  modules/localstack/go.mod
  modules/localstack/go.sum
  modules/mariadb/go.mod
  modules/mariadb/go.sum
  modules/mockserver/go.mod
  modules/mockserver/go.sum
  modules/mongodb/go.mod
  modules/mongodb/go.sum
  modules/mssql/go.mod
  modules/mssql/go.sum
  modules/mysql/go.mod
  modules/mysql/go.sum
  modules/nats/go.mod
  modules/nats/go.sum
  modules/neo4j/go.mod
  modules/neo4j/go.sum
  modules/postgres/go.mod
  modules/postgres/go.sum
  modules/pulsar/go.mod
  modules/pulsar/go.sum
  modules/rabbitmq/go.mod
  modules/rabbitmq/go.sum
  modules/redis/go.mod
  modules/redis/go.sum
  modules/redpanda/go.mod
  modules/redpanda/go.sum
  modules/vault/go.mod
  modules/vault/go.sum
Labels: dependencies

#2114 chore(deps): bump github.com/aws/aws-sdk-go-v2/config from 1.25.10 to 1.26.3, github.com/aws/aws-sdk-go from 1.48.13 to 1.49.19 in /modules/localstack
  modules/localstack/go.mod
  modules/localstack/go.sum
Labels: dependencies

#2115 chore(deps): bump cloud.google.com/go/spanner from 1.54.0 to 1.55.0, google.golang.org/api from 0.154.0 to 0.156.0 in /modules/gcloud
  modules/gcloud/go.mod
  modules/gcloud/go.sum
Labels: dependencies

#2120 lint: enable testifylint
  .github/workflows/ci-test-go.yml
  .golangci.yml
  docker_auth_test.go
  docker_test.go
  file_test.go
  from_dockerfile_test.go
  internal/core/docker_host_test.go
  internal/core/docker_rootless_test.go
  lifecycle_test.go
  logconsumer_test.go
  modulegen/context_test.go
  modulegen/main_test.go
  modulegen/mkdocs_test.go
  modules/cassandra/cassandra_test.go
  modules/clickhouse/clickhouse_test.go
  modules/localstack/localstack_test.go
  modules/localstack/v1/s3_test.go
  modules/localstack/v2/s3_test.go
  modules/postgres/postgres_test.go
  modules/redpanda/redpanda_test.go
  modules/vault/vault_test.go
  mounts_test.go
  network/network_test.go
  options_test.go
  reaper_test.go
  wait/health_test.go
Labels: chore

#2121 enable golangci-lint for pulsar
  .github/workflows/ci-test-go.yml
  modules/pulsar/pulsar_test.go
Labels: chore

#2122 chore: run make lint on new modules
  modulegen/internal/main.go
  modulegen/internal/tools/exec.go
Labels: chore

#2125 improve OSSF score
  .github/workflows/ci-windows-trigger.yml
  .github/workflows/ci-windows.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/release-drafter.yml
  modulegen/_template/ci.yml.tmpl
Labels: chore

#2127 Go install gotestsum and golangci-lint
  .github/workflows/ci-test-go.yml
  .github/workflows/ci-windows.yml
  commons-test.mk
Labels: chore

#2126 enable golangci-lint for redis module
  .github/workflows/ci-test-go.yml
  modules/redis/redis_test.go
Labels: chore

#2128 enable golangci-lint for examples
  .github/workflows/ci-test-go.yml
  examples/cockroachdb/cockroachdb_test.go
Labels: chore

#2129 pin Docker images version
  docs/features/build_from_dockerfile.md
  modules/redis/testdata/Dockerfile
  testdata/Dockerfile
  wait/testdata/Dockerfile
Labels: chore

#2135 chore: skip assertions for Docker Rootless
  .github/workflows/ci.yml
  docker_test.go
  from_dockerfile_test.go
  modulegen/_template/ci.yml.tmpl
  modulegen/main_test.go
Labels: chore

#2130 fix: skip-host-cache option removed in latest MySQL 8.3.0 version
  docker_test.go
  docs/features/image_name_substitution.md
  docs/features/wait/log.md
  docs/features/wait/multi.md
  docs/modules/mysql.md
  modules/compose/testdata/docker-compose-complex.yml
  modules/compose/testdata/docker-compose-override.yml
  modules/mariadb/testdata/my.cnf
  modules/mysql/examples_test.go
  modules/mysql/mysql.go
  modules/mysql/mysql_test.go
  modules/mysql/testdata/my_5.6.cnf
  modules/mysql/testdata/my_8.cnf
Labels: bug

#2132 feat: Add Minio module
  .github/dependabot.yml
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/minio.md
  mkdocs.yml
  modules/minio/Makefile
  modules/minio/examples_test.go
  modules/minio/go.mod
  modules/minio/go.sum
  modules/minio/minio.go
  modules/minio/minio_test.go
  sonar-project.properties
Labels: enhancement

#2143 testifylint: enable compares rule
  .golangci.yml
  docker_test.go
Labels: chore

#2142 Adding inbucket module
  .github/dependabot.yml
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/inbucket.md
  mkdocs.yml
  modules/inbucket/Makefile
  modules/inbucket/examples_test.go
  modules/inbucket/go.mod
  modules/inbucket/go.sum
  modules/inbucket/inbucket.go
  modules/inbucket/inbucket_test.go
  sonar-project.properties
Labels: enhancement

#2117 Openldap module support
  .github/dependabot.yml
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/openldap.md
  mkdocs.yml
  modules/openldap/Makefile
  modules/openldap/examples_test.go
  modules/openldap/go.mod
  modules/openldap/go.sum
  modules/openldap/openldap.go
  modules/openldap/openldap_test.go
  sonar-project.properties
Labels: enhancement

#2164 chore: do not compile modules on macos workers on GH
  .github/workflows/ci.yml
  modulegen/_template/ci.yml.tmpl
Labels: chore

#2167 chore(deps): bump k8s.io/api, k8s.io/apimachinery and k8s.io/client-go from 0.29.0 to 0.29.1 in /modules/k3s
  modules/k3s/go.mod
  modules/k3s/go.sum
Labels: dependencies

#2168 chore(deps): bump google.golang.org/api from 0.156.0 to 0.159.0, google.golang.org/grpc from 1.60.1 to 1.61.0, cloud.google.com/go/pubsub from 1.33.0 to 1.35.0 in /modules/gcloud
  modules/gcloud/go.mod
  modules/gcloud/go.sum
Labels: dependencies

#2131 feat(modules.cockroachdb) Adds cockroachdb module
  .github/dependabot.yml
  .github/workflows/ci.yml
  .vscode/.testcontainers-go.code-workspace
  RELEASING.md
  docs/examples/cockroachdb.md
  docs/modules/cockroachdb.md
  examples/cockroachdb/cockroachdb.go
  examples/cockroachdb/cockroachdb_test.go
  mkdocs.yml
  modules/cockroachdb/Makefile
  modules/cockroachdb/certs.go
  modules/cockroachdb/cockroachdb.go
  modules/cockroachdb/cockroachdb_test.go
  modules/cockroachdb/examples_test.go
  modules/cockroachdb/go.mod
  modules/cockroachdb/go.sum
  modules/cockroachdb/options.go
  sonar-project.properties
Labels: enhancement

#1775 fix: Add HTTPStrategy WithForcedIPv4LocalHost To Fix Docker Port Map
  wait/http.go
  wait/http_test.go
Labels: bug
