Repository testcontainers/testcontainers-go, pull requests merged in 2024-12, with the labels that each got.

#2883 refactor(cockroachdb): to use request driven options
  docs/features/tls.md
  docs/modules/cockroachdb.md
  modules/cockroachdb/certs.go
  modules/cockroachdb/cockroachdb.go
  modules/cockroachdb/cockroachdb_test.go
  modules/cockroachdb/data/cluster_defaults.sql
  modules/cockroachdb/examples_test.go
  modules/cockroachdb/go.mod
  modules/cockroachdb/go.sum
  modules/cockroachdb/options.go
  modules/cockroachdb/testdata/__init.sql
  modules/rabbitmq/examples_test.go
Labels: chore

#2877 chore: enable implicit default logger only in testing with -v
  logger.go
Labels: chore

#2905 feat(nats): WithConfigFile - pass a configuration file to nats server
  docs/modules/nats.md
  modules/nats/nats_test.go
  modules/nats/options.go
Labels: feature

#2911 chore(ci): enforce conventional commits syntax in PR titles
  .github/workflows/conventions.yml
  docs/contributing.md
Labels: chore

#2913 chore(gha): use official docker/setup-docker-action
  .github/workflows/ci-test-go.yml
  .github/workflows/docker-moby-latest.yml
Labels: chore

#2914 chore(ci): add Github labels based on PR title
  .github/release-drafter.yml
  .github/workflows/conventions.yml
  .github/workflows/release-drafter.yml
  docs/contributing.md
Labels: chore

#2523 feat(gcloud)!: add support to seed data when using RunBigQueryContainer
  docs/modules/gcloud.md
  modules/gcloud/bigquery.go
  modules/gcloud/bigquery_test.go
  modules/gcloud/gcloud.go
  modules/gcloud/go.mod
  modules/gcloud/testdata/data.yaml
Labels: feature, breaking change

#2900 fix: avoid double lock in DockerProvider.DaemonHost()
  docker.go
  docker_test.go
  internal/core/docker_host.go
Labels: bug

#2928 fix: handle nil value in CleanupNetwork
  network/network_test.go
  testing.go
Labels: bug

#2929 feat(wait): log sub match callback
  docs/features/wait/log.md
  wait/log.go
  wait/log_test.go
Labels: feature
