Repository testcontainers/testcontainers-go, pull requests merged in 2025-07, with the labels that each got.

#3228 chore: clarify image auth warning message for public images
  docker.go
Labels: chore

#3226 fix: strip headers from logs using log stream specification
  docker.go
  from_dockerfile_test.go
  logconsumer_test.go
Labels: bug

#3231 chore(deps): update go.mod in azure module
  modules/azure/go.mod
Labels: dependencies

#3232 feat(mcpgateay): add Docker's MCP gateway module
  .github/dependabot.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/dockermcpgateway.md
  mkdocs.yml
  modules/dockermcpgateway/Makefile
  modules/dockermcpgateway/dockermcpgateway.go
  modules/dockermcpgateway/dockermcpgateway_test.go
  modules/dockermcpgateway/examples_test.go
  modules/dockermcpgateway/go.mod
  modules/dockermcpgateway/go.sum
  modules/dockermcpgateway/options.go
  modules/dockermcpgateway/options_test.go
Labels: feature

#3230 feat: add Solace pubsub+ module
  .github/dependabot.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/solace.md
  mkdocs.yml
  modules/solace/Makefile
  modules/solace/examples_test.go
  modules/solace/go.mod
  modules/solace/go.sum
  modules/solace/mounts/solace.script.tpl
  modules/solace/options.go
  modules/solace/options_test.go
  modules/solace/service.go
  modules/solace/solace.go
  modules/solace/solace_test.go
Labels: enhancement

#3247 fix(dockermcpgateway): use duckduckgo instead of brave
  modules/dockermcpgateway/dockermcpgateway_test.go
  modules/dockermcpgateway/examples_test.go
Labels: chore
