Repository testcontainers/testcontainers-go, pull requests merged in 2025-09, with the labels that each got.

#3274 chore(deps): bump ryuk to v0.13.0, which uses scratch as base image
  internal/config/config.go
Labels: dependencies

#3275 feat(registry): add helper functions to pull and tag images
  docs/modules/registry.md
  modules/registry/examples_test.go
  modules/registry/registry.go
  modules/registry/registry_test.go
Labels: feature

#3279 docs: clarify no client SDKs in production modules/images, in contributing.md
  docs/contributing.md
  docs/modules/index.md
Labels: documentation

#3309 chore: use Run in more tests (part 4)
  container_test.go
  examples/nginx/nginx.go
  options_test.go
  options_unit_test.go
Labels: chore

#3317 chore: update relative-path-mode to "gitroot" in golangci configuration
  .golangci.yml
Labels: chore

#3319 chore(arangodb): use Run function
  modules/arangodb/arangodb.go
  modules/arangodb/options.go
Labels: chore

#3320 chore(artemis): use Run function
  modules/artemis/artemis.go
  modules/artemis/artemis_test.go
Labels: chore

#3308 fix: use path.Join instead of url.JoinPath when prepending a custom registry to an image
  image_substitutors_test.go
  options.go
Labels: bug

#3325 chore(clickhouse): use Run function
  modules/clickhouse/clickhouse.go
  modules/clickhouse/options.go
Labels: chore
