Repository testcontainers/testcontainers-go, pull requests merged in 2025-03, with the labels that each got.

#2999 docs: fix typo of grafanalgtm -> grafana-lgtm module package
  docs/modules/grafana-lgtm.md
Labels: documentation

#3010 docs: correct container variable
  docs/features/creating_container.md
Labels: documentation

#3012 docs: refine texts on how to set the module image
  docs/modules/artemis.md
  docs/modules/azurite.md
  docs/modules/cassandra.md
  docs/modules/chroma.md
  docs/modules/clickhouse.md
  docs/modules/cockroachdb.md
  docs/modules/consul.md
  docs/modules/couchbase.md
  docs/modules/databend.md
  docs/modules/dolt.md
  docs/modules/dynamodb.md
  docs/modules/elasticsearch.md
  docs/modules/etcd.md
  docs/modules/gcloud.md
  docs/modules/grafana-lgtm.md
  docs/modules/inbucket.md
  docs/modules/influxdb.md
  docs/modules/k3s.md
  docs/modules/k6.md
  docs/modules/kafka.md
  docs/modules/localstack.md
  docs/modules/mariadb.md
  docs/modules/meilisearch.md
  docs/modules/milvus.md
  docs/modules/minio.md
  docs/modules/mockserver.md
  docs/modules/mongodb.md
  docs/modules/mssql.md
  docs/modules/mysql.md
  docs/modules/nats.md
  docs/modules/neo4j.md
  docs/modules/ollama.md
  docs/modules/openfga.md
  docs/modules/openldap.md
  docs/modules/opensearch.md
  docs/modules/pinecone.md
  docs/modules/postgres.md
  docs/modules/pulsar.md
  docs/modules/qdrant.md
  docs/modules/rabbitmq.md
  docs/modules/redis.md
  docs/modules/redpanda.md
  docs/modules/registry.md
  docs/modules/scylladb.md
  docs/modules/surrealdb.md
  docs/modules/valkey.md
  docs/modules/vault.md
  docs/modules/vearch.md
  docs/modules/weaviate.md
  docs/modules/yugabytedb.md
  modulegen/_template/module.md.tmpl
  modulegen/main_test.go
Labels: documentation

#3007 chore(ci): use new GH action for SonarQube
  .github/workflows/ci-test-go.yml
  .github/workflows/ci.yml
  modulegen/_template/sonar-project.properties.tmpl
  modulegen/cmd/modules/main.go
  modulegen/internal/context/context.go
  modulegen/internal/main.go
  modulegen/internal/sonar/main.go
  modulegen/internal/sonar/types.go
  modulegen/main_test.go
  scripts/changed-modules.sh
  scripts/pre-release.sh
  scripts/release.sh
  sonar-project.properties
Labels: chore

#3034 fix: pass secret to the reusable workflow
  .github/workflows/ci-test-go.yml
  .github/workflows/ci.yml
Labels: chore

#3035 fix: use empty dir for the core
  .github/workflows/ci-test-go.yml
Labels: chore

#3036 fix(ci): update core path in sonar build
  .github/workflows/ci-test-go.yml
Labels: chore

#3037 fix(sonar): run on ubuntu and the lowest Go version
  .github/workflows/ci-test-go.yml
  scripts/bump-go.sh
Labels: chore

#3038 chore(sonar): set main as default branch
  .github/workflows/ci-test-go.yml
Labels: chore

#2953 chore!: export DockerCompose type in compose package
  modules/compose/compose.go
  modules/compose/compose_api.go
  modules/compose/compose_api_test.go
  modules/compose/compose_local.go
Labels: breaking change

#3041 deps(compose): bump compose to v2.34.0 and compose-go to v2.4.9
  docs/features/docker_compose.md
  modules/compose/compose_examples_test.go
  modules/compose/compose_local_examples_test.go
  modules/compose/compose_test.go
  modules/compose/go.mod
  modules/compose/go.sum
Labels: dependencies, compose

#3039 chore(ci): manage Sonar projects from Github actions
  .github/scripts/sonar-manager.sh
  .github/workflows/sonar-bulk-operations.yml
  .github/workflows/sonar-create-project.yml
  .github/workflows/sonar-delete-project.yml
  .gitignore
  scripts/changed-modules.sh
Labels: chore

#3045 fix(ci): update sonar script path in the GH actions
  .github/workflows/sonar-bulk-operations.yml
  .github/workflows/sonar-delete-project.yml
Labels: chore

#3059 chore(deps): bump golang.org/x/net from 0.23.0 to 0.36.0 in /modules/dynamodb
  modules/dynamodb/go.mod
  modules/dynamodb/go.sum
Labels: dependencies, security

#3060 chore: dockerise docs build
  .gitignore
  Makefile
  docs/contributing.md
Labels: chore

#3032 fix: skip nil strategies in wait.ForAll
  wait/all.go
  wait/all_test.go
Labels: bug

#3047 fix(portforward): stop port-forward from the beforeStop container hook to the afterStop
  port_forwarding.go
Labels: bug

#3068 chore: fixed comment typo in InfluxDB
  modules/influxdb/influxdb.go
Labels: chore

#3073 fix(dind): use docker image load
  modules/dind/dind.go
  modules/dind/dind_test.go
Labels: bug
