Repository testcontainers/testcontainers-go, pull requests merged in 2025-05, with the labels that each got.

#3126 docs(redpanda): update sasl authentication option to use scram sha 256
  docs/modules/redpanda.md
  modules/redpanda/options.go
Labels: documentation

#3156 feat: add more functional options for customising containers
  docs/features/common_functional_options.md
  docs/modules/index.md
  network/network.go
  network/network_test.go
  options.go
  options_test.go
Labels: feature

#3158 fix(wait): no port to wait for
  wait/host_port.go
  wait/host_port_test.go
Labels: bug

#3162 fix(etcd): expose ports for the etcd nodes
  modules/etcd/etcd.go
Labels: bug

#3161 feat: support adding wait strategies as functional option
  docs/features/common_functional_options.md
  docs/modules/index.md
  modules/k3s/k3s_test.go
  modules/localstack/examples_test.go
  modules/mongodb/examples_test.go
  modules/mssql/mssql_test.go
  modules/postgres/examples_test.go
  modules/postgres/postgres_test.go
  modules/postgres/wait_strategies.go
  options.go
  options_test.go
Labels: feature

#3164 chore(ci): do not fail fast in the Testcontainers Cloud run
  .github/workflows/ci.yml
Labels: chore

#3166 fix(ci): do not run sonar for Testcontainers Cloud
  .github/workflows/ci-test-go.yml
Labels: chore
