Repository testcontainers/testcontainers-go, pull requests merged in 2025-02, with the labels that each got.

#2956 deps(fix): include modulegen templates dir in dependabot updates
  .github/dependabot.yml
  modulegen/_template/ci.yml.tmpl
Labels: dependencies

#2962 fix(valkey): fix port race
  modules/valkey/valkey.go
Labels: bug

#2876 chore(ci): run lint in a separate build before running the tests
  .github/dependabot.yml
  .github/workflows/ci-lint-go.yml
  .github/workflows/ci-test-go.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/docker-moby-latest.yml
  .github/workflows/scorecards.yml
  modulegen/_template/ci.yml.tmpl
  modulegen/internal/main.go
  modulegen/internal/workflow/main.go
  modulegen/internal/workflow/types.go
  modulegen/main_test.go
  scripts/bump-go.sh
  scripts/changed-modules.sh
Labels: chore

#2974 fix(ci): use same condition for sonar steps
  .github/workflows/ci-test-go.yml
Labels: chore

#2967 chore!: remove variadic arguments from nats ConnectionString
  docs/modules/nats.md
  modules/nats/nats.go
Labels: breaking change

#2978 chore: enable var-naming from revive (private vars only)
  .golangci.yml
  commons-test.mk
  docker_test.go
  examples/toxiproxy/toxiproxy_test.go
  modules/consul/consul.go
  modules/consul/examples_test.go
  modules/couchbase/couchbase.go
  modules/dolt/dolt.go
  modules/grafana-lgtm/examples_test.go
  modules/grafana-lgtm/grafana.go
  modules/inbucket/inbucket.go
  modules/inbucket/inbucket_test.go
  modules/influxdb/influxdb.go
  modules/influxdb/influxdb_test.go
  modules/k3s/k3s.go
  modules/k6/k6.go
  modules/nats/nats_test.go
  modules/neo4j/neo4j.go
  modules/neo4j/neo4j_test.go
  modules/ollama/local_test.go
  modules/openfga/openfga.go
  modules/pinecone/pinecone.go
  modules/qdrant/examples_test.go
  modules/rabbitmq/rabbitmq.go
  modules/redpanda/redpanda.go
  modules/redpanda/redpanda_test.go
  modules/vault/vault.go
  modules/weaviate/weaviate.go
  network/network_test.go
  wait/sql.go
  wait/sql_test.go
Labels: chore

#2989 docs: remove duplicated options in the customisers lists
  docs/modules/index.md
Labels: documentation

#2979 feat!: log package for consistent output
  container.go
  container_test.go
  docker.go
  docker_client.go
  docker_mounts.go
  docker_test.go
  docs/features/common_functional_options.md
  docs/modules/neo4j.md
  file.go
  from_dockerfile_test.go
  generic.go
  lifecycle.go
  log/logger.go
  logconsumer_test.go
  logger.go
  logger_option.go
  logger_option_test.go
  modules/compose/compose.go
  modules/compose/compose_api.go
  modules/compose/compose_api_test.go
  modules/compose/compose_local.go
  modules/compose/compose_test.go
  modules/grafana-lgtm/grafana.go
  modules/k3s/k3s.go
  modules/localstack/localstack.go
  modules/neo4j/config.go
  modules/neo4j/neo4j.go
  modules/neo4j/neo4j_test.go
  modules/postgres/postgres.go
  modules/rabbitmq/rabbitmq.go
  provider.go
  reaper.go
  wait/exec_test.go
  wait/host_port.go
  wait/host_port_test.go
  wait/http_test.go
  wait/tls_test.go
Labels: feature, breaking change

#2966 chore(ollama): bump default version to 0.5.7
  docs/features/wait/log.md
  docs/modules/ollama.md
  modules/ollama/examples_test.go
  modules/ollama/ollama.go
  modules/ollama/ollama_test.go
Labels: dependencies

#2975 feat(redpanda): add bootstrap user account option
  docs/modules/redpanda.md
  modules/redpanda/admin_api.go
  modules/redpanda/options.go
  modules/redpanda/redpanda.go
  modules/redpanda/redpanda_test.go
Labels: feature

#2991 chore(ci): add an end job to verify the pipeline finished with success
  .github/settings.yml
  .github/workflows/ci.yml
Labels: chore

#2993 fix(ci): exclude mkdocs.yml file and sonar.properties from the changed-modules script
  scripts/changed-modules.sh
Labels: chore

#2994 chore: enable empty-block from revive
  .golangci.yml
  logconsumer_test.go
Labels: chore

#2992 feat: add ScyllaDB module
  .vscode/.testcontainers-go.code-workspace
  docs/modules/scylladb.md
  mkdocs.yml
  modules/scylladb/Makefile
  modules/scylladb/examples_test.go
  modules/scylladb/go.mod
  modules/scylladb/go.sum
  modules/scylladb/scylladb.go
  modules/scylladb/scylladb_test.go
  modules/scylladb/testdata/scylla.yaml
  sonar-project.properties
Labels: feature
