Repository testcontainers/testcontainers-go, pull requests merged in 2025-04, with the labels that each got.

#3075 chore(deps): replace `golang.org/x/exp/slices` with stdlib
  modulegen/go.mod
  modulegen/go.sum
  modulegen/internal/mkdocs/types.go
Labels: dependencies

#3074 docs: add dependabot configuration
  docs/dependabot.md
  mkdocs.yml
  modulegen/internal/mkdocs/types.go
Labels: documentation

#3082 chore: bump golangci-lint to v2
  .github/workflows/ci-lint-go.yml
  .golangci.yml
  commons-test.mk
  container.go
  docker.go
  docker_client.go
  docs/features/wait/walk.md
  internal/core/bootstrap.go
  internal/core/docker_host_test.go
  modules/cassandra/cassandra_test.go
  modules/clickhouse/clickhouse.go
  modules/clickhouse/clickhouse_test.go
  modules/cockroachdb/cockroachdb.go
  modules/compose/compose_local.go
  modules/consul/consul.go
  modules/couchbase/couchbase.go
  modules/dind/dind.go
  modules/dolt/dolt.go
  modules/elasticsearch/elasticsearch.go
  modules/gcloud/bigquery/bigquery_test.go
  modules/gcloud/bigtable/bigtable_test.go
  modules/gcloud/bigtable/examples_test.go
  modules/gcloud/spanner/examples_test.go
  modules/gcloud/spanner/spanner_test.go
  modules/grafana-lgtm/grafana.go
  modules/inbucket/inbucket.go
  modules/influxdb/influxdb.go
  modules/influxdb/influxdb_test.go
  modules/k3s/k3s.go
  modules/k6/k6.go
  modules/localstack/localstack.go
  modules/meilisearch/meilisearch_test.go
  modules/mongodb/mongodb.go
  modules/mssql/mssql_test.go
  modules/neo4j/neo4j.go
  modules/ollama/local.go
  modules/ollama/local_test.go
  modules/openfga/openfga.go
  modules/pinecone/pinecone.go
  modules/rabbitmq/rabbitmq.go
  modules/redpanda/redpanda.go
  modules/registry/registry.go
  modules/vault/vault.go
  modules/weaviate/weaviate.go
  options_test.go
  parallel_test.go
  wait/http.go
  wait/http_test.go
  wait/walk.go
  wait/walk_test.go
Labels: chore, dependencies

#3084 fix(mssql): reduce flakiness in tests
  modules/mssql/Makefile
Labels: chore

#3071 feat: add socat container
  .github/dependabot.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/socat.md
  mkdocs.yml
  modules/socat/Makefile
  modules/socat/examples_test.go
  modules/socat/go.mod
  modules/socat/go.sum
  modules/socat/options.go
  modules/socat/options_test.go
  modules/socat/socat.go
  modules/socat/socat_test.go
  testing.go
Labels: feature

#3083 feat: add arangodb module
  .github/dependabot.yml
  .vscode/.testcontainers-go.code-workspace
  docs/modules/arangodb.md
  mkdocs.yml
  modules/arangodb/Makefile
  modules/arangodb/arangodb.go
  modules/arangodb/arangodb_test.go
  modules/arangodb/examples_test.go
  modules/arangodb/go.mod
  modules/arangodb/go.sum
  modules/arangodb/options.go
Labels: feature

#3070 feat: add more functional options to the modules API
  container.go
  docker.go
  docker_test.go
  docs/features/common_functional_options.md
  docs/features/creating_container.md
  docs/modules/index.md
  docs/modules/localstack.md
  examples_test.go
  from_dockerfile_test.go
  generic.go
  lifecycle.go
  logconsumer_test.go
  modules/dind/dind.go
  modules/k3s/k3s.go
  modules/localstack/examples_test.go
  modules/redpanda/go.mod
  modules/redpanda/redpanda.go
  modules/vearch/go.mod
  modules/vearch/vearch.go
  options.go
  options_test.go
  reaper.go
  reaper_test.go
Labels: feature

#3095 security(compose): upgrade github.com/docker/compose/v2 to fix security vulnerability
  modules/compose/go.mod
  modules/compose/go.sum
Labels: dependencies, security, compose

#3094 feat(aerospike): add Aerospike module
  .github/dependabot.yml
  docs/modules/aerospike.md
  mkdocs.yml
  modules/aerospike/Makefile
  modules/aerospike/aerospike.go
  modules/aerospike/aerospike_test.go
  modules/aerospike/examples_test.go
  modules/aerospike/go.mod
  modules/aerospike/go.sum
Labels: enhancement

#3100 chore(pulsar): bump github.com/apache/pulsar-client-go from 0.10.0 to 0.14.0
  modules/pulsar/go.mod
  modules/pulsar/go.sum
Labels: dependencies, security

#3102 docs: fix reference to container types in Run function
  docs/modules/aerospike.md
  docs/modules/arangodb.md
  docs/modules/azure.md
  docs/modules/dind.md
  docs/modules/etcd.md
  docs/modules/pinecone.md
  docs/modules/scylladb.md
  docs/modules/socat.md
  modulegen/_template/module.md.tmpl
  modulegen/main_test.go
Labels: documentation

#3103 chore(ci): run codeql on the modified modules
  .github/workflows/codeql.yml
Labels: chore

#3107 deps(ci): use python 3.13 on Netlify deployments
  Makefile
  Pipfile
  runtime.txt
Labels: dependencies

#3108 chore(ci): reduce GH runners usage by calling codeql in the lint stage
  .github/workflows/ci-lint-go.yml
  .github/workflows/codeql.yml
Labels: chore

#3110 deps: use pinned dependencies on GH actions
  .github/workflows/docker-projects-latest.yml
  .github/workflows/sonar-bulk-operations.yml
  .github/workflows/sonar-create-project.yml
  .github/workflows/sonar-delete-project.yml
Labels: dependencies

#3111 docs(socat): add missing version marker for new options
  docs/modules/socat.md
Labels: documentation

#3112 chore(ci): revert codeql improvements for CI resiliency
  .github/workflows/ci-lint-go.yml
  .github/workflows/codeql.yml
Labels: chore

#3116 deps(aerospike): replace core module in go.mod
  modules/aerospike/go.mod
  modules/aerospike/go.sum
Labels: dependencies

#3117 chore(ci): run core tests on Testcontainers Cloud
  .github/workflows/ci-test-go.yml
  .github/workflows/ci.yml
Labels: chore

#3092 feat: add toxiproxy module
  .github/dependabot.yml
  .vscode/.testcontainers-go.code-workspace
  docs/examples/toxiproxy.md
  docs/modules/toxiproxy.md
  examples/toxiproxy/redis.go
  examples/toxiproxy/toxiproxy.go
  examples/toxiproxy/toxiproxy_test.go
  mkdocs.yml
  modules/toxiproxy/Makefile
  modules/toxiproxy/config.go
  modules/toxiproxy/examples_test.go
  modules/toxiproxy/go.mod
  modules/toxiproxy/go.sum
  modules/toxiproxy/options.go
  modules/toxiproxy/options_test.go
  modules/toxiproxy/testdata/toxiproxy.json
  modules/toxiproxy/toxiproxy.go
  modules/toxiproxy/toxiproxy_test.go
Labels: feature

#3115 feat(redis): add TLS support
  docs/modules/redis.md
  modules/postgres/go.mod
  modules/postgres/go.sum
  modules/redis/examples_test.go
  modules/redis/go.mod
  modules/redis/go.sum
  modules/redis/options.go
  modules/redis/options_test.go
  modules/redis/redis.go
  modules/redis/redis_test.go
  modules/toxiproxy/go.mod
  modules/toxiproxy/go.sum
Labels: feature

#3121 feat(postgres): add WithOrderedInitScripts for Postgres testcontainers
  docs/modules/postgres.md
  modules/postgres/postgres.go
  modules/postgres/postgres_test.go
  modules/postgres/testdata/aaaa-insert-user.sql
Labels: feature

#3072 feat(influxdb): support for influxdbv2
  docs/modules/influxdb.md
  modules/influxdb/examples_test.go
  modules/influxdb/go.mod
  modules/influxdb/go.sum
  modules/influxdb/influxdb.go
  modules/influxdb/influxdb_test.go
Labels: enhancement

#3122 chore(ci): exclude more files for a full-blown build
  scripts/changed-modules.sh
Labels: chore

#3123 chore(ci): close PR if it was sent from main
  .github/workflows/conventions.yml
Labels: chore

#3044 feat: support for mounting images
  docker_mounts.go
  docs/features/common_functional_options.md
  docs/features/files_and_mounts.md
  lifecycle.go
  lifecycle_test.go
  modules/ollama/examples_test.go
  mounts.go
  mounts_test.go
  options.go
  options_test.go
  validator.go
Labels: feature

#3009 feat(gcloud): add option to run firestore in datastore mode
  docs/modules/gcloud.md
  modules/gcloud/firestore/examples_test.go
  modules/gcloud/firestore/firestore.go
  modules/gcloud/firestore/firestore_test.go
  modules/gcloud/firestore/options.go
Labels: enhancement

#3062 fix: handle stopped containers more gracefully when reuse is enabled
  docker.go
  reuse_test.go
Labels: bug

#3130 fix(localstack): remove checksum from image name before parsing version
  modules/localstack/localstack.go
  modules/localstack/localstack_test.go
Labels: bug

#3125 fix(dockermodelrunner): wait for the model to be pulled
  docs/modules/dockermodelrunner.md
  modules/dockermodelrunner/dockermodelrunner_test.go
  modules/dockermodelrunner/examples_test.go
  modules/dockermodelrunner/internal/sdk/client/pull.go
Labels: bug

#3131 feat(valkey): add TLS support for Valkey
  docs/modules/redis.md
  docs/modules/valkey.md
  modules/valkey/examples_test.go
  modules/valkey/go.mod
  modules/valkey/go.sum
  modules/valkey/options.go
  modules/valkey/valkey.go
  modules/valkey/valkey_test.go
Labels: feature
