Repository testcontainers/testcontainers-go, pull requests merged in 2025-06, with the labels that each got.

#3195 chore: bump ryuk to 0.12.0
  internal/config/config.go
Labels: dependencies

#3198 fix: try to fix more IPv6 handling issues
  docker.go
  examples/nginx/nginx.go
  lifecycle.go
  modules/azure/azurite/azurite.go
  modules/cassandra/cassandra.go
  modules/chroma/chroma.go
  modules/clickhouse/clickhouse.go
  modules/consul/consul.go
  modules/couchbase/couchbase.go
  modules/databend/databend.go
  modules/dolt/dolt.go
  modules/dynamodb/dynamodb.go
  modules/elasticsearch/elasticsearch.go
  modules/etcd/etcd.go
  modules/gcloud/bigquery.go
  modules/gcloud/gcloud.go
  modules/grafana-lgtm/go.mod
  modules/grafana-lgtm/grafana.go
  modules/k3s/k3s.go
  modules/ollama/local.go
  modules/redis/redis.go
Labels: bug

#3215 docs: document copy from container
  docs/features/files_and_mounts.md
  examples_test.go
Labels: documentation

#3220 deps: update testcontainers/sshd image to 1.3.0
  port_forwarding.go
Labels: dependencies, security
