Repository testcontainers/testcontainers-go, pull requests merged in 2025-01, with the labels that each got.

#2926 feat(termination)!: make container termination timeout configurable
  cleanup.go
  container.go
  docker.go
  docker_test.go
  docs/features/garbage_collector.md
  modules/etcd/etcd.go
  port_forwarding.go
Labels: feature, breaking change

#2923 feat(ollama): support calling the Ollama local process
  .github/scripts/modules/ollama/install-dependencies.sh
  .github/workflows/ci-test-go.yml
  docs/modules/ollama.md
  modules/ollama/examples_test.go
  modules/ollama/go.mod
  modules/ollama/local.go
  modules/ollama/local_test.go
  modules/ollama/ollama.go
  modules/ollama/options.go
  modules/ollama/options_test.go
Labels: feature

#2473 feat(postgres): ssl for postgres
  docs/modules/postgres.md
  modules/postgres/go.mod
  modules/postgres/go.sum
  modules/postgres/postgres.go
  modules/postgres/postgres_test.go
  modules/postgres/resources/customEntrypoint.sh
  modules/postgres/testdata/postgres-ssl.conf
Labels: feature

#2938 deps(compose): bump compose (v2.32.2) and compose-go spec (v2.4.7)
  modules/compose/go.mod
  modules/compose/go.sum
Labels: dependencies, compose

#2939 chore: recover from panic in `SkipIfProviderIsNotHealthy` test helper function
  testing.go
Labels: chore

#2936 fix(localstack): more reliable legacy tag detection
  modules/localstack/localstack.go
  modules/localstack/localstack_test.go
Labels: bug

#2941 chore!: rename EnpointSettingsModifier to EndpointSettingsModifier
  container.go
  lifecycle.go
  lifecycle_test.go
  options.go
  reaper_test.go
Labels: breaking change

#2947 chore: enable early-return, indent-error-flow and superfluous-else from revive linter
  .golangci.yml
  container.go
  docker.go
  internal/core/docker_rootless.go
  modules/compose/compose_api.go
  modules/registry/registry.go
  wait/exit.go
Labels: chore

#2942 chore: enable var-declaration from revive linter
  .golangci.yml
  container.go
  internal/config/config.go
  internal/core/images_test.go
  modules/dynamodb/dynamodb_test.go
Labels: chore

#2950 chore(deps): bump golangci-lint to v1.63.4
  commons-test.mk
  modules/ollama/local_test.go
Labels: chore

#2948 chore: enable use-any from revive
  .golangci.yml
  lifecycle_test.go
  logger.go
  modulegen/internal/mkdocs/types.go
  modules/chroma/examples_test.go
  modules/compose/compose_builder_test.go
  modules/compose/compose_local.go
  modules/gcloud/spanner_test.go
  modules/grafana-lgtm/grafana_test.go
  modules/mockserver/examples_test.go
  modules/neo4j/neo4j_test.go
  modules/pulsar/pulsar_test.go
  modules/rabbitmq/rabbitmq_test.go
  modules/rabbitmq/types_test.go
  modules/surrealdb/surrealdb_test.go
Labels: chore

#2949 chore: enable unused-parameter from revive
  .golangci.yml
  docker.go
  docker_auth_test.go
  internal/core/docker_host.go
  internal/core/docker_host_test.go
  lifecycle.go
  lifecycle_test.go
  logger.go
  modulegen/cmd/modules/example.go
  modulegen/cmd/modules/module.go
  modules/clickhouse/clickhouse_test.go
  modules/couchbase/options.go
  modules/dynamodb/dynamodb_test.go
  modules/gcloud/firestore_test.go
  modules/gcloud/pubsub_test.go
  modules/k6/k6.go
  modules/localstack/localstack.go
  modules/nats/nats.go
  modules/nats/options.go
  modules/ollama/local.go
  modules/ollama/options.go
  modules/openldap/openldap.go
  modules/pulsar/pulsar.go
  modules/qdrant/qdrant_test.go
  modules/redpanda/options.go
  modules/registry/registry_test.go
  modules/vearch/vearch_test.go
  modules/weaviate/weaviate_test.go
  network/network.go
  options_test.go
  port_forwarding.go
  port_forwarding_test.go
  reaper.go
  reaper_test.go
  wait/all_test.go
  wait/exec.go
  wait/exec_test.go
  wait/exit_test.go
  wait/health_test.go
  wait/http.go
  wait/sql_test.go
Labels: chore
