Repository testcontainers/testcontainers-go, pull requests merged in 2025-10, with the labels that each got.

#3327 chore(consul): use Run function
  modules/consul/consul.go
Labels: chore

#3402 chore(databend): use Run function
  modules/databend/databend.go
  modules/databend/databend_test.go
Labels: chore

#3401 chore(couchbase): use Run function
  modules/couchbase/couchbase.go
Labels: chore

#3404 chore(docker): fix error messages
  modules/dockermcpgateway/dockermcpgateway.go
  modules/dockermodelrunner/dockermodelrunner.go
Labels: chore

#3405 chore(dolt): use Run function
  modules/dolt/dolt.go
Labels: chore

#3408 chore(milvus): update Milvus SDK to new module
  docs/modules/milvus.md
  modules/milvus/examples_test.go
  modules/milvus/go.mod
  modules/milvus/go.sum
  modules/milvus/milvus.go
  modules/milvus/milvus_test.go
Labels: chore

#3412 chore(grafana): use Run function
  modules/grafana-lgtm/grafana.go
  modules/grafana-lgtm/grafana_test.go
Labels: chore

#3414 chore(k6|localstack|kafka|mariadb): use Run function
  modules/k3s/k3s.go
  modules/k6/k6.go
  modules/kafka/kafka.go
  modules/kafka/kafka_helpers_test.go
  modules/localstack/localstack.go
  modules/localstack/localstack_test.go
  modules/localstack/types.go
  modules/mariadb/mariadb.go
  modules/mariadb/mariadb_test.go
Labels: chore

#3415 chore(meilisearch|memcached|milvus|minio|mockserver|mssql): use Run function
  modules/meilisearch/meilisearch.go
  modules/memcached/memcached.go
  modules/milvus/milvus.go
  modules/minio/minio.go
  modules/mockserver/mockserver.go
  modules/mssql/mssql.go
Labels: chore

#3417 docs(mssql): describe MSSQL issue with negative certificates
  docs/modules/mssql.md
Labels: documentation

#3416 chore(mysql): use Run function
  modules/mysql/mysql.go
  modules/mysql/mysql_test.go
Labels: chore

#3418 chore(nats): use Run function
  modules/nats/nats.go
Labels: chore

#3421 chore(openfga): use Run function
  modules/openfga/openfga.go
Labels: chore

#3424 chore(pinecone): use Run function
  modules/pinecone/pinecone.go
Labels: chore

#3423 chore(opensearch)!: use Run function
  modules/opensearch/opensearch.go
  modules/opensearch/options.go
Labels: breaking change

#3428 chore(rabbitmq)!: use Run function
  modules/rabbitmq/options.go
  modules/rabbitmq/rabbitmq.go
  modules/rabbitmq/rabbitmq_test.go
Labels: breaking change

#3430 chore(redpanda)!: use Run function
  modules/redpanda/options.go
  modules/redpanda/redpanda.go
Labels: breaking change
